### ISSUE TITLE
Forward chain

### ISSUE THREAD

**Issue by manchelsi** [Waujito/youtubeUnblock#1]
How can this be done not in the Output chain, but in the Forward chain, for use in a router?

**Comment by Waujito** [comment]
Hi! 
Just tested it on my host with docker container and it works out-of-the box. But it anyways needs in further testing. Also I'm unsure about Chrome's Client Hello TCP Segmentation on router. 

Note that for router the cross-compilation is required. To simplify the process I think it's prefferable to compile dependency libraries alongside with the application and link them statically. 
I am working around it.

**Comment by Waujito** [comment]
Can confirm, it works. I think on router it is even simpler because of no GSO. 
Now the scary thing is to document out guideline for openwrt and cross-compilation and dive into openwrt [procd init scripts](https://openwrt.org/docs/guide-developer/procd-init-scripts#procd_init_scripts)

**Comment by manchelsi** [comment]
If I enter -t mangle FORWARD I get the following:
<img width="1278" alt="Снимок экрана 2024-07-23 в 11 41 01" src="https://github.com/user-attachments/assets/36309a8c-b0ae-4063-9ef2-65980a5c7d6e">

**Comment by Waujito** [comment]
Can reproduce. I think that this is related to RKN. It seems like they started to drop fragmented IP requests. After I set up transmision via a transparent proxy on tor everything started to work. The solution will be to do the fragmentation on TCP layer instead of IP.

**Comment by Waujito** [comment]
Can you please test this PR? I forked it from main branch so for cross-compilation you may need merge it with previous one.

**Comment by manchelsi** [comment]
Yes it works!
<img width="1278" alt="Снимок экрана 2024-07-23 в 17 51 27" src="https://github.com/user-attachments/assets/3efde4cc-5d8c-4b12-92be-26212c7e1be6">

**Comment by manchelsi** [comment]
It works, with the provider Ertelecom, with the provider Rostelecom the video does not load, in the debug I see: Packet split in portion 193 428
Google video!
Packet split in portion 193 428
raw frags send: Operation not permitted
Google video!
Packet split in portion 193 428
Google video!
Packet split in portion 193 428
Google video!
Packet split in portion 193 428

**Comment by Waujito** [comment]
Interesting. `raw frags send` indicates that the error is somewhere inside the `send_raw_socket` function. Did you change the router? Can you debug it yourself and tell me which error handler breaks? Just add printf on each return statement and check which one executes. Also you can set errno = 0 on top of the function to exclude possibility of earlier error.

`Operation not permitted` is not documented in the sendto manual so may be the error is related to something else.

I updated the 1-tcp-segmentation branch. I've noticed an outperformance for my router and optimizing the code now. I also added more error handlers to it.

**Comment by manchelsi** [comment]
Yes, the problem is not in your program. I have 2 providers connected at the same time. Now I have disabled Ertelecom and redirected the traffic only to Rostelecom, everything works.
It seems that with the latest commit in the 1-tcp-segmentation branch it works even better.

**Comment by Waujito** [comment]
So did the problem solve? The program works on IP level and should be unrelated to that staff with multiple providers/multiple clients. I'm scared of that Operation not permitted. Can you reproduce the error now?

**Comment by manchelsi** [comment]
strace:
sendto(4, "E\0\1\256\243\341@\0?\6@\357\n\354f\274@\351\242]\245\"\1\273!\301\352\366m-3\364"..., 430, 0, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("64.233.162.93")}, 16) = -1 EPERM (Операция не позволена)
dup(2)                                  = 5                                                                                                  fcntl(5, F_GETFL)                       = 0x402 (flags O_RDWR|O_APPEND)
newfstatat(5, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x11), ...}, AT_EMPTY_PATH) = 0                                               write(5, "raw frags send: Operation not pe"..., 40raw frags send: Operation not permitted                                                    ) = 40
close(5)                                = 0

**Comment by manchelsi** [comment]
I think you shouldn’t bother, since everything works separately.

**Comment by Waujito** [comment]
Ok, I will merge 1-tcp-segmentation to main. 
Idk how to help you with EPERM. I see that this occures in sendto but here is not a lot information about it. May be https://stackoverflow.com/questions/74522604/how-to-fix-eperm-error-when-trying-to-use-sendto-with-ethernet-socketaf will be helpful.

**Comment by Waujito** [comment]
Github closed it automatically but if the problem keeps or you wish to proceed with that EPERM, we can reopen.
