### ISSUE TITLE
TSPU Update 01 Aug

### ISSUE THREAD

**Issue by hukarere** [Waujito/youtubeUnblock#10]
Hello,

I tried it on Ubuntu 22.04, where youtube is slowed down without youtubeUnblock, but the playback either stops completely when it is running or keeps as slow as it was. I built it with "make dev" and when attempting to play something, it is correctly writing  "Google video! Packet split in portion 198 599", but It does not help.

That's in Firefox, tested with both http3 enabled and disabled in about:config.

However, when I try the curl command mentioned in the habr article for testing:
``curl --connect-to ::speedtest.selectel.ru https://manifest.googlevideo.com/100MB -k -o/dev/null``
-- it does work and running youtubeUnblock really mitigates the slowdown!

Any suggestions?

**Comment by hukarere** [comment]
P.S. I tried to also test it in chromium and edge, but just about an hour ago youtube stopped working for me completely in these two browsers, whereas in firefox it is still working (slowed down).

**Comment by imnethen** [comment]
similar issue. works perfectly in curl test but doesnt do anything in firefox. it does work for me in chromium though

**Comment by Waujito** [comment]
Hello!

Wireshark logs will be helpful to make sure that it is not the package internal issue, but some TSPU got updated. In Wireshark you can pickle packets and send them to me. You can filter it by ip address. I interested in example that holds first handshake packets and demonstration of the shaping from TSPU.

As of now, for me it works on Rostelecom.

**Comment by Waujito** [comment]
> similar issue. works perfectly in curl test but doesnt do anything in firefox. it does work for me in chromium though

Did you try to disable quic? network.http(2,3).enable(d) in about:config

**Comment by Waujito** [comment]
Also helpful may be the feedback about your experience in yt-dlp as it is lightweight and uses only tcp.

**Comment by imnethen** [comment]
disabling quic doesnt seem to do anything (ive tried every combination of http 2 and 3 and restarting the browser)
yt-dlp works very slowly without youtubeUnblock but doesnt work at all with it (time out error)

**Comment by Waujito** [comment]
Can you report the normal network speed: 
```curl -o/dev/null https://speedtest.selectel.ru/100MB```

Selectel speedtest with googlevideo sni speed for enabled/disabled youtubeUnblock:
```curl -o/dev/null --connect-to ::speedtest.selectel.ru https://test.googlevideo.com/100MB -k```

Network speed with Normal google IP: 
```curl -o/dev/null -k --connect-to ::google.com -k -L -H Host:\ mirror.gcr.io https://mirror.gcr.io/v2/cimg/android/blobs/sha256:6fd8bdac3da660bde7bd0b6f2b6a46e1b686afb74b9a4614def32532b73f5eaa```

And network speed with that ip with googlevideo SNI for enabled/disabled youtubeUnblock: 
```curl -o/dev/null -k --connect-to ::google.com -k -L -H Host:\ mirror.gcr.io https://test.googlevideo.com/v2/cimg/android/blobs/sha256:6fd8bdac3da660bde7bd0b6f2b6a46e1b686afb74b9a4614def32532b73f5eaa```

**Comment by Baldie27** [comment]
Doesn't work for me anywhere (tried Firefox, Chromium, Vivaldi). Disabled quic and Kyber in all browsers. (MGTS provider)

**Comment by Waujito** [comment]
Hello! I added the delay option for 2nd packet. Can you please test it? 
You also can play around with `#define SEG2_DELAY 100` where 100 stands for delay in milliseconds.

**Comment by ylyxa** [comment]
With the delay Firefox plain stops loading videos. Chrome still works fine, curl test is also fine.

**Comment by imnethen** [comment]
> Can you report the normal network speed: `curl -o/dev/null https://speedtest.selectel.ru/100MB`
> 
> Selectel speedtest with googlevideo sni speed for enabled/disabled youtubeUnblock: `curl -o/dev/null --connect-to ::speedtest.selectel.ru https://test.googlevideo.com/100MB -k`
> 
> Network speed with Normal google IP: `curl -o/dev/null -k --connect-to ::google.com -k -L -H Host:\ mirror.gcr.io https://mirror.gcr.io/v2/cimg/android/blobs/sha256:6fd8bdac3da660bde7bd0b6f2b6a46e1b686afb74b9a4614def32532b73f5eaa`
> 
> And network speed with that ip with googlevideo SNI for enabled/disabled youtubeUnblock: `curl -o/dev/null -k --connect-to ::google.com -k -L -H Host:\ mirror.gcr.io https://test.googlevideo.com/v2/cimg/android/blobs/sha256:6fd8bdac3da660bde7bd0b6f2b6a46e1b686afb74b9a4614def32532b73f5eaa`
> 
> I have tested the program now and can say that they broke googlevideo speed even more but with youtubeUnblock everything works perfect for me.
> 
> UPD: Also you may experiment with curl request directly to googlevideo video. This thing will give the clearest results. Please, check the [yt-dlp/yt-dlp#10443 (comment)](https://github.com/yt-dlp/yt-dlp/issues/10443#issuecomment-2237395791) yt-dlp reports the download link with `--print-traffic`. You may inject it to the curl request and playaround with SNI:
> 
> ```
>  curl https://rr3---sn-4g5edndz.googlevideo.com/videoplayback/id/2d76f710a5ac2274/itag/642/source/youtube/expire/1722521173/ei/9UGrZrOzKrTCv_IPrPiY8Ag/ip/65.107.46.73/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D1135566526%3Bdur%3D313.779%3Bgir%3Dyes%3Bitag%3D337%3Blmt%3D1711474575024876/rqh/1/hls_chunk_host/rr3---sn-4g5edndz.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/NH/mm/31/mn/sn-4g5edndz/ms/au/mv/m/mvi/3/pl/24/initcwndbps/152500/vprv/1/playlist_type/DVR/txp/4502434/mt/1722499247/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,vprv,playlist_type/sig/AJfQdSswRQIhAKy1Iu54mPoVyWD2nmmj2BNxqSoDEvdiq8_0C-bmSJP0AiAF-bgOdvuVFX7mywTf4IMerPQivBS6qa5RjzRkEj3YtQ%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AGtxev0wRAIgSN6Kcnbv7G2e7lkkrZljKgVqJ_NnlR0a4n-X655eaEICIFR9NqZnDcP3RklNm_YQCm4YUzVv0oRyevopyakCvXaf/playlist/index.m3u8/govp/slices%3D0-319,18190919-36435612/gosq/1/file/seg.ts -H "Host: rr3---sn-4g5edndz.googlevideo.com" -o/dev/null
> ```
> 
> ```
>  curl --connect-to ::rr3---sn-4g5edndz.googlevideo.com https://yandex.ru/videoplayback/id/2d76f710a5ac2274/itag/642/source/youtube/expire/1722521173/ei/9UGrZrOzKrTCv_IPrPiY8Ag/ip/65.107.46.73/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D1135566526%3Bdur%3D313.779%3Bgir%3Dyes%3Bitag%3D337%3Blmt%3D1711474575024876/rqh/1/hls_chunk_host/rr3---sn-4g5edndz.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/NH/mm/31/mn/sn-4g5edndz/ms/au/mv/m/mvi/3/pl/24/initcwndbps/152500/vprv/1/playlist_type/DVR/txp/4502434/mt/1722499247/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,vprv,playlist_type/sig/AJfQdSswRQIhAKy1Iu54mPoVyWD2nmmj2BNxqSoDEvdiq8_0C-bmSJP0AiAF-bgOdvuVFX7mywTf4IMerPQivBS6qa5RjzRkEj3YtQ%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AGtxev0wRAIgSN6Kcnbv7G2e7lkkrZljKgVqJ_NnlR0a4n-X655eaEICIFR9NqZnDcP3RklNm_YQCm4YUzVv0oRyevopyakCvXaf/playlist/index.m3u8/govp/slices%3D0-319,18190919-36435612/gosq/1/file/seg.ts -H "Host: rr3---sn-4g5edndz.googlevideo.com" -o/dev/null -k
> ```


Normal network speed is around 9.3M
Second test is very slow without youtubeUnblock (starts at 30000 and quickly drops down), even slower with it but much faster with the delay fix (~900K)
Third test is the same as normal network speed
Fourth test without youtubeUnblock is slow (starts at 100K and quickly drops down) and as fast as normal network speed with youtubeUnblock (both with and without delay)
The other two immediately exit after starting

The delay fix seems to have made firefox even slower but didnt affect chromium (chromium still works flawlessly)

**Comment by asuasu** [comment]
Hello! Have the same issue as topic starter, tried with SEG2_DELAY patch (with default value and 300) with no results: no video playback in any of the browsers I've tried (Safari, Chrome, Firefox), speed in curl test becomes great at the same time.
I use application on OpenWrt 22.03.2 router and see in debug mode that packets are fragmented for sure.

**Comment by Waujito** [comment]
So, I was able to reproduce it in some maner on another ISP. Now, it seems like fake SNI (random out-of-ack packet) solves the problem. Can you please try latest commit in #11

**Comment by aykhan247** [comment]
> So, I was able to reproduce it in some maner on another ISP. Now, it seems like fake SNI (random out-of-ack packet with sni=google.com) solves the problem. Can you please try the latest commit in #11

Firstly Im installed last version from master and videos not loading, but curl show max speed. After reinstall with that last commit everything works fine, thanks for your work!

**Comment by imnethen** [comment]
This commit fixes the issue, thank you!

**Comment by slesru** [comment]
I get
youtubeUnblock[58007]: Error in gen fake sni
after this video stops...

**Comment by Waujito** [comment]
> I get youtubeUnblock[58007]: Error in gen fake sni after this video stops...

Probably the problem is in nfq_ip_set_transport_header. May be ip tot_len should be specified explicitly. Anyways in the last commit I have added more reports.

**Comment by Waujito** [comment]
Also I've disabled TCP segment delay by default, prior to only fake sni by default.

**Comment by hukarere** [comment]
@Waujito,

Thanks a lot for your fixes, the 10-tspu-updated branch seems to be working for Firefox now.

```curl --connect-to ::speedtest.selectel.ru https://manifest.googlevideo.com/100MB -k -o/dev/null```
is reporting about 8KB/sec without youtubeUnblock for me and 9MB/sec with it (but it was already like that before the latest fix).

**Comment by Waujito** [comment]
Nice! So, we are ready to merge. 

Thank you all for the feedback!

**Comment by jelly8173** [comment]
Should not be blosed

Compiled for OpenWRT and tested with and without FAKE_SNI and DELAY

Firefox tends to switch to HTTP/3 and use UDP with half success avoiding slowing down by itself but not completely.

Using proxy it works completely flawless but with youtubeUnblock:

No problem with curl test, full speed comes back but firefox floods with NS_BINDING_ERROR:

![firefox errors](https://litter.catbox.moe/uq3b1s.png)

**Comment by jelly8173** [comment]
Here clean logs with proxy:

![clean logs](https://litter.catbox.moe/s5o6va.png)

**Comment by Waujito** [comment]
@jelly8173 disable quic like in #29

**Comment by jelly8173** [comment]
> @jelly8173 disable quic like in #29

disabled both (internet without http2/3 in 2024, srsly?) and it stopped working completely:
![](https://litter.catbox.moe/p8e289.png)

curl test full speed

**Comment by Waujito** [comment]
> > @jelly8173 disable quic like in #29
> 
> disabled both (internet without http2/3 in 2024, srsly?) and it stopped working completely: ![](https://camo.githubusercontent.com/909a626690faa6ebe9b28b535d8e73fbc60d69e393281e31bf63b70d4d263213/68747470733a2f2f6c69747465722e636174626f782e6d6f652f7038653238392e706e67)
> 
> curl test full speed

Do you see multiple Google video detected as well as using fake sni on start logs from youtubeUnblock?

**Comment by jelly8173** [comment]
yes! i see a lot, and i think more than one per request, console floods with
```
Packet split in portion 198 596
Google video!
Packet split in portion 198 596
Google video!
Packet split in portion 198 596
Google video!
Packet split in portion 198 596
Google video!
Packet split in portion 198 596
Google video!
Packet split in portion 198 596
Google video!
Packet split in portion 198 596
Google video!
Packet split in portion 198 596
Google video!
Packet split in portion 198 596```

**Comment by jelly8173** [comment]
here current startup log:
```
Using TCP segmentation
Some outgoing googlevideo request segments will be delayed for 100 ms as of SEG2_DELAY define
Fake SNI will be sent before each googlevideo request
GSO is enabled
Google video!
Packet split in portion 193 589
Google video!
Packet split in portion 193 1020
Google video!
Packet split in portion 198 593
Google video!
Packet split in portion 198 593
```

**Comment by Waujito** [comment]
What 

> yes! i see a lot, and i think more than one per request, console floods with
> 
> ```
> Packet split in portion 198 596
> Google video!
> Packet split in portion 198 596
> Google video!
> Packet split in portion 198 596
> Google video!
> Packet split in portion 198 596
> Google video!
> Packet split in portion 198 596
> Google video!
> Packet split in portion 198 596
> Google video!
> Packet split in portion 198 596
> Google video!
> Packet split in portion 198 596
> Google video!
> Packet split in portion 198 596
> ```

What if you set seg2 delay to 300? Change it in youtubeUnblock.c, you will see logs about it.

**Comment by jelly8173** [comment]
> Can you also try to run youtubeUnblock on local machine, not openwrr.

Now I see I was too hasty 🥲
Its too tedious to recompile it every time for openwrt.

I can test delay 300 np
Can you on your side move FAKE_SNI, DELAY and DEBUG to args? I care a lot about my flash chips 😝

**Comment by Waujito** [comment]
> > Can you also try to run youtubeUnblock on local machine, not openwrr.
> 
> Now I see I was too hasty 🥲 Its too tedious to recompile it every time for openwrt.
> 
> I can test delay 300 np Can you on your side move FAKE_SNI, DELAY and DEBUG to args? I care a lot about my flash chips 😝

I were too lazy to move it as args at start @zabbius works around it as I know.

If nothing of that works provide me with traveroute to Google server.

**Comment by jelly8173** [comment]
```
Using TCP segmentation
Some outgoing googlevideo request segments will be delayed for 300 ms as of SEG2_DELAY define
Fake SNI will be sent before each googlevideo request
GSO is enabled
```

With both HTTP2/3 disabled it does not load www.youtube.com at all!
With only HTTP2 disabled console floods with packet split messages, video does not start to play,
browser network logs shows red:
![Screenshot 2024-08-05 at 20 11 08](https://github.com/user-attachments/assets/cee3d287-938b-4f12-997b-9dff26bde743)

curl test: ```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 23  100M   23 23.4M    0     0  3522k      0  0:00:29  0:00:06  0:00:23 3487k^C
```

**Comment by jelly8173** [comment]
> If nothing of that works provide me with traveroute to Googlevideo server.
Its a bit of a confidential information. I can say that my Internet Provider is TransTelekom (TTK) and region Povolzhje

**Comment by Waujito** [comment]
> > If nothing of that works provide me with traveroute to Googlevideo server.
> 
> Its a bit of a confidential information. I can say that my Internet Provider is TransTelekom (TTK) and region Povolzhje

Ok, nvm. Just wanted to see how much hops are between you on GGC.

try this patch:
```patch
diff --git a/youtubeUnblock.c b/youtubeUnblock.c
index 67def6a..1a47de6 100644
--- a/youtubeUnblock.c
+++ b/youtubeUnblock.c
@@ -660,6 +660,9 @@ static struct pkt_buff *gen_fake_sni(const struct iphdr *iph, const struct tcphd

        ntcph->th_dport = tcph->th_dport;
        ntcph->th_sport = tcph->th_sport;
+       ntcph->seq = tcph->seq;
+       ntcph->ack_seq = tcph->ack_seq;
+       niph->ttl = 8;
        nfq_ip_set_checksum(niph);
        nfq_tcp_compute_checksum_ipv4(ntcph, niph);


```

**Comment by Waujito** [comment]
@jelly8173 
So it seems like the TSPU really get updated. Further tracking of the issue will be in #32

**Comment by cu6apum** [comment]
Particularly.
Firefox on macos behind the openwrt - started to work fine. Iphones in the same lan - did not.
