### ISSUE TITLE
Флаг и лист для доменов, не обрабатывающихся youtubeUnblock

### ISSUE THREAD

**Issue by EvgenyZR** [Waujito/youtubeUnblock#100]
Добрый день.

Добавьте, пожалуйста, новый флаг (а-ля --domains-excluded=) , где можно было бы перечислить домены, которые _не_ будут обрабатываться youtubeUnblock при использовании флага --sni-domains=all.

Как пример: невозможно зайти в личные кабинеты мегафон и мтс при --sni-domains=all . А выключать =all уж очень не хочется. :)

Спасибо!

**Comment by Waujito** [comment]
Да, у меня была мысль насчёт этого. В целом, можно добавить

**Comment by EvgenyZR** [comment]
Отлично! Тогда ждём с нетерпением. :)

**Comment by Waujito** [comment]
Проверяйте https://github.com/Waujito/youtubeUnblock/releases/tag/continuous

**Comment by EvgenyZR** [comment]
У меня на TP-Link Archer C7 работает. Спасибо!

**Comment by YBS-PC** [comment]
В каком формате можно добавлять домены-исключения: точный домен или можно например *.ru ?

**Comment by Waujito** [comment]
Без звёздочки. Оно будет сравнивать по символам начиная с конца. Регулярных выражений я не делал

**Comment by ballistix-ru** [comment]
Прошу подсказать как и где можно вносить исключения? в файле .ipk ? какой программой на винде это можно сделать?

**Comment by Waujito** [comment]
> Прошу подсказать как и где можно вносить исключения? в файле .ipk ? какой программой на винде это можно сделать?

В флагах надо прописывать —exclude-domains. Флаги прописываются либо в /etc/init.d/youtubeUnblock либо просто при запуске бинарника

**Comment by ballistix-ru** [comment]
я залил youtubeUnblock в openwrt на свой роутер. Как править этот ipk на роутере или на компе с виндой никак не получается. Скачал уже все проги на комп которые вроде должны открыть это расширение, но везде кракозябры.

**Comment by Waujito** [comment]
> я залил youtubeUnblock в openwrt на свой роутер. Как править этот ipk на роутере или на компе с виндой никак не получается. Скачал уже все проги на комп которые вроде должны открыть это расширение, но везде кракозябры.

Вам не нужно править ipk. Вам необходимо подключиться к роутеру по ssh и поправить файл /etc/init.d/youtubeUnblock. Флаги прописываются в строчке `procd_set_param command /usr/bin/youtubeUnblock`. Перезапускайте анблок `/etc/init.d/youtubeUnblock restart` Чтобы посмотреть логи используйте `logread -l 50`

**Comment by ballistix-ru** [comment]
спасибо!

**Comment by ballistix-ru** [comment]
procd_set_param command /usr/bin/youtubeUnblock -exclude-domains .ru

Вот так должна выглядеть строка? Поставил WinSCP. Правильно ли стоят дефисы и пробелы или это не имеет значения?

**Comment by Waujito** [comment]
> procd_set_param command /usr/bin/youtubeUnblock -exclude-domains .ru
> 
> Вот так должна выглядеть строка? Поставил WinSCP. Правильно ли стоят дефисы и пробелы или это не имеет значения? Знаки = ?
> 
> Заранее извиняюсь

Перед exclude двойной минус. И он вам вообще не нужен на параметрах по умолчанию. Дефолтно обрабатываются только домены гугла

**Comment by Waujito** [comment]
В #104 нашли ошибку, приводящую к бесконечному циклу, если не стоит опция --sni-domains=all. Обновитесь до последней версии youtubeUnblock https://github.com/Waujito/youtubeUnblock/actions/runs/10749316319

Возможно, проблема затрагивает @ballistix-ru, если вы используете последний development release.
