### ISSUE TITLE
Instagram не работает

### ISSUE THREAD

**Issue by proninyaroslav** [Waujito/youtubeUnblock#101]
Не совсем по теме, но я решил настроить утилиту и для некоторых других заблокированных доменов. Работает всё кроме инсты. Где то читал в ветке goodbye dpi что в случае инсты блокируются и ip адреса. Так ли это? `faking-strategy=pastseq`.

**Comment by Waujito** [comment]
С ним ничего не сделать
![image](https://github.com/user-attachments/assets/3be31f34-a5fa-46f2-897d-bc259bd242dd)

**Comment by proninyaroslav** [comment]
Значит да, по ip. Особые извращения ркн). Спасибо!
