### ISSUE TITLE
Попытался установить по инструкции в Xiaomi Router 3G Padavan Entware

### ISSUE THREAD

**Issue by unkn000wn** [Waujito/youtubeUnblock#103]
по инструкции из описания попытался запустить S51youtubeUnblock
Entware
For Entware on Keenetic here is an installation guide (russian). Note that if your Entware router is missing netfilter queue kernel modules, here is no way to deal with it since Entware does not offer kernel modules.

Install the binary with opkg install youtubeUnblock-*.ipk. After installation, the binary in /opt/bin and the init script in /opt/etc/init.d/S51youtubeUnblock will be available. To run the youtubeUnblock, simply run /opt/etc/init.d/S51youtubeUnblock start

после запуска /opt/etc/init.d/S51youtubeUnblock start выдает сообщение
`admin@TAICHI:/opt/etc/init.d# ./S91youtubeUnblock start
iptables: No chain/target/match by that name.
admin@TAICHI:/opt/etc/init.d#
`
Что не хватает, чтобы работало я просто плохо разбираюсь в этом. Добавьте пожалуйста в описание.

**Comment by Waujito** [comment]
Необходимо вставить модуль xt_NFQUEUE и xt_connbytes. `insmod $(find /lib/modules -name "xt_NFQUEUE.ko*")` и `insmod $(find /lib/modules -name "xt_connbytes.ko*")`

**Comment by unkn000wn** [comment]
[Waujito](https://github.com/Waujito) подскажите пожалуйста как это сделать? где и как его вставить?

**Comment by renr4** [comment]
https://github.com/Waujito/youtubeUnblock/pull/163
