### ISSUE TITLE
Не запускается правило nft

### ISSUE THREAD

**Issue by astinus000** [Waujito/youtubeUnblock#107]
Здравствуйте!
OpenWrt 23.05, MT7621
Установил пакет с github youtubeUnblock-0.3.2-31aa309-mipsel_24kc-openwrt-23.05.ipk
Положил файлик /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft скачанный с github
При перезапуске firewall ругается на ошибку:
---------
add rule inet fw4 mangle_forward tcp dport 443 ct original packets < 20 counter queue num 537 bypass
                                                                                                                            ^^^^
can't open 20: no such file
---------
Почитал мануал, в мануале в примере указано использовать с кавычками строку:  "packets < 20" 
Открыл файлик /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft , поправил строку, чтобы она выглядела так:
add rule inet fw4 mangle_forward tcp dport 443 ct original "packets < 20" counter queue num 537 bypass

Теперь при запуске ругается на Error: syntax error, unexpected quoted string
Решил попробовать исправить на одинарные кавычки. Тоже не работает.
Что я делаю не так? Как нужно подправить, чтобы заработало?

**Comment by astinus000** [comment]
nftables в этой версии openwrt установлен по умолчанию. Другие правила nft работают.

**Comment by Waujito** [comment]
Вообще этот файлик должен быть автоматически, после установки ipl. Проблема с кавычками может возникнуть только если вы добавляете правила через баш

**Comment by Waujito** [comment]
Попробуйте руками добавить правило
```sh
nft add rule inet fw4 mangle_forward tcp dport 443 ct original "packets < 20" counter queue num 537 bypass
```

**Comment by astinus000** [comment]
Также вываливает ошибку:
Error: Could not process rule: No such file or directory
add rule inet fw4 mangle_forward tcp dport 443 ct original packets < 20 counter queue num 537 bypass
                                                                                ^^^^^

Может как-то можно сформулировать правило по-другому?

**Comment by Waujito** [comment]
Модули установлены?

**Comment by astinus000** [comment]
Угу :(
-----
opkg list-installed | grep kmod-nf
kmod-nf-conncount - 5.15.150-1
kmod-nf-conntrack - 5.15.150-1
kmod-nf-conntrack6 - 5.15.150-1
kmod-nf-flow - 5.15.150-1
kmod-nf-ipt - 5.15.150-1
kmod-nf-ipt6 - 5.15.150-1
kmod-nf-log - 5.15.150-1
kmod-nf-log6 - 5.15.150-1
kmod-nf-nat - 5.15.150-1
kmod-nf-reject - 5.15.150-1
kmod-nf-reject6 - 5.15.150-1
kmod-nfnetlink - 5.15.150-1
kmod-nfnetlink-queue - 5.15.150-1
kmod-nft-compat - 5.15.150-1
kmod-nft-core - 5.15.150-1
kmod-nft-fib - 5.15.150-1
kmod-nft-nat - 5.15.150-1
kmod-nft-offload - 5.15.150-1
kmod-nft-queue - 5.15.150-1

**Comment by astinus000** [comment]
оооооооооо
переустановил зависимые модули и дало добавить правило из консоли

**Comment by astinus000** [comment]
Спасибо, проблема решилась переустановкой модулей. Из консоли сработало. Потом думаю, что не так с правилом в файлике? А я там кавычки забыл убрать. Теперь всё запустилось.
