### ISSUE TITLE
Необходимость в периодическом перезапуске 

### ISSUE THREAD

**Issue by tkachevaa** [Waujito/youtubeUnblock#111]
Поставил youtubeUnblock-0.3.2-3d50c00-mipsel-3.4-entware.tar на Keenetik Ultra II
при запуске бинарника youtube начинает нормально работать, но через несколько часов опять начинает тормозить (пока не вычислил точные периоды), при проверке статуса пишет running.
После команд stop и далее start все снова нормально.
Видимо нужен какой то скрипт перезапуска, не подскажите как это сделать или можно добавить какую то опцию для рестарта при каком то условии.
А вообще за программу огромный респект, окошко в мир позволяет держать открытым!

**Comment by Waujito** [comment]
Может, у вас правило iptables чем то перезаписывается? Это вряд ли проблема анблока, попробуйте вывести iptables -t mangle -nvL когда опять ютуб перестанет работать

**Comment by CavumSubarachnoidale** [comment]
Здравствуйте.

На Keenetic правило для 443 порта переписывается, я проверил, вот эту часть стирает:

147  117K NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 connbytes 0:19 connbytes mode packets connbytes direction original NFQUEUE num 537 bypass
  
Скорее всего, связано с тем, что этот порт для чего-то используется сами роутером:
https://forum.keenetic.com/topic/14696-переадресация-tcp443-в-keeneticos/

Думаю, надо чего-то крутить в самих настройках роутера, чтобы этого не происходило, буду пытаться.

**Comment by Waujito** [comment]
Случайно наткнулся на вот это
https://github.com/ndmsystems/packages/wiki/Opkg-Component#ndmnetfilterd

**Comment by tkachevaa** [comment]
> Здравствуйте.
> 
> На Keenetic правило для 443 порта переписывается, я проверил, вот эту часть стирает:
> 
> 147 117K NFQUEUE tcp -- * * 0.0.0.0/0 0.0.0.0/0 tcp dpt:443 connbytes 0:19 connbytes mode packets connbytes direction original NFQUEUE num 537 bypass
> 
> Скорее всего, связано с тем, что этот порт для чего-то используется самим роутером: [https://forum.keenetic.com/topic/14696-переадресация-tcp443-в-keeneticos/](https://forum.keenetic.com/topic/14696-%D0%BF%D0%B5%D1%80%D0%B5%D0%B0%D0%B4%D1%80%D0%B5%D1%81%D0%B0%D1%86%D0%B8%D1%8F-tcp443-%D0%B2-keeneticos/)
> 
> Думаю, надо чего-то крутить в самих настройках роутера, чтобы этого не происходило, буду пытаться.

Да у меня также, именно эта строка пропадает. А после рестарта youtubeUnblock восстанавливается.

**Comment by Waujito** [comment]
```sh
#!/bin/sh

[ "$type" == "ip6tables" ] && exit 0   # check the protocol type in backward-compatible way
[ "$table" != "mangle" ] && exit 0   # check the table name

iptables -t mangle -N YOUTUBEUNBLOCK
iptables -t mangle -A YOUTUBEUNBLOCK -p tcp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass
iptables -t mangle -A YOUTUBEUNBLOCK -p udp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass
iptables -t mangle -A POSTROUTING -j YOUTUBEUNBLOCK
```

Попробуйте прописать это в `/opt/etc/ndm/netfilter.d/99-youtubeUnblock.sh` (не забудьте сделать `chmod +x /opt/etc/ndm/netfilter.d/99-youtubeUnblock.sh`)

**Comment by tkachevaa** [comment]
> ```shell
> #!/bin/sh
> 
> [ "$type" == "ip6tables" ] && exit 0   # check the protocol type in backward-compatible way
> [ "$table" != "mangle" ] && exit 0   # check the table name
> 
> iptables -t mangle -N YOUTUBEUNBLOCK
> iptables -t mangle -A YOUTUBEUNBLOCK -p tcp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass
> iptables -t mangle -A YOUTUBEUNBLOCK -p udp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass
> iptables -t mangle -A POSTROUTING -j YOUTUBEUNBLOCK
> ```
> 
> Попробуйте прописать это в `/opt/etc/ndm/netfilter.d/99-youtubeUnblock.sh` (не забудьте сделать `chmod +x /opt/etc/ndm/netfilter.d/99-youtubeUnblock.sh`)

Сделал, но теперь при запуске выдает следующее: iptables: No chain/target/match by that name.

**Comment by CavumSubarachnoidale** [comment]
> Сделал, но теперь при запуске выдает следующее: iptables: No chain/target/match by that name. Удалил файл 99-youtubeUnblock.sh, перезапустил роутер, но ошибка осталась та же и самое грустное ютуб стал тормозить как обычно. В общем больному стало хуже, он перестал дышать-)

Об этом уже был Issue #97 

Решение - эти 3 команды:

opkg install kmod

и дальше

insmod /lib/modules/4.9-ndm-5/xt_NFQUEUE.ko
insmod /lib/modules/4.9-ndm-5/xt_connbytes.ko

**Comment by tkachevaa** [comment]
> > Сделал, но теперь при запуске выдает следующее: iptables: No chain/target/match by that name. Удалил файл 99-youtubeUnblock.sh, перезапустил роутер, но ошибка осталась та же и самое грустное ютуб стал тормозить как обычно. В общем больному стало хуже, он перестал дышать-)
> 
> Об этом уже был Issue #97
> 
> Решение - эти 3 команды:
> 
> opkg install kmod
> 
> и дальше
> 
> insmod /lib/modules/4.9-ndm-5/xt_NFQUEUE.ko insmod /lib/modules/4.9-ndm-5/xt_connbytes.ko

kmod у меня уже стоял, а вот после следующих двух команд старт прошел без ошибок, буду тестировать дальше, посмотрю не отвалится ли снова через пару тройку часов. Спасибо за совет!

**Comment by CavumSubarachnoidale** [comment]
> ```shell
> #!/bin/sh
> 
> [ "$type" == "ip6tables" ] && exit 0   # check the protocol type in backward-compatible way
> [ "$table" != "mangle" ] && exit 0   # check the table name
> 
> iptables -t mangle -N YOUTUBEUNBLOCK
> iptables -t mangle -A YOUTUBEUNBLOCK -p tcp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass
> iptables -t mangle -A YOUTUBEUNBLOCK -p udp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass
> iptables -t mangle -A POSTROUTING -j YOUTUBEUNBLOCK
> ```
> 
> Попробуйте прописать это в `/opt/etc/ndm/netfilter.d/99-youtubeUnblock.sh` (не забудьте сделать `chmod +x /opt/etc/ndm/netfilter.d/99-youtubeUnblock.sh`)

К сожалению, не возымело никакого эффекта, я в других скриптах видел что-то вроде этого:

`
  iptables -t nat -A PREROUTING -i br0 -p tcp --dport 80 -j REDIRECT --to-port 999
  iptables -t nat -A PREROUTING -i br0 -p tcp --dport 443 -j REDIRECT --to-port 999
  iptables -t nat -A PREROUTING -i br0 -p udp --dport 443 -j REDIRECT --to-port 999
`

Пока что я написал простейший скрипт который перезапускает S91youtubeUnblock каждую минуту, уже пару дней с этим полёт нормальный, пуду ещё пробовать перенастроить порты.

**Comment by CavumSubarachnoidale** [comment]
@tkachevaa как ваши успехи? У меня пока никаких продвижений, всё ещё сижу на скрипте перезапуска каждую минуту.

Пробовал вбивать эти команды напрямую в терминал:

`iptables -t mangle -N YOUTUBEUNBLOCK`
`iptables -t mangle -A YOUTUBEUNBLOCK -p tcp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass`
`iptables -t mangle -A YOUTUBEUNBLOCK -p udp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass`
`iptables -t mangle -A POSTROUTING -j YOUTUBEUNBLOCK`

А потом запускать скрипт - всё равно отваливается.

Также пробовал добавить такую строку в скрипт S91youtubeUnblock в Start

`iptables -t nat -A PREROUTING -i br0 -p tcp --dport 443 -j REDIRECT --to-port 999`

 и поменять порт, который уже был в самом скрипте с 443 на 999. Думал, что это сделает редирект с 443 на 999, а youtubeUnblock уже пусть работает с 999, но тогда скрипт просто перестаёт работать, хоть ошибок и не выдаёт.

Но я по сути действую вслепую, потому что абсолютно ничего не понимаю :)

Также в моём скрипте перезапуска есть такие строки:

`insmod /lib/modules/4.9-ndm-5/xt_NFQUEUE.ko || true`
`insmod /lib/modules/4.9-ndm-5/xt_connbytes.ko || true`

Так как у меня время от времени эти инструкции отваливаются и приходится заново их вводить. `|| true` позволяет продолжить выполнение скрипта в случае ошибки, ибо если эти инструкции активны, то они выдают ошибку, а если неактивны, то вводятся нормально.

Мне кажется, что подход с редиректом на другой порт (999) самый перспективный, я просто не знаю, как его правильно накодить.

**Comment by Waujito** [comment]
Я сомневаюсь, что проблема в ваших портах ната. Мне кажется, что что-то заставляет постоянно перезапускаться ваш фаервол. Мне показалось, что тут описывается как раз эта ситуация, причём даже на форумах кинетика ссылались сюда https://github.com/ndmsystems/packages/wiki/Opkg-Component#ndmnetfilterd Конечно, странно, что оно не помогло, но мне кажется, что стоит копать в эту сторону.

Нашёл упоминание об этом в запрете https://github.com/bol-van/zapret/discussions/208#discussioncomment-10368580
![image](https://github.com/user-attachments/assets/9977788e-ecf7-414d-8ad3-c3865ceeb5db)
 
В целом, можно туда написать что-то типа
```
#!/bin/sh
[ "$type" == "ip6tables" ] && exit 0
[ "$table" != "mangle" ] && exit 0
/opt/init.d/youtubeUnblock firewall-stop &>/dev/null
/opt/init.d/youtubeUnblock firewall-load
```

**Comment by tkachevaa** [comment]
> @tkachevaa как ваши успехи? У меня пока никаких продвижений, всё ещё сижу на скрипте перезапуска каждую минуту.
> 
> Пробовал вбивать эти команды напрямую в терминал:
> 
> `iptables -t mangle -N YOUTUBEUNBLOCK` `iptables -t mangle -A YOUTUBEUNBLOCK -p tcp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass` `iptables -t mangle -A YOUTUBEUNBLOCK -p udp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass` `iptables -t mangle -A POSTROUTING -j YOUTUBEUNBLOCK`
> 
> А потом запускать скрипт - всё равно отваливается.
> 
> Также пробовал добавить такую строку в скрипт S91youtubeUnblock в Start
> 
> `iptables -t nat -A PREROUTING -i br0 -p tcp --dport 443 -j REDIRECT --to-port 999`
> 
> и поменять порт, который уже был в самом скрипте с 443 на 999. Думал, что это сделает редирект с 443 на 999, а youtubeUnblock уже пусть работает с 999, но тогда скрипт просто перестаёт работать, хоть ошибок и не выдаёт.
> 
> Но я по сути действую вслепую, потому что абсолютно ничего не понимаю :)
> 
> Также в моём скрипте перезапуска есть такие строки:
> 
> `insmod /lib/modules/4.9-ndm-5/xt_NFQUEUE.ko || true` `insmod /lib/modules/4.9-ndm-5/xt_connbytes.ko || true`
> 
> Так как у меня время от времени эти инструкции отваливаются и приходится заново их вводить. `|| true` позволяет продолжить выполнение скрипта в случае ошибки, ибо если эти инструкции активны, то они выдают ошибку, а если неактивны, то вводятся нормально.
> 
> Мне кажется, что подход с редиректом на другой порт (999) самый перспективный, я просто не знаю, как его правильно накодить.

Я все пытаюсь поймать логику отключений, ведь несколько часов все работает нормально, может это пока есть обращения к ютубу, а после допустим какого-то периода неактивности необходим перезапуск. Пока это не сильно напрягает, так что смирился с этим недостатком

**Comment by CavumSubarachnoidale** [comment]
> В целом, можно туда написать что-то типа
> 
> ```
> /opt/etc/ndm/netfilter.d/000-youtubeUnblock.sh
> ```
> 
> ```shell
> #!/bin/sh
> [ "$type" == "ip6tables" ] && exit 0
> [ "$table" != "mangle" ] && exit 0
> /opt/etc/init.d/youtubeUnblock firewall-stop &>/dev/null
> /opt/etc/init.d/youtubeUnblock firewall-load
> ```

Всё, вроде как стабильно заработало. Пришлось добавить в Start в **S91youtubeUnblock**

```
start() {
	chmod +x /opt/etc/ndm/netfilter.d/000-youtubeUnblock.sh
	insmod /lib/modules/4.9-ndm-5/xt_NFQUEUE.ko || true
	insmod /lib/modules/4.9-ndm-5/xt_connbytes.ko || true
	...
}
```

А сам **000-youtubeUnblock.sh** в итоге у меня выглядит так (убрал логи, потому что в какая-то ерунда без конца писалась)

```
#!/bin/sh
[ "$type" == "ip6tables" ] && exit 0 &>/dev/null
[ "$table" != "mangle" ] && exit 0 &>/dev/null
/opt/etc/init.d/S91youtubeUnblock firewall-stop &>/dev/null
/opt/etc/init.d/S91youtubeUnblock firewall-load &>/dev/null
```

@Waujito Огромное спасибо за ваш труд! Скажите, куда можно донатить.

**Comment by Waujito** [comment]
Обновил пакет для entware с новым скриптом, можете скачать отсюда
https://github.com/Waujito/youtubeUnblock/actions/runs/10970546908

**Comment by Waujito** [comment]
> Обновил пакет для entware с новым скриптом, можете скачать отсюда https://github.com/Waujito/youtubeUnblock/actions/runs/10970546908

@CavumSubarachnoidale у вас заработала последняя версия скрипта из коробки? (https://github.com/Waujito/youtubeUnblock/actions/runs/10974681779)

**Comment by tkachevaa** [comment]
> > Обновил пакет для entware с новым скриптом, можете скачать отсюда https://github.com/Waujito/youtubeUnblock/actions/runs/10970546908
> 
> @CavumSubarachnoidale у вас заработала последняя версия скрипта из коробки? (https://github.com/Waujito/youtubeUnblock/actions/runs/10974681779)

У меня так же, только перезапуск помогает

**Comment by CavumSubarachnoidale** [comment]
@Waujito у меня тоже из коробки отваливается через минуту, как перестаю смотреть ютуб. Возвращаюсь к предыдущему варианту:

> Всё, вроде как стабильно заработало. Пришлось добавить в Start в **S91youtubeUnblock**
> 
> ```
> start() {
> 	chmod +x /opt/etc/ndm/netfilter.d/000-youtubeUnblock.sh
> 	insmod /lib/modules/4.9-ndm-5/xt_NFQUEUE.ko || true
> 	insmod /lib/modules/4.9-ndm-5/xt_connbytes.ko || true
> 	...
> }
> ```
> 
> А сам **000-youtubeUnblock.sh** в итоге у меня выглядит так (убрал логи, потому что в какая-то ерунда без конца писалась)
> 
> ```
> #!/bin/sh
> [ "$type" == "ip6tables" ] && exit 0 &>/dev/null
> [ "$table" != "mangle" ] && exit 0 &>/dev/null
> /opt/etc/init.d/S91youtubeUnblock firewall-stop &>/dev/null
> /opt/etc/init.d/S91youtubeUnblock firewall-load &>/dev/null
> ```

**Comment by bencheg** [comment]
@CavumSubarachnoidale попробовал по вашему рецепту, ругается при запуске:

insmod: ERROR: could not insert module /lib/modules/4.9-ndm-5/xt_NFQUEUE.ko: File exists
insmod: ERROR: could not insert module /lib/modules/4.9-ndm-5/xt_connbytes.ko: File exists

Если я правильно понимаю, модули уже загружены, но если их убрать из секции start - симптомы остаются, минута и отваливается.

**Comment by CavumSubarachnoidale** [comment]
> @CavumSubarachnoidale попробовал по вашему рецепту, ругается при запуске:
> 
> insmod: ERROR: could not insert module /lib/modules/4.9-ndm-5/xt_NFQUEUE.ko: File exists insmod: ERROR: could not insert module /lib/modules/4.9-ndm-5/xt_connbytes.ko: File exists
> 
> Если я правильно понимаю, модули уже загружены, но если их убрать из секции start - симптомы остаются, минута и отваливается.

Это нормально, оно выдаёт ошибку но скрипт продолжается, так как  '|| true'

Эта инструкция иногда отваливается поэтому надо её перезапускать.

**Comment by bencheg** [comment]
> @bencheg копайте в сторону того, что именно пропадает. После того как пропадёт анблок посмотрите его статус в инит файле и правила iptables в таблице mangle (см. начало этого треда)

Да, пропадает это строка:

`Chain YOUTUBEUNBLOCK (1 references)`

Все инструкции выше выполнил, но один фиг пропадает :(

**Comment by Waujito** [comment]
@bencheg 

А что у вас вообще живёт в /opt/etc/ndm/netfilter.d ?
Покажите вывод всех этих файлов если их много

**Comment by bencheg** [comment]
000-youtubeUnblock.sh
`#!/bin/sh
[ "$type" == "ip6tables" ] && exit 0 &>/dev/null
[ "$table" != "mangle" ] && exit 0 &>/dev/null
/opt/etc/init.d/S91youtubeUnblock firewall-stop &>/dev/null
/opt/etc/init.d/S91youtubeUnblock firewall-load &>/dev/null
`
100-dns-local
`#
#------------------------------------------------------------------------------
#
#       Данный файл служит для создания правил для пропуска DNS трафика по 53 порту (tcp и udp)
#       при использовании любого VPN подключения (в том числе и shadowsocks).
#       Они срабатывают при пепезаписи правил в таблице netfilter
#       https://github.com/ndmsystems/packages/wiki/Opkg-Component
#
# ------------------------------------------------------------------------------
#       Разработчик: mail@zeleza.ru
#       Дата создания: 21/05/2022
#       Лицензия: Apache License 2.0
# ------------------------------------------------------------------------------
if [ "${type}" = "iptables" ] && [ "${table}" = "nat" ] ; then
        . /opt/apps/kvas/bin/libs/ndm
#        logger -t "КВАС"  "Запущен файл ${0} [type=${type} и table=${table}]"
        ip4_firewall_dns_rules_set &> /dev/null
        #       в случае наличия гостевой сети
#       set_guest_nets_rules &> /dev/null
fi`
100-proxy-redirect
`
#
#------------------------------------------------------------------------------
#
#       Данный файл служит для создания правил для пропуска DNS трафика по 53 порту (tcp и udp)
#       при использовании любого VPN подключения (в том числе и shadowsocks).
#       Они срабатывают при пепезаписи правил в таблице netfilter
#       https://github.com/ndmsystems/packages/wiki/Opkg-Component
#
# ------------------------------------------------------------------------------
#       Разработчик: mail@zeleza.ru
#       Дата создания: 21/05/2022
#       Лицензия: Apache License 2.0
# ------------------------------------------------------------------------------
if [ "${type}" = "iptables" ] && [ "${table}" = "nat" ] ; then
        . /opt/apps/kvas/bin/libs/ndm
#        logger -t "КВАС"  "Запущен файл ${0} [type=${type} и table=${table}]"
        ip4_firewall_dns_rules_set &> /dev/null
        #       в случае наличия гостевой сети
#       set_guest_nets_rules &> /dev/null
fi`

**Comment by Waujito** [comment]
Так, сделаем по-другому. 
000-youtubeUnblock.sh -> 200-youtubeUnblock

```sh
#!/bin/sh
[ "$type" == "ip6tables" ] && exit 0 &>/dev/null
[ "$table" != "mangle" ] && exit 0 &>/dev/null
iptables -t mangle -N YOUTUBEUNBLOCK || true
iptables -t mangle -A YOUTUBEUNBLOCK -p tcp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass || true
iptables -t mangle -A YOUTUBEUNBLOCK -p udp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass || true
iptables -t mangle -A POSTROUTING -j YOUTUBEUNBLOCK || true
iptables -I OUTPUT -m mark --mark 32768/32768 -j ACCEPT || true
ip6tables -t mangle -N YOUTUBEUNBLOCK || true
ip6tables -t mangle -A YOUTUBEUNBLOCK -p tcp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass || true
ip6tables -t mangle -A YOUTUBEUNBLOCK -p udp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass || true
ip6tables -t mangle -A POSTROUTING -j YOUTUBEUNBLOCK || true
ip6tables -I OUTPUT -m mark --mark 32768/32768 -j ACCEPT || true
```

**Comment by bencheg** [comment]
Пока не менял 000-youtubeUnblock.sh -> 200-youtubeUnblock  жду пока отвалится, но почему-то пока не отваливается. 

Не знаю пока что послужило причиной, наблюдаю. Чуть позже поменяю, отпишусь.

Спасибо!

**Comment by bencheg** [comment]
Два дня прошло, сервис не падал. Видимо, помогло.

Наблюдаю дальше.

Всем огромное спасибо за помощь, автору отдельное за его работу.

**Comment by tkachevaa** [comment]
> Два дня прошло, сервис не падал. Видимо, помогло.
> 
> Наблюдаю дальше.
> 
> Всем огромное спасибо за помощь, автору отдельное за его работу.

Можете финальный мануал написать для старых чайников что и как сделать для устранения проблемы?

**Comment by Waujito** [comment]
@CavumSubarachnoidale только увидел, спасибо большое!

**Comment by bencheg** [comment]
> > Два дня прошло, сервис не падал. Видимо, помогло.
> > Наблюдаю дальше.
> > Всем огромное спасибо за помощь, автору отдельное за его работу.
> 
> Можете финальный мануал написать для старых чайников что и как сделать для устранения проблемы?

Да, собственно, всё то что написано здесь:

в /opt/etc/ndm/netfilter.d/000-youtubeUnblock.sh

```
#!/bin/sh
[ "$type" == "ip6tables" ] && exit 0 &>/dev/null
[ "$table" != "mangle" ] && exit 0 &>/dev/null
/opt/etc/init.d/S91youtubeUnblock firewall-stop &>/dev/null
/opt/etc/init.d/S91youtubeUnblock firewall-load &>/dev/null
```

B S91youtubeUnblock добавил строки:

```
start() {
	chmod +x /opt/etc/ndm/netfilter.d/000-youtubeUnblock.sh
	insmod /lib/modules/4.9-ndm-5/xt_NFQUEUE.ko || true
	insmod /lib/modules/4.9-ndm-5/xt_connbytes.ko || true
	...
}
```

Но, наблюдаю другую картину, которую пока не связываю с youtubeUnblock - мой кинетик виснет через 30-60 часов работы. Появилось после установки, но после не значит в следствие :)

**Comment by tkachevaa** [comment]
Последняя версия теперь работает стабильно, перезапусков не требует

**Comment by tkachevaa** [comment]
> > Последняя версия теперь работает стабильно, перезапусков не требует
> 
> youtubeUnblock-0.3.2-3d50c00 Эта версия?

youtubeUnblock_1.0.0-e9b033c-mipsel-3.4-1_mipsel-3.4

**Comment by tkachevaa** [comment]
Релиза не было, есть и посвежее, но этот вариант я пока не пробовал
https://github.com/Waujito/youtubeUnblock/actions/runs/11201897622

**Comment by tkachevaa** [comment]
> > > > Последняя версия теперь работает стабильно, перезапусков не требует
> > > 
> > > 
> > > youtubeUnblock-0.3.2-3d50c00 Эта версия?
> > 
> > 
> > youtubeUnblock_1.0.0-e9b033c-mipsel-3.4-1_mipsel-3.4
> 
> Хм, не нахожу такой релиз для entware. Там последний youtubeUnblock-0.3.2-3d50c00 .

Релиза не было, есть и посвежее, но этот вариант я пока не пробовал
https://github.com/Waujito/youtubeUnblock/actions/runs/11201897622

**Comment by Waujito** [comment]
Просто поставьте из rc3
