### ISSUE TITLE
LuCI seems doesn't work

### ISSUE THREAD

**Issue by proninyaroslav** [Waujito/youtubeUnblock#114]
During installation I get the following errors (truncated log):
```
Command failed: ubus call service delete { "name": "youtubeUnblock" } (Not found)
uci: Entry not found
uci: Entry not found

uci: Entry not found


uci: Entry not found
...
```

and in the GUI:

![image](https://github.com/user-attachments/assets/415a2cad-aca8-409c-acd9-6a46b98a2a60)

installation log if needed:
```
Upgrading youtubeUnblock on root from 0.3.2-aef2b5b-ath79-1 to 0.3.2-f082660-ath79-1...
Installing liblua5.1.5 (5.1.5-11) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/mips_24kc/base/liblua5.1.5_5.1.5-11_mips_24kc.ipk
Installing lua (5.1.5-11) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/mips_24kc/base/lua_5.1.5-11_mips_24kc.ipk
Installing luci-lib-nixio (git-24.034.54875-21210dc) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/mips_24kc/luci/luci-lib-nixio_git-24.034.54875-21210dc_mips_24kc.ipk
Installing luci-lib-ip (git-23.311.79290-c2a887e) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/mips_24kc/luci/luci-lib-ip_git-23.311.79290-c2a887e_mips_24kc.ipk
Installing luci-lib-jsonc (git-23.298.74571-62eb535) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/mips_24kc/luci/luci-lib-jsonc_git-23.298.74571-62eb535_mips_24kc.ipk
Installing liblucihttp-lua (2023-03-15-9b5b683f-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/mips_24kc/luci/liblucihttp-lua_2023-03-15-9b5b683f-1_mips_24kc.ipk
Installing luci-lib-base (git-22.308.54612-9118452) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/mips_24kc/luci/luci-lib-base_git-22.308.54612-9118452_all.ipk
Installing libubus-lua (2023-06-05-f787c97b-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/mips_24kc/base/libubus-lua_2023-06-05-f787c97b-1_mips_24kc.ipk
Installing ucode-mod-lua (1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/mips_24kc/luci/ucode-mod-lua_1_mips_24kc.ipk
Installing luci-lua-runtime (git-23.233.52805-dae2684) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/mips_24kc/luci/luci-lua-runtime_git-23.233.52805-dae2684_mips_24kc.ipk
Installing luci-compat (git-24.086.45108-51aee90) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/mips_24kc/luci/luci-compat_git-24.086.45108-51aee90_all.ipk
Configuring liblua5.1.5.
Configuring lua.
Configuring luci-lib-nixio.
Configuring luci-lib-ip.
Configuring luci-lib-jsonc.
Configuring liblucihttp-lua.
Configuring luci-lib-base.
Configuring libubus-lua.
Configuring ucode-mod-lua.
Configuring luci-lua-runtime.
Configuring luci-compat.
Configuring youtubeUnblock.
```

**Comment by Waujito** [comment]
Hello! Thank you for such an early testing.
I added the commit that may fix this. Please, try it now with https://github.com/Waujito/youtubeUnblock/actions/runs/10863253494

**Comment by proninyaroslav** [comment]
Works, thank you.

![image](https://github.com/user-attachments/assets/7af8221d-5d47-49fb-9557-ac9b2a495094)

**Comment by YBS-PC** [comment]
![Снимок экрана 2024-09-14 174017](https://github.com/user-attachments/assets/9b4c5ba4-49f7-4110-b290-8d907534536b)
При установке появилось что то такое (последнее изменение не посмотрел). Пришлось вручную запустить https://github.com/Waujito/youtubeUnblock/blob/openwrt/youtubeUnblock/files/etc/uci-defaults/99-youtubeUnblock.sh
Потом, очень сильно расширяется страница Процессы из-за большого количества доменов наверное
![Снимок экрана 2024-09-14 175917](https://github.com/user-attachments/assets/b1141661-3b9f-456d-bfcd-954d0b70aa17)
 а обычно
![Снимок экрана 2024-09-14 175942](https://github.com/user-attachments/assets/b0daefb5-1b8e-420e-90d1-cd79105f3010)
 Остался вопрос по двум настройкам nftables нужны ли они:
sed -i "s/mangle_forward/mangle_postrouting/" /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft
echo "insert rule inet fw4 forward ip saddr 192.168.2.10 udp dport 443 counter drop" >> /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft

**Comment by proninyaroslav** [comment]
@YBS-PC 
Ставьте версию выше

**Comment by Waujito** [comment]
@YBS-PC
Насчёт nftables, я обновил правила, теперь они улавливают quic. Можете просто поставить флажок в quic-drop и всё. Правила оставляйте те, которые есть изначально. (если вам всё таки надо оставить quic для других устройств, пока что придётся использовать это правило вместо флажка.

**Comment by Waujito** [comment]
Я сделал всё в postrouting, так будет правильнее. Получается, теперь не нужна

**Comment by Waujito** [comment]
Такая рекомендация была для тех, у кого метка 32768 конфликтовала с другими правилами, которые опираются на эту метку

**Comment by YBS-PC** [comment]
если я раньше использовал 
`--packet-mark=524288 --frag-sni-reverse=0`
и
```
add rule inet fw4 mangle_postrouting tcp dport 443 ct original packets < 20 counter queue num 537 bypass
insert rule inet fw4 forward ip saddr 192.168.1.10 udp dport 443 counter drop
```
сейчас в настройках:
```

config youtubeUnblock 'youtubeUnblock'
	option frag 'tcp'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option fk_winsize '0'
	option seg2delay '0'
	option packet_mark '524288'
	option fake_sni '1'
	option faking_strategy 'pastseq'
	option fake_sni_seq_len '1'
	list sni_domains 'googlevideo.com'
	list sni_domains 'ggpht.com'
	list sni_domains 'ytimg.com'
	list sni_domains 'youtube.com'
	list sni_domains 'play.google.com'
	list sni_domains 'youtu.be'
	list sni_domains 'googleapis.com'
	list sni_domains 'googleusercontent.com'
	list sni_domains 'gstatic.com'
	list sni_domains 'l.google.com'
	option quic_drop '1'


```
Все настройки соответствуют же, за исключением индивидуального quic drop для одного ip 192.168.2.10?

**Comment by Waujito** [comment]
Хорошее замечание по поводу вкладки processes, [создал issue в luci](https://github.com/openwrt/luci/issues/7280)

> если я раньше использовал --frag-sni-reverse=0

вообще нет, там должен стоять 0

**Comment by YBS-PC** [comment]
> вообще нет, там должен стоять 0

я снимаю галку и сохраняю, а frag-sni-reverse=0 не появляется

**Comment by Waujito** [comment]
Да, вижу, сейчас подумаю над этим.

**Comment by Waujito** [comment]
@YBS-PC 
Обновил для последнего development релиза, проверяйте

**Comment by YBS-PC** [comment]
> Обновил для последнего development релиза, проверяйте

появились  --frag-sni-reverse=0 --frag-sni-faked=0 --synfake=0 - как и ожидалось. Чуть позже проверю на apple tv - гасит ли quic.

**Comment by YBS-PC** [comment]
на эпл тв падает до 480р поставлю insert rule inet fw4 forward ip saddr 192.168.1.10 udp dport 443 counter drop и буду наблюдать

**Comment by SnoweTiger** [comment]
Не появляеться приложение в Сервисах для роутера routerich с его оригинальной прошивкой на базе OpenWrt 23.05.3. Ставлю сначала 3 необходимых пакета потом сам youtubeUnblock. Пробовал 0,3,2 и девелопер релиз. Ошибок при установке нет. Подскажите в чем может быть дело?
