### ISSUE TITLE
UnBlock Instagram

### ISSUE THREAD

**Issue by CodeRoK7** [Waujito/youtubeUnblock#115]
Привет всем. У кого нибудь получилось разблокировать инстраграм? Можете скинуть рабочую стратегию, чтобы я не пробовал - не получается.

**Comment by Waujito** [comment]
Ответ прост - это невозможно :)
Он блокируется по IP.

**Comment by MrPipp** [comment]
> Ответ прост - это невозможно :) Он блокируется по IP.
goodbyedpi пробивает:)

**Comment by Waujito** [comment]
> > Ответ прост - это невозможно :) Он блокируется по IP.

> goodbyedpi пробивает:)

Вряд ли goodbyedpi, мне кажется, ответ в ipv6

**Comment by MrPipp** [comment]
Тестил на goodbyedpi-0.2.3rc3-2\1_russia_blacklist_dnsredir.cmd

**Comment by mmmpolkovnikov-cloud** [comment]
Ну так что кто скинет домены с помощью которых пробивает инсту ?
