### ISSUE TITLE
Ошика сети на Samsung ТВ с PBR

### ISSUE THREAD

**Issue by unclgeek** [Waujito/youtubeUnblock#116]
Всё отлично работает на всех устройствах, но на Tizen при запуске youtube вылетает с ошибкой сети.
Метки пакетов десятки раз менял, не сработало. 
Все параметры после установки на openwrt оставил по-умолчанию: стратегия - pastseq.
Если выключаю PBR, то всё работает. 
Все параметры из [PBR conflict with youtubeUnblock #59](https://github.com/Waujito/youtubeUnblock/issues/59) пробовал - не помогло.

**Comment by Waujito** [comment]
Поставьте отсюда анблок https://github.com/Waujito/youtubeUnblock/actions/runs/10865382667

И включите флаги drop quic и all domains (можно через гуи)
Правила фаервола не меняйте, они тут более полные. Единственное, что можете поменять - это метку пакетов на другую степень двойки, если она кофликтует с вашим PBR.
