### ISSUE TITLE
`--silent`

### ISSUE THREAD

**Issue by a3r5** [Waujito/youtubeUnblock#117]
`--silent`
this arg disable messages in syslog

_Originally posted by @antiuser in https://github.com/Waujito/youtubeUnblock/issues/34#issuecomment-2278133262_

В какой строке файла /etc/init.d/youtubeUnblock  ,прописать флаг --silent

**Comment by a3r5** [comment]
Пытаюсь избавится от спама.
Где только не пытался , прописать этот флаг. 
Прописывал  рядом с похожей строкой:
```
procd_set_param command $PROG $OPTS
procd_set_param command /usr/bin/youtubeUnblock --silent 
```
ещё здесь пытался :
```
# You should use uci for configuration
OPTS="--silent"
```
перезагрузку юнита делал и даже 1 раз ребут.

Хотелось бы, оставить ipv6.

@Waujito
> Отключите ipv6

У меня стоит как я понял последний билд [10863253494](https://github.com/Waujito/youtubeUnblock/actions/runs/10863253494) , youtubeUnblock-0.3.2-85d3843-aarch64_cortex-a53-openwrt-23.05.ipk .

Спам в лог файле который пытаюсь убрать , а лучше отключить весь вывод youtubeUnblock в лог  :

```
ip4_payload_split: ipversion: Invalid argument
Target SNI detected: “e.t.c”
```

**Comment by Waujito** [comment]
Уберите флаг из OPTS, сделайте
```
uci set youtubeUnblock.youtubeUnblock. silent=1
uci commit
reload_config
```

Также можете использовать графический интерфейс в панели управления роутером, там просто флажок силент надо поставить

**Comment by a3r5** [comment]
Всё сделал , флажок выставил , рестарт юнита, спам остался.
Команды ввёл , рестарт, спам не уходит ,и вывод в лог при старте также .

```
Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: Using TCP segmentation
Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: Fake SNI will be sent before each target client hello
Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: Fragmentation Client Hello will be reversed
Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: Past seq faking strategy will be used
Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: GSO is enabled
Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: IPv6 is enabled
Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: Queue 537 started
Mon Sep 16 09:36:34 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
Mon Sep 16 09:36:34 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
Mon Sep 16 09:36:37 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
Mon Sep 16 09:36:37 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
Mon Sep 16 09:36:41 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
Mon Sep 16 09:36:41 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
Mon Sep 16 09:36:51 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
Mon Sep 16 09:36:51 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
Mon Sep 16 09:36:51 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
Mon Sep 16 09:36:52 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
```

**Comment by Waujito** [comment]
> Всё сделал , флажок выставил , рестарт юнита, спам остался.
> Команды ввёл , рестарт, спам не уходит ,и вывод в лог при старте также .
> 
> ```
> Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: Using TCP segmentation
> Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: Fake SNI will be sent before each target client hello
> Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: Fragmentation Client Hello will be reversed
> Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: Past seq faking strategy will be used
> Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: GSO is enabled
> Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: IPv6 is enabled
> Mon Sep 16 09:36:32 2024 daemon.info youtubeUnblock[5267]: Queue 537 started
> Mon Sep 16 09:36:34 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
> Mon Sep 16 09:36:34 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
> Mon Sep 16 09:36:37 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
> Mon Sep 16 09:36:37 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
> Mon Sep 16 09:36:41 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
> Mon Sep 16 09:36:41 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
> Mon Sep 16 09:36:51 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
> Mon Sep 16 09:36:51 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
> Mon Sep 16 09:36:51 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
> Mon Sep 16 09:36:52 2024 daemon.info youtubeUnblock[5267]: ip4_payload_split: ipversion: Invalid argument
> ```

Это quic over ipv6, тут исправлено https://github.com/Waujito/youtubeUnblock/actions/runs/10865382667

**Comment by a3r5** [comment]
Подтверждаю , ошибка ушла , спасибо за программу :+1:
