### ISSUE TITLE
Client Hello packet is too big

### ISSUE THREAD

**Issue by aloorpro** [Waujito/youtubeUnblock#118]
не совсем понятно, чем вызывается и как побеждать такое поведение. Буду рад любым подсказкам и мыслям по теме

Using TCP segmentation
Fake SNI will be sent before each target client hello
Fragmentation Client Hello will be reversed
Past seq faking strategy will be used
GSO is enabled
IPv6 is enabled
All QUIC packets will be dropped
Queue 537 started
Target SNI detected: rr4---sn-hxb54vo-238s.googlevideo.com
WARNING! Client Hello packet is too big and may cause issues!
Split packet!
Target SNI detected: rr4---sn-hxb54vo-238s.googlevideo.com
WARNING! Client Hello packet is too big and may cause issues!
Split packet!
Target SNI detected: rr1---sn-hxb54vo-238s.googlevideo.com
WARNING! Client Hello packet is too big and may cause issues!
Split packet!
Target SNI detected: i.ytimg.com
WARNING! Client Hello packet is too big and may cause issues!
Split packet!
Target SNI detected: r4---sn-ug5onuxaxjvh-n8vz.googlevideo.com
WARNING! Client Hello packet is too big and may cause issues!
Split packet!

не совсем понятно, чем вызывается и как побеждать такое поведение.

**Comment by Waujito** [comment]
Что происходит? Пакеты хрома с включенной опцией kyber могут быть очень большими, даже больше доступного MTU. На локальной машине пакет полностью попадает в youtubeUnblock за счёт GSO, но при отправке уже изменённого пакета используется rawsocket, и если загрузить больше чем MTU будет ошибка packet is too long. Анблок разбивает пакет так же, как это делается с фрагментацией для обхода DPI и отправляет частями. Я думаю, можно уже переместить этот варнинг в trace, чтобы не пугать окружающих)
