### ISSUE TITLE
Some unrecognized options

### ISSUE THREAD

**Issue by perfect7gentleman** [Waujito/youtubeUnblock#119]
Version git.
OpenWRT snapshot.
```
Wed Sep 18 22:37:57 2024 daemon.err youtubeUnblock[13572]: /usr/bin/youtubeUnblock: unrecognized option: packet-mark=32768
```
```
Wed Sep 18 22:34:49 2024 daemon.err youtubeUnblock[13137]: /usr/bin/youtubeUnblock: unrecognized option: synfake=0
```
```
Wed Sep 18 22:33:23 2024 daemon.err youtubeUnblock[13123]: /usr/bin/youtubeUnblock: unrecognized option: synfake=1
```

**Comment by Waujito** [comment]
Did you built it yourself with the SDK from scratch?

**Comment by perfect7gentleman** [comment]
Yes

**Comment by Waujito** [comment]
I updated the version of commit in openwrt branch, check it now

**Comment by perfect7gentleman** [comment]
З.Ы. Как понял, можно по-русски писать тут.

Стартует нормально, но выдаёт следующее:
```
Thu Sep 19 18:40:57 2024 daemon.info youtubeUnblock[15598]: ip4_payload_split: ipversion: Invalid argument
```

**Comment by Waujito** [comment]
Ждите апдейта. Это было исправлено в ветке kmod, придётся чуть подождать, пока я доделаю её и вмёржу в мейн. В целом, можете поискать сборки в actions с этой ветки, они должны работать

**Comment by Waujito** [comment]
https://github.com/Waujito/youtubeUnblock/actions/runs/10865382667

Вот тут можно найти хорошую версию

**Comment by Waujito** [comment]
Всё должно работать сейчас без ошибок

**Comment by perfect7gentleman** [comment]
Да, собрал git. Всё окей.
