### ISSUE TITLE
suggestion: would be nice to have ability to specify more hosts , not only googlevideo 

### ISSUE THREAD

**Issue by luckydevil13** [Waujito/youtubeUnblock#12]
subj

**Comment by zabbius** [comment]
@luckydevil13 you can do this by yourself, just add suffix file reading to `parse_args`, store suffixes with length to struct array and check it in the end of `analyze_tls_data`

I've tried to do this but was puzzled. How to read text file to lines array in pure C? =) 
Too many years in managed languages.

**Comment by Waujito** [comment]
Yes, the problem is not how to do that but how to maintain. It will require too much headache settings so I'm not ready for that now.



> I've tried to do this but was puzzled. How to read text file to lines array in pure C? =)

getline is perfect until you remember to free it out after EOF)

**Comment by zabbius** [comment]
> getline is perfect until you remember to free it out after EOF)
I mean that there is no such thing as std::list to store the lines. Using realloc on each line does not seem good. Writing custom container seems as overkill. So what is snandard way do to such things C? =)

**Comment by Waujito** [comment]
> > getline is perfect until you remember to free it out after EOF)
> 
> I mean that there is no such thing as std::list to store the lines. Using realloc on each line does not seem good. Writing custom container seems as overkill. So what is standard way do to such things in C? =)

A standard way is 128*64 static array)

**Comment by Waujito** [comment]
The issue is solved with https://github.com/Waujito/youtubeUnblock/commit/fb47d80543691446c8fd9cc41cdc615fee0a918f
