### ISSUE TITLE
установка

### ISSUE THREAD

**Issue by borisorlov21** [Waujito/youtubeUnblock#120]
Вадим дружище подскажи как поставить зто на арч линукс я в линуксе новичек

**Comment by aegoroff** [comment]
@borisorlov21 зачем тогда взяли арч если вы новичек? Арч не для новичков. А вообще также как и в любом другом линуксе - запустить программу из консоли с нужными параметрами. О том как сделать это демоном - рассказывать не буду - вам в документацию (арч вики)
