### ISSUE TITLE
ARMv8 Processor rev 4

### ISSUE THREAD

**Issue by absid89** [Waujito/youtubeUnblock#121]
Привет, подскажите что делать, выбираю вроде подходящий ipk, но не устанавливается. Есть предположение, что не поддерживается и нужно собирать самому, подтвердите так это или нет

youtubeUnblock-0.3.2-2d1b58b-arm_cortex-a8_vfpv3-openwrt-23.05.ipk

роутер Gl.Inet mt6000 , ARMv8 Processor rev 4

при попытке установить:
Executing package manager
Unknown package 'youtubeUnblock'.
Errors
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for youtubeUnblock found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package youtubeUnblock.

**Comment by Waujito** [comment]
А что `cat /etc/openwrt_release` напишет?

**Comment by absid89** [comment]
> А что `cat /etc/openwrt_release` напишет?

aarch64_cortex-a53... 

понял свою ошибку. установил - работает
