### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by anklimov** [Waujito/youtubeUnblock#123]
Model	FriendlyElec NanoPi R2S
Architecture	ARMv8 Processor rev 4
Target Platform	rockchip/armv8
Firmware Version	OpenWrt 23.05.4 r24012-d8dd03c46f / LuCI openwrt-23.05 branch git-24.212.79335-cdbe903
Kernel Version	5.15.162

During upload&install "youtubeUnblock-0.3.2-2d1b58b-aarch64_generic-openwrt-23.05.ipk" throw LUCI user interface:

```
Executing package manager
Unknown package 'youtubeUnblock'.
Errors
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-compat for youtubeUnblock
 * pkg_hash_fetch_best_installation_candidate: Packages for youtubeUnblock found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package youtubeUnblock.

The opkg install command failed with code 255.
```
Previous build for aarch64_generic-openwrt was compatible with rockchip/armv8

**Comment by Waujito** [comment]
Do opkg update before installation (update lists in Luci software page)

**Comment by anklimov** [comment]
> Do opkg update before installation (update lists in Luci software page)

Thank you, update helps
