### ISSUE TITLE
Видео  зависает через 5-10 минут

### ISSUE THREAD

**Issue by Mihrutkin** [Waujito/youtubeUnblock#124]
Routerich

И до этого в Zapret и на youtubeUnblock через 5-10 минут зависает видео/
Помогите понять это у моего провайдера мега умный DPI или какой-то хардварный косяк ?

**Comment by Mihrutkin** [comment]
Да, зависает видео до момента переключения на другое: через 5 до 15 минут.
И запрет ведет себя также. Через vpn все в порядке.

По поводу quick, я udp полностью заблокировал в роутере,так как на яндекс приставке нет возможности установить smarttube, а родное приложение лезет через quick

**Comment by Mihrutkin** [comment]
Youtubeunblock установлен 1.0. rc

**Comment by Waujito** [comment]
Попробуйте поставить seg2delay 100 и frag sni reverse 0
