### ISSUE TITLE
Luci and installing 0.3.2-3d50c00

### ISSUE THREAD

**Issue by 0x131313** [Waujito/youtubeUnblock#125]
**Installed:**
- `youtubeUnblock-0.3.2-3d50c00-mipsel_24kc-openwrt-23.05.ipk` (not v1.0.0-rc1)
- `kmod-nfnetlink-queue + kmod-nft-queue + kmod-nf-conntrack`
- reload firewall:
```
root@OpenWrt:~# /etc/init.d/firewall reload
Automatically including '/usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft'
```

Default `537-youtubeUnblock.nft`:
```
#!/usr/sbin/nft -f
# This file 

add rule inet fw4 mangle_forward tcp dport 443 ct original packets < 20 counter queue num 537 bypass
insert rule inet fw4 output mark and 0x8000 == 0x8000 counter accept
```

System log:
```
daemon.info youtubeUnblock[2449]: Using TCP segmentation
daemon.info youtubeUnblock[2449]: Fake SNI will be sent before each target client hello
daemon.info youtubeUnblock[2449]: Fragmentation Client Hello will be reversed
daemon.info youtubeUnblock[2449]: Past seq faking strategy will be used
daemon.info youtubeUnblock[2449]: GSO is enabled
daemon.info youtubeUnblock[2449]: IPv6 is enabled
daemon.info youtubeUnblock[2449]: Queue 537 started
```

Итог:
1) youtube не работает
2) отсутствует пункт **Services->youtubeUnblock** (и **Service** тоже)

___
Как вариант, попробовать поставить [v1.0.0-rc1](https://github.com/Waujito/youtubeUnblock/releases/tag/v1.0.0-rc1)?

Спасибо!

**Comment by Waujito** [comment]
Yes, you want to delete this version and install from rc1. I think I should mention in Readme that it is up to date only with pre release versions

**Comment by 0x131313** [comment]
> Yes, you want to delete this version and install from rc1. I think I should mention in Readme that it is up to date only with pre release versions

```
daemon.info youtubeUnblock[1578]: Queue 537 started
daemon.info youtubeUnblock[1578]: IPv6 is enabled
daemon.info youtubeUnblock[1578]: GSO is enabled
daemon.info youtubeUnblock[1578]: Past seq faking strategy will be used
daemon.info youtubeUnblock[1578]: Fragmentation Client Hello will be reversed
daemon.info youtubeUnblock[1578]: Fake SNI will be sent before each target client hello
daemon.info youtubeUnblock[1578]: Using TCP segmentation
daemon.info youtubeUnblock[1578]:
daemon.info youtubeUnblock[1578]: Bypasses deep packet inspection systems that relies on SNI
daemon.info youtubeUnblock[1578]: youtubeUnblock
```

Да, спасибо - помогло.
___

Хотел узнать по поводу стратегий - как лучше настраивать? (потому как из коробки у youtube ничего не изменилось)

**Comment by Waujito** [comment]
А у вас гудбай отваливался недавно?

**Comment by 0x131313** [comment]
> А у вас гудбай отваливался недавно?

`-9 --fake-gen 12 --fake-from-hex ...`
сейчас работает

**Comment by Waujito** [comment]
Понятно, ждите обновления (сейчас можете попробовать `fake sni seq len = 12`, но не факт, что отработает)

**Comment by 0x131313** [comment]
> Понятно, ждите обновление

ок, а что будет в обнове?

**Comment by 0x131313** [comment]
@Waujito 
дополню, гудбай работает и вот так:
`-5 -e1 -q --fake-gen 5 --fake-from-hex ...`

**Comment by Waujito** [comment]
Ждите обновление, скоро добавлю улучшенные фейки

**Comment by user26092024** [comment]
У меня есть пакет, который я скачивал 22.09 - 0.3.2-2d1b58b-aarch64_cortex-a53-openwrt-23.05.ipk, если его ставишь - то пункт в Services-youtubeUnblock присутствует, а вот допустим после установки пакета 0.3.2-3d50c00-aarch64_cortex-a53-openwrt-23.05 он пропадает, а если ставить начисто, то он не появляется.

**Comment by Waujito** [comment]
> @Waujito а без обновления подобные выше рецепты не реализовать?

Забыл наверное сюда написать, но скорее всего дело не в этом. Попробуйте seg2delay 100 и frag sni reverse 0

**Comment by 0x131313** [comment]
> Попробуйте seg2delay 100 и frag sni reverse 0

пробовал, но кажется дело ещё и в остальных параметрах, которые тоже крутил.
если есть возможность кинуть, так скажем, базовый дефолтный конфиг + добавлю эти параметры к ним, чтобы было от чего отталкиваться и что проверять.

спасибо!

**Comment by Waujito** [comment]
```sh
#!/bin/sh
[[ ! "$(uci -q get youtubeUnblock.youtubeUnblock)" == "" ]] && exit 0
touch /etc/config/youtubeUnblock
uci batch << EOI
set youtubeUnblock.youtubeUnblock='youtubeUnblock'
set youtubeUnblock.youtubeUnblock.frag='tcp'
set youtubeUnblock.youtubeUnblock.frag_sni_reverse='1'
set youtubeUnblock.youtubeUnblock.frag_middle_sni='1'
set youtubeUnblock.youtubeUnblock.frag_sni_pos='1'
set youtubeUnblock.youtubeUnblock.fk_winsize='0'
set youtubeUnblock.youtubeUnblock.seg2delay='0'
set youtubeUnblock.youtubeUnblock.packet_mark='32768'
set youtubeUnblock.youtubeUnblock.fake_sni='1'
set youtubeUnblock.youtubeUnblock.faking_strategy='pastseq'
set youtubeUnblock.youtubeUnblock.fake_sni_seq_len='1'
add_list youtubeUnblock.youtubeUnblock.sni_domains='googlevideo.com'
add_list youtubeUnblock.youtubeUnblock.sni_domains='ggpht.com'
add_list youtubeUnblock.youtubeUnblock.sni_domains='ytimg.com'
add_list youtubeUnblock.youtubeUnblock.sni_domains='youtube.com'
add_list youtubeUnblock.youtubeUnblock.sni_domains='play.google.com'
add_list youtubeUnblock.youtubeUnblock.sni_domains='youtu.be'
add_list youtubeUnblock.youtubeUnblock.sni_domains='googleapis.com'
add_list youtubeUnblock.youtubeUnblock.sni_domains='googleusercontent.com'
add_list youtubeUnblock.youtubeUnblock.sni_domains='gstatic.com'
add_list youtubeUnblock.youtubeUnblock.sni_domains='l.google.com'
EOI
uci commit
/etc/init.d/firewall restart &>/dev/null
exit 0
```

**Comment by 0x131313** [comment]
@Waujito 
```
config youtubeUnblock 'youtubeUnblock'
	option frag 'tcp'
	option fk_winsize '0'
	option seg2delay '100'
	option packet_mark '32768'
	list sni_domains 'googlevideo.com'
	list sni_domains 'ggpht.com'
	list sni_domains 'ytimg.com'
	list sni_domains 'youtube.com'
	list sni_domains 'play.google.com'
	list sni_domains 'youtu.be'
	list sni_domains 'googleapis.com'
	list sni_domains 'googleusercontent.com'
	list sni_domains 'gstatic.com'
	option fake_sni '1'
	option faking_strategy 'pastseq'
	option fake_sni_seq_len '1'
	option frag_sni_pos '1'
	option frag_sni_faked '1'
	option frag_middle_sni '1'
```
Вот мой текущий вышел и yt даже не появляется/не грузится

**Comment by Waujito** [comment]
frag sni faked по дефолту 0, если не поможет напишите https://t.me/waujito будем разбираться (нужен docker)

**Comment by Waujito** [comment]
Много чего поменялось со времени этого релиза. Добавилась кнопка reset в gui и изменились рабочие стратегии.

@asolocloud поставьте luci-app-youtubeUnblock
