### ISSUE TITLE
Начало работать нестабильно (многократное обновление страницы)

### ISSUE THREAD

**Issue by ElPadreX** [Waujito/youtubeUnblock#126]
Скачал исходники (лонировал с мастер ветки с гитхаб),скомпилировал,установил .Несколько месяцев все было замечательно,однако вот сейчас стало работать проблемно ,я вроде и обновил до последней актуальной..
В общем, вроде как и работает,ночерез раз после многократного обновления страницы ,ну и если видео меняется ,то кружит бесконечно,пока многократно не обновишь страницу.
Куда посмотреть для вероятного решения?

Конфиг системы: GNU Linux Mint 21.3 ,ядро: Linux linux 6.8.0-45-generic, арх.: x86_64

```
● youtubeUnblock.service - youtubeUnblock
     Loaded: loaded (/usr/local/lib/systemd/system/youtubeUnblock.service; enab>
     Active: active (running) since Sun 2024-09-22 14:38:01 MSK; 3 days ago

сен 25 15:27:21 linux youtubeUnblock[935]: Packet split in portion 194 582
сен 25 15:27:21 linux youtubeUnblock[935]: Google video!
сен 25 15:27:21 linux youtubeUnblock[935]: Packet split in portion 194 582
сен 25 15:27:21 linux youtubeUnblock[935]: Google video!
сен 25 15:27:21 linux youtubeUnblock[935]: Packet split in portion 193 582
сен 25 15:27:21 linux youtubeUnblock[935]: Google video!
сен 25 15:27:21 linux youtubeUnblock[935]: Packet split in portion 193 582
сен 25 15:27:21 linux youtubeUnblock[935]: Google video!
сен 25 15:27:21 linux youtubeUnblock[935]: Packet split in portion 193 582
сен 25 15:27:21 linux youtubeUnblock[935]: Google video!

````

Заранее благодарю за ответ.

**Comment by Waujito** [comment]
Ждите обновления, скоро добавлю улучшенные фейки

**Comment by Steve-61** [comment]
> Ждите обновления, скоро добавлю улучшенные фейки
Дайте инструкцию, как обновить? У меня до сих пор 3.0 версия.

**Comment by ElPadreX** [comment]
> Ждите обновления, скоро добавлю улучшенные фейки

Понятно. Спасибо, очень ждём . 

_Им (тем кто создаёт простым людям проблемы на ровном месте из-за своих больных амбиций) уготован отдельный котёл в аду! Я верю!_

**Comment by Waujito** [comment]
Попробуйте поставить seg2delay 100 и frag sni reverse 0

**Comment by ElPadreX** [comment]
> Попробуйте поставить seg2delay 100 и frag sni reverse 0

я правильно понимаю, что мнемне достаточно указать эти аргументы "ExecStart" в youtubeUnblock.service и перезагрузить службу?

**Comment by Waujito** [comment]
Вижу у вас старую версию анблока, судя по логам. Обновите её лучше до последней. Да, прописывать после execStart. Еще можно обновить в systemd скрипте правила, чтобы они затрагивали udp (см. Ридми) и поставить флаг —quic-drop

**Comment by ElPadreX** [comment]
> Вижу у вас старую версию анблока, судя по логам. Обновите её лучше до последней. Да, прописывать после execStart. Еще можно обновить в systemd скрипте правила, чтобы они затрагивали udp (см. Ридми) и поставить флаг —quic-drop

клоникровал проект с gh, собрал, установил , добавил в файл сервиса выше упомянутые команды, перезагрузил службу, получаю уорнинг:
`systemd[1]: youtubeUnblock.service: Current command vanished from the unit file, execution of the command list won't be `
