### ISSUE TITLE
сборка модуля для ramips/mt7621 "cannot find dependency kernel" 

### ISSUE THREAD

**Issue by koroni** [Waujito/youtubeUnblock#127]
здравствуйте!

1. 
имею перепрошитый роутер:
Model	D-Link DIR-853 R1
Architecture	MediaTek MT7621 ver:1 eco:3
Target Platform	ramips/mt7621
Firmware Version	OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-23.236.53405-fc638c8
Kernel Version	5.15.134

2.
подобрал под роутер прошивку:
https://hub.docker.com/layers/openwrt/sdk/ramips-mt7621-23.05.0/images/sha256-858642cfef319d73d71207c6e80c8058219f06b31bbe8787bbd980c7945d1746?context=explore

3.
собрался в докере (видел варнинги, но собралось)

4.
пытаюсь поставить модуль на роутер, получаю:

Unknown package 'kmod-youtubeUnblock'.
Errors
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-0e8896b32ade622c6f0cbd83ee589109) for kmod-youtubeUnblock
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-youtubeUnblock found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-youtubeUnblock.
The opkg install command failed with code 255

5.
прошу подсказать где проблема? что сравнивать?

**Comment by Waujito** [comment]
Я не думаю, что произойдёт что-то страшное, если отключить эту проверку на opkg (флагом).

Но конечно это не решение. Вообще, как я вижу у вас как будто используется таргет для mt7620 вместо 7621 (по хешу ядра). Попробуйте https://hub.docker.com/layers/openwrt/sdk/ramips-mt7620-23.05.0/images/sha256-858642cfef319d73d71207c6e80c8058219f06b31bbe8787bbd980c7945d1746?context=explore

**Comment by koroni** [comment]
флаг пока не пробовал.
попробовал: https://hub.docker.com/layers/openwrt/sdk/ramips-mt7620-23.05.0/images/sha256-858642cfef319d73d71207c6e80c8058219f06b31bbe8787bbd980c7945d1746?context=explore - таже ошибка

про одинаковый хеш ядря: если хеш ядра совпадает, то значит одинаковые я думаю, возможно обвязка роутеров разная

попробую SDK как второй резервный вариант (неохота убунту засорять)

а сейчас чуть позже перешью роутер совсем свежей прошивкой, возможно это поможет, отпишусь

**Comment by koroni** [comment]
вроде получилось!

1.
прошил роутер до версии:
Model	D-Link DIR-853 R1
Architecture	MediaTek MT7621 ver:1 eco:3
Target Platform	ramips/mt7621
Firmware Version	OpenWrt 23.05.4 r24012-d8dd03c46f / LuCI openwrt-23.05 branch git-24.086.45142-09d5a38
Kernel Version	5.15.162

2. 
собрал в докере https://hub.docker.com/r/openwrt/sdk/tags?name=mt7621-23.05.4

3.
модуль задеплоился (еще не проверял)

спасибо за советы!
