### ISSUE TITLE
Конечный список настроек которые нужно выполнить для режима модуля ядра

### ISSUE THREAD

**Issue by koroni** [Waujito/youtubeUnblock#128]
Несколько раз перечитывал инструкцию и не совсем понял, что нужно сделать в режиме модуля ядра.

На текущий момент:
1. создал модуль ядра в докере;
2. загрузил модуль в openwrt.

Читаю инструкцию https://github.com/Waujito/youtubeUnblock, пытаюсь понять какие настройки нужно сделать?
Правильно ли я понимаю, что для "модуля ядра" достаточно настроить флаги запуска? тогда нужно редактировать, файл  /etc/init.d/kmod_youtubeUnblock? но он не содержит секции "procd_set_param command /usr/bin/youtubeUnblock", но есть "modprobe kyoutubeUnblock" тут параметры вписывать?

прошу помощи )

**Comment by Waujito** [comment]
Да, мне желательно сделать что-то с этим. Вообще, у модуля есть очень хорошая абстракция над настройками. Вы можете найти все настройки в /sys/modules/youtubeUnblock/parameters

И просто для каждого параметра можно прописать и посмотреть его статус (я вроде как упоминал об этом в ридми)

**Comment by koroni** [comment]
по описанию, я бы предложил создать два нумерных раздела что бы не путать )
т.е. я меняю значение парметра и он прописывается? достаточно сервис перестартовать? или ребут нужен?
и еще вопрос, по дефолту trace=1 я рассчитывал увидеть в логах адреса сайтов которые он фейкнул, такого нет?

**Comment by Waujito** [comment]
> по описанию, я бы предложил создать два нумерных раздела что бы не путать ) т.е. я меняю значение параметра и он прописывается? достаточно сервис перестартовать? или ребут нужен? и еще вопрос, по дефолту trace=1, и я рассчитывал увидеть в логах названия доменов (SNI), которые он фейкнул, такого нет?

Не надо ничего рестартовать или еще что-нибудь делать. Установили параметр, он сам начал работать, в этом и прелесть модуля ядра. По логам не помню точно насчёт логрид, а вот в dmesg точно должно быть. НО! trace в режиме модуля ядра я не советую, особенно на openwrt. trace будет говорить об абсолютно каждом пакете, отправленным в систему. У меня лично роутер просто умирает от этого. И без trace=1 в dmesg отображается информация о пакетах, которые он обработал.

**Comment by koroni** [comment]
по дефолту трейс в модуле ядря у вас = 1, если это вредно, то надо наверное поменять дефолт
ну вот я не вижу в логах про пакеты. как можно проверить что пакеты обрабатываются? какую строчку искать в логах?

**Comment by koroni** [comment]
т.е. trace=1 а на самом деле ноль?

**Comment by koroni** [comment]
dmesg | grep SNI - нет строк

**Comment by Waujito** [comment]
Хм, странно
А что будет в dmesg если всё-таки сделать 
`echo 1 > /sys/module/kyoutubeUnblock/parameters/trace`

Не забудьте вернуть его обратно после проверки
`echo 0 > /sys/module/kyoutubeUnblock/parameters/trace`

**Comment by koroni** [comment]
echo 1 > /sys/module/kyoutubeUnblock/parameter/trace

**Comment by koroni** [comment]
опечатка echo 1 > /sys/module/kyoutubeUnblock/parameter**s**/trace
вроде пишет, но при открытии через vi вот такая картина (кстати логов не добавилось)
![image](https://github.com/user-attachments/assets/5e1f67be-d80b-454e-9b1c-a3ed9d04532f)

**Comment by koroni** [comment]
отбой, в dmesg появилось 
`root@OpenWrt:/sys/module/kyoutubeUnblock/parameters# dmesg | grep SNI
[ 7392.309574] Target SNI detected: www.youtube.com
[ 7395.404169] Target SNI detected: yt3.ggpht.com
[ 7395.404254] Target SNI detected: yt3.ggpht.com
[ 7395.404642] Target SNI detected: yt3.ggpht.com
[ 7397.033233] Target SNI detected: play.google.com
[ 7397.126850] Target SNI detected: play.google.com
`

**Comment by koroni** [comment]
в общем странно, он постоянно показывает =1
а если записывать 0 или 1 пока не смог увидеть разницы.

**Comment by koroni** [comment]
хотя запись echo 1 > /sys/module/kyoutubeUnblock/parameters/trace - повесила роутер ))

**Comment by koroni** [comment]
вот еще вопрос: если я включаю sni_domains=all то фейковые пакеты будут генериться для любых соединений?
дело в том что в моей задаче нужно, что бы абс все пакеты изменялись защищаясь от dpi

**Comment by koroni** [comment]
но это касается всех рукопожатий. а если фейкать абс все пакеты? это достижимо?

**Comment by koroni** [comment]
все разобрался, спасибо за помощь!

**Comment by YBS-PC** [comment]
Если на openwrt можно использовать и модуль ядра и обычный пакет, то есть какие то преимущества использования модуля ядра, они чувствуется? 
И еще, модуль ядра наверное на каждый роутер отдельно надо генерить в зависимости от проца?

**Comment by Waujito** [comment]
> Если на openwrt можно использовать и модуль ядра и обычный пакет, то есть какие то преимущества использования модуля ядра, они чувствуется? И еще, модуль ядра наверное на каждый роутер отдельно надо генерить в зависимости от проца?

В зависимости и от проца, и от версии ядра (openwrt предоставляет очень мощный sdk, который это всё абстрагирует). Поэтому автоматические релизы увы не получится делать. Зачем это нужно? Вообще, модуль позволяет обрабатывать каждый пакет без потерь в скорости (для обычного анблока мы используем коннбайтс). Ещё модуль не требует практически никаких зависимостей, кроме ядра и самого фаервола, в то время, как для обычного анблока требуются еще и модули netlink queue, и модули фаервола для queue, и сам юзер спейс фаервол с поддержкой queue
