### ISSUE TITLE
Asus-Merlin возможно ли сие чудо?

### ISSUE THREAD

**Issue by r0otx** [Waujito/youtubeUnblock#130]
Поставил entware, попробовал побаловаться пакетами из коробки в частности попытался запустить v2rayA с гуём, но тот почему-то в упор не хочет запускаться в режиме redirect или tproxy оперируя невозможностью выполнить операцию с iptables, не нравится аргумент -w 2, ну да ладно. Решил поискать альтернативы, так как все это затевается лишь ради ютуба, наткнулся на сей пакет, думаю, а возможно ли развернуть?

**Comment by Waujito** [comment]
Да, есть отдельная сборка под entware, посмотрите пакеты с названием entware
