### ISSUE TITLE
Скрипт работает только с открытой командной строкой

### ISSUE THREAD

**Issue by wdclord** [Waujito/youtubeUnblock#131]
Добрый день, у меня youtube работает только если открыта командная строка с которой запускал скрипт.

Дано: Роутер на Мерлине `ASUSWRT-Merlin RT-AX86U_PRO`
Шаги:
1. Устанавливаю пакет `youtubeUnblock_0.3.2-3d50c00-1_aarch64-3.10.ipk` с помощью entware: `opkg install youtubeUnblock_0.3.2-3d50c00-1_aarch64-3.10.ipk`
2. Запускаю скрипт командой `/opt/etc/init.d/S91youtubeUnblock start`
3. Пробую открыть youtube - всё работает
4. Проверяю статус `/opt/etc/init.d/S91youtubeUnblock status` - говорит, что `stopped`, но youtube всё ещё работает
5. Закрываю powershell с сессией - youtube перестает работать

Подскажите, пожалуйста, как это починить?

**Comment by Cycypa** [comment]
Вам нужно написать команду `service `
она выдаст список всех сервисов и их статус, там должен быть и сервис `youtubeUnblock`
вероятнее всего его вам надо запустить командой `service youtubeUnblock start`

**Comment by Waujito** [comment]
А что произойдёт если обернуть команду старта в ( /opt/etc/init.d/youtubeUnblock start & )?

И что будет если так же обернуть команду старта внутри скрипта (начинается с $PROCD и заканчивается на амперсанд) (в конце должен быть только один амперсанд

**Comment by wdclord** [comment]
> А что произойдёт если обернуть команду старта в ( /opt/etc/init.d/youtubeUnblock start & )
> 
> И, если сработает, что будет если так же обернуть команду старта внутри скрипта (начинается с $PROCD и заканчивается на амперсанд) (в конце должен быть только один амперсанд.
> 
> (Между запусками killall youtubeUnblock)

Попробовал оба варианта (killall запускал перед каждой попыткой) - в итоге поведение не изменилось.
Всё также работает пока не закрываешь powershell. Стоит закрыть консоль и youtube сразу перестает работать.



> Вам нужно написать команду `service ` она выдаст список всех сервисов и их статус, там должен быть и сервис `youtubeUnblock` вероятнее всего его вам надо запустить командой `service youtubeUnblock start`
Получается такой ответ:
`/tmp/home/root# service S91youtubeUnblock`
`Done.`

На `service S91youtubeUnblock start`
отвечает `Usage: service <action_service>`

**Comment by Waujito** [comment]
Для сервиса скорее всего надо поменять местами анблок и старт.

Ещё есть идея запустить анблок вообще без скрипта: `(/opt/usr/bin/youtubeUnblock &> /tmp/logs.txt &) `. За одно и возможность посмотреть логи

**Comment by wdclord** [comment]
> Для сервиса скорее всего надо поменять местами анблок и старт.

Не помогло, к сожалению.

> Ещё есть идея запустить анблок вообще без скрипта: `(/opt/usr/bin/youtubeUnblock &> /tmp/logs.txt &) `. Заодно появляется возможность посмотреть логи

Запустил, в логах не нашел его в этом пути. Как узнать, где он установлен?
`-sh: /opt/usr/bin/youtubeUnblock: not found`

**Comment by Waujito** [comment]
> -sh: /opt/usr/bin/youtubeUnblock: not found

Ой, да, /opt/bin/youtubeUnblock

**Comment by wdclord** [comment]
> (/opt/usr/bin/youtubeUnblock &> /tmp/logs.txt &)

Получилось запустить, но лог вообще пустой. Ютуб тоже работает пока не закроешь консоль. После открытия консоли лог тоже пустой, процесс уже убит почему-то

**Comment by Waujito** [comment]
В том, что лог пустой проблема скорее всего буфферизации. Есть еще одно решение - daemonize. Его скорее всего придётся поставить через opkg install. Возможно, что-то типа `daemonize -o /tmp/logs.txt /opt/usr/bin/youtubeUnblock` сработает.

**Comment by wdclord** [comment]
> В том, что лог, пустой проблема буфферизации. Есть еще одно решение - daemonize. Его, скорее всего, придётся поставить через opkg install. Возможно, что-то типа `daemonize -o /tmp/logs.txt /opt/usr/bin/youtubeUnblock` сработает.

Огонь! С daemonize всё взлетело. Теперь работает с закрытой консолью 👍 
Спасибо!

Это какая-то особенность асус мерлина?

**Comment by Waujito** [comment]
> Это какая-то особенность асус мерлина?

Вообще, такого быть не должно, и если на одном не работает, значит не работает на всех, но вы первый, кто об этом пишет.

**Comment by Di1Ly** [comment]
Проблема воспроизводиться на роутерах ASUS с прошивкой Merlin.
Решение - запускать скрипт daemonize /opt/etc/init.d/S91youtubeUnblock start
Не уверен, что так задумывалось....

**Comment by r0otx** [comment]
Аналогичная проблема на том же роутере и есть еще GT-AX11000 раньше работало, после обновления на rc5 тоже после закрытия консоли процесс умирает, пробовал и nohup и амперсанд, не срабатывает, через daemonize взлетело, спасибо!

**Comment by Waujito** [comment]
> Аналогичная проблема на том же роутере и есть еще GT-AX11000 раньше работало, после обновления на rc5 тоже после закрытия консоли процесс умирает, пробовал и nohup и амперсанд, не срабатывает, через daemonize взлетело, спасибо!

На rc5 есть флаг --daemonize, который позволяет без сторонних утилит запустить демоном
