### ISSUE TITLE
Через раз работает на всех устройствах apple

### ISSUE THREAD

**Issue by BrainDeLook** [Waujito/youtubeUnblock#133]
После перепрошивки маршрутизатора и переустановки youtubeunblock на openwrt столкнулся с проблемой - youtube на мобильных устройствах прогружает страницу через раз. либо нужно ждать от 2 минут до бесконечности. На Пк и Андроид все работает хорошо, а вот apple TV и другие apple девайсы ни в какую. До переустановки работало все идеально. Quic drop включен, версия релиз кандидат

Заранее спасибо за помощь!

Sun Sep 29 12:35:35 2024 daemon.err uhttpd[1077]: [!] Automatically including '/usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft'
Sun Sep 29 12:35:19 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: firebaselogging-pa.googleapis.com
Sun Sep 29 12:34:36 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: yt3.ggpht.com
Sun Sep 29 12:34:34 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: i.ytimg.com
Sun Sep 29 12:34:32 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: i.ytimg.com
Sun Sep 29 12:34:26 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: i.ytimg.com
Sun Sep 29 12:34:19 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: firebaselogging-pa.googleapis.com
Sun Sep 29 12:34:14 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:34:11 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: www.youtube.com
Sun Sep 29 12:34:08 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: redirector.googlevideo.com
Sun Sep 29 12:34:08 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: redirector.googlevideo.com
Sun Sep 29 12:34:08 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: yt3.ggpht.com
Sun Sep 29 12:34:05 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: www.youtube.com
Sun Sep 29 12:34:03 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: firebaselogging-pa.googleapis.com
Sun Sep 29 12:34:02 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: www.youtube.com
Sun Sep 29 12:34:02 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: s.youtube.com
Sun Sep 29 12:34:01 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: rr6---sn-jvhnu5g-c35d.googlevideo.com
Sun Sep 29 12:34:01 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: rr6---sn-jvhnu5g-c35d.googlevideo.com
Sun Sep 29 12:33:58 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: yt3.ggpht.com
Sun Sep 29 12:33:57 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:33:55 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:33:55 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauth2.googleapis.com
Sun Sep 29 12:33:53 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:33:53 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauth2.googleapis.com
Sun Sep 29 12:33:53 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: i.ytimg.com
Sun Sep 29 12:33:53 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: youtubei.googleapis.com
Sun Sep 29 12:33:53 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:33:53 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:33:53 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: play.googleapis.com
Sun Sep 29 12:33:53 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauth2.googleapis.com
Sun Sep 29 12:33:43 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:33:40 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:33:40 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: play.googleapis.com
Sun Sep 29 12:33:40 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: play.googleapis.com
Sun Sep 29 12:33:39 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: play.googleapis.com
Sun Sep 29 12:33:38 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:33:37 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: youtubei.googleapis.com
Sun Sep 29 12:33:37 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:33:35 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:33:35 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauth2.googleapis.com
Sun Sep 29 12:33:34 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: redirector.googlevideo.com
Sun Sep 29 12:33:34 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: redirector.googlevideo.com
Sun Sep 29 12:33:34 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauth2.googleapis.com
Sun Sep 29 12:33:34 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:33:34 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:33:34 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauth2.googleapis.com
Sun Sep 29 12:33:29 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: play.googleapis.com
Sun Sep 29 12:32:32 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: mail.google.com
Sun Sep 29 12:32:22 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: dl.google.com
Sun Sep 29 12:32:04 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: graph.facebook.com
Sun Sep 29 12:31:51 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: graph.facebook.com
Sun Sep 29 12:31:49 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:31:37 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: play.google.com
Sun Sep 29 12:31:37 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:31:37 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauth2.googleapis.com
Sun Sep 29 12:31:32 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: fonts.gstatic.com
Sun Sep 29 12:31:30 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: fonts.gstatic.com
Sun Sep 29 12:31:30 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: mail.google.com
Sun Sep 29 12:31:29 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: www.gstatic.com
Sun Sep 29 12:31:28 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: ssl.gstatic.com
Sun Sep 29 12:31:28 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: www.gstatic.com
Sun Sep 29 12:31:27 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:31:19 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: youtubei.googleapis.com
Sun Sep 29 12:31:19 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:31:02 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: ssl.gstatic.com
Sun Sep 29 12:30:59 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:30:59 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauth2.googleapis.com
Sun Sep 29 12:30:52 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: mail-attachment.googleusercontent.com
Sun Sep 29 12:30:49 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauthaccountmanager.googleapis.com
Sun Sep 29 12:30:49 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: oauth2.googleapis.com
Sun Sep 29 12:30:48 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: mail.google.com
Sun Sep 29 12:30:45 2024 daemon.info youtubeUnblock[8524]: Target SNI detected: www.googleapis.com

**Comment by BrainDeLook** [comment]
Так же через safari на айфоне все работаетб похоже проблема в самом приложении youtube для мобилок и ТВ

**Comment by BrainDeLook** [comment]
Опытным путем было выяснено что главная страница прогружается на всех устройствах с примененным флагом fragmentation strategy none, однако это дало эффект только на загрузку главной страницы и поиска видео, сами ролики не загружаются на всех устройствах включая пк

**Comment by Waujito** [comment]
Проблема только у яблок и сафари? Если поставить sni domains all, другие сайты будут открываться?

**Comment by BrainDeLook** [comment]
Было выяснено что проблема заключалась в флаге frag sni pos. Ставим на 1 и будет работать на всех устройствах как раньше. Не идеально, бывает не подгружает превью на ютубе, но лучше так чем никак

**Comment by Waujito** [comment]
> Было выяснено что проблема заключалась в флаге frag sni pos. Ставим на 1 и будет работать на всех устройствах как раньше. Не идеально, бывает не подгружает превью на ютубе, но лучше так чем никак

frag sni pos по дефолту 1

**Comment by BrainDeLook** [comment]
> > Было выяснено что проблема заключалась в флаге frag sni pos. Ставим на 1 и будет работать на всех устройствах как раньше. Не идеально, бывает не подгружает превью на ютубе, но лучше так чем никак
> 
> frag sni pos по дефолту 1

Возможно при переустановке на realese candidate версию дефолтные настройки слетели. Но сейчас все работает стабильно.
