### ISSUE TITLE
Ошибки в логе, но youtube РАБОТАЕТ!

### ISSUE THREAD

**Issue by nitro3188** [Waujito/youtubeUnblock#136]
```
Tue Oct  1 17:38:50 2024 daemon.info youtubeUnblock[5355]: Bypasses deep packet inspection systems that relies on SNI
Tue Oct  1 17:38:50 2024 daemon.info youtubeUnblock[5355]: youtubeUnblock
Tue Oct  1 17:37:49 2024 daemon.info youtubeUnblock[4847]: Queue 537 started
Tue Oct  1 17:37:49 2024 daemon.info youtubeUnblock[4847]: IPv6 is disabled
Tue Oct  1 17:37:49 2024 daemon.info youtubeUnblock[4847]: GSO is enabled
Tue Oct  1 17:37:49 2024 daemon.info youtubeUnblock[4847]: Past seq faking strategy will be used
Tue Oct  1 17:37:49 2024 daemon.info youtubeUnblock[4847]: Fragmentation Client Hello will be reversed
Tue Oct  1 17:37:49 2024 daemon.info youtubeUnblock[4847]: Fake SNI will be sent before each target client hello
Tue Oct  1 17:37:49 2024 daemon.info youtubeUnblock[4847]: Using TCP segmentation
Tue Oct  1 17:37:49 2024 daemon.info youtubeUnblock[4847]:
Tue Oct  1 17:37:49 2024 daemon.info youtubeUnblock[4847]: Bypasses deep packet inspection systems that relies on SNI
Tue Oct  1 17:37:49 2024 daemon.info youtubeUnblock[4847]: youtubeUnblock
Tue Oct  1 17:02:36 2024 daemon.notice procd: /etc/rc.d/S19firewall: /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft:21:3-3: Error: syntax error, unexpected <
Tue Oct  1 17:02:36 2024 daemon.notice procd: /etc/rc.d/S19firewall: /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft:20:3-3: Error: syntax error, unexpected <
Tue Oct  1 17:02:36 2024 daemon.notice procd: /etc/rc.d/S19firewall: /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft:19:5-5: Error: syntax error, unexpected <
Tue Oct  1 17:02:36 2024 daemon.notice procd: /etc/rc.d/S19firewall: /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft:18:3-3: Error: syntax error, unexpected <
Tue Oct  1 17:02:36 2024 daemon.notice procd: /etc/rc.d/S19firewall: /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft:14:3-3: Error: syntax error, unexpected >
Tue Oct  1 17:02:36 2024 daemon.notice procd: /etc/rc.d/S19firewall: /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft:12:28-28: Error: syntax error, unexpected '=', expecting string or last
Tue Oct  1 17:02:36 2024 daemon.notice procd: /etc/rc.d/S19firewall: /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft:11:18-18: Error: syntax error, unexpected '=', expecting string or last
Tue Oct  1 17:02:36 2024 daemon.notice procd: /etc/rc.d/S19firewall: /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft:9:7-7: Error: syntax error, unexpected '=', expecting string or last
Tue Oct  1 17:02:36 2024 daemon.notice procd: /etc/rc.d/S19firewall: /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft:8:1-1: Error: syntax error, unexpected <
Tue Oct  1 17:02:36 2024 daemon.notice procd: /etc/rc.d/S19firewall: /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft:7:1-1: Error: syntax error, unexpected
```
Добрый вечер!
Установлено:
youtubeUnblock-0.3.2-2d1b58b-mipsel_24kc-openwrt-23.05
kmod-nfnetlink-queue + kmod-nft-queue + kmod-nf-conntrack

youtube работает, но что-то с синтаксисом в файерволле не так?

**Comment by Waujito** [comment]
А у вас чистый опенврт?

**Comment by nitro3188** [comment]
да, 23.05.5
самое интересное, после нескольких ребутов лог стал нормальный, что было неизвестно
`Tue Oct  1 20:00:39 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: yt3.ggpht.com
Tue Oct  1 19:56:40 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: rr7---sn-uxaxufvg0-n8ve.googlevideo.com
Tue Oct  1 19:54:36 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: rr7---sn-n8v7znly.googlevideo.com
Tue Oct  1 19:54:17 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: i.ytimg.com
Tue Oct  1 19:54:11 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: rr7---sn-n8v7znly.googlevideo.com
Tue Oct  1 19:54:09 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: rr5---sn-uxaxufvg0-n8ve.googlevideo.com
Tue Oct  1 19:54:05 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: rr7---sn-n8v7znly.googlevideo.com
Tue Oct  1 19:54:02 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: rr7---sn-n8v7znly.googlevideo.com
Tue Oct  1 19:54:02 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: rr7---sn-n8v7znly.googlevideo.com
Tue Oct  1 19:54:02 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: rr7---sn-n8v7znly.googlevideo.com
Tue Oct  1 19:53:46 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: www.youtube.com
Tue Oct  1 19:53:21 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: www.gstatic.com
Tue Oct  1 19:53:21 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: yt3.ggpht.com
Tue Oct  1 19:53:19 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: rr5---sn-uxaxufvg0-n8ve.googlevideo.com
Tue Oct  1 19:53:18 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: play.google.com
Tue Oct  1 19:53:18 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: rr5---sn-uxaxufvg0-n8ve.googlevideo.com
Tue Oct  1 19:53:18 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: play.google.com
Tue Oct  1 19:53:17 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: www.youtube.com
Tue Oct  1 19:53:17 2024 daemon.info youtubeUnblock[5037]: Target SNI detected: www.youtube.com
Tue Oct  1 19:50:43 2024 daemon.info youtubeUnblock[5037]: Queue 537 started
Tue Oct  1 19:50:43 2024 daemon.info youtubeUnblock[5037]: IPv6 is disabled
Tue Oct  1 19:50:43 2024 daemon.info youtubeUnblock[5037]: GSO is enabled
Tue Oct  1 19:50:43 2024 daemon.info youtubeUnblock[5037]: Past seq faking strategy will be used
Tue Oct  1 19:50:43 2024 daemon.info youtubeUnblock[5037]: Fragmentation Client Hello will be reversed
Tue Oct  1 19:50:43 2024 daemon.info youtubeUnblock[5037]: Fake SNI will be sent before each target client hello
Tue Oct  1 19:50:43 2024 daemon.info youtubeUnblock[5037]: Using TCP segmentation
Tue Oct  1 19:50:43 2024 daemon.info youtubeUnblock[5037]:
Tue Oct  1 19:50:43 2024 daemon.info youtubeUnblock[5037]: Bypasses deep packet inspection systems that relies on SNI
Tue Oct  1 19:50:43 2024 daemon.info youtubeUnblock[5037]: youtubeUnblock`

**Comment by 0x131313** [comment]
@nitro3188 а можете, пожалуйста, поделиться своим конфигом?

**Comment by nitro3188** [comment]
пожалуйста
![3](https://github.com/user-attachments/assets/0cf35b55-ecbf-41de-8c87-305c8032efda)
![2](https://github.com/user-attachments/assets/37af786c-a8d8-40eb-b230-f222d15cd6a3)
![1](https://github.com/user-attachments/assets/ed8321d7-68dc-4925-8e3a-b3c3a029c08d)

**Comment by Waujito** [comment]
Раз работает, закрою
