### ISSUE TITLE
Вылетает игра Call of Duty

### ISSUE THREAD

**Issue by R0iZ** [Waujito/youtubeUnblock#137]
При активной службе youtubeunblock у ребенка вылетает игра Call of Duty, при этом никакой ошибки не выдает. Если на роутере отключаю youtubeunblock, игра работает нормально. Настроек youtubeunblock никаких не делал, все по умолчанию после установки. Может кто подсказать, что в настройках можно подкрутить?

**Comment by Waujito** [comment]
А у вас анблок с sni domains all?

**Comment by R0iZ** [comment]
> А у вас анблок с sni domains all?

Нет, конечно. Прописаны только домены ютуб. Так по умолчанию ставится.

**Comment by R0iZ** [comment]
> А у вас анблок с sni domains all?

Отключил фрагментацию пока, посмотрю как пойдёт.

**Comment by R0iZ** [comment]
К сожалению, с отключенной фрагментацией не работает Youtube. Какие еще настройки могут влиять на трафик?  Да и вообще, почему трафик к доменам не в списке как-то модифицируется?

**Comment by Waujito** [comment]
А том то и проблема, что он не модифицируется

**Comment by R0iZ** [comment]
> В том то и проблема, что он не модифицируется. Вот единственное что могу предположить - параметр quic block, который будет идти на весь трафик

Этот параметр я включал и выключал, картина не меняется. Попробую отследить, на какие домены обращается игра и добавить их в исключение

**Comment by R0iZ** [comment]
Поставил "drop quick" и работает игра, не вылетает. Хотя точно так уже делал, может проблема в игре была
