### ISSUE TITLE
cannot find dependency libubox &  libubus

### ISSUE THREAD

**Issue by YBS-PC** [Waujito/youtubeUnblock#138]
требует 
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libubox20230523 for rpcd-mod-luci
 * pkg_hash_check_unresolved: cannot find dependency libubus20230605 for rpcd-mod-luci
 * pkg_hash_check_unresolved: cannot find dependency libubox20230523 for cgi-io
 * pkg_hash_check_unresolved: cannot find dependency libubus20230605 for cgi-io
но устанавливается
а последние прошивки формируются с libubus20231128 и libubox20240329 - может есть возможность связать просто с libubox и libubus без версий

**Comment by YBS-PC** [comment]
видимо это сами rpcd-mod-luci и cgi-io не перестроились

**Comment by Waujito** [comment]
В общем, надо разделять luci и просто сборку для openwrt
