### ISSUE TITLE
Потрачено

### ISSUE THREAD

**Issue by manchelsi** [Waujito/youtubeUnblock#14]
Похоже, что начали дропать фрагментированные пакеты

**Comment by manchelsi** [comment]
А нет, с более большим делеем из https://github.com/Waujito/youtubeUnblock/pull/11 не потрачено

**Comment by Waujito** [comment]
А, это вы писали в коммит)

Я отключил делей по дефолту, чтобы он не рушил соединение + создавать отдельный поток каждый раз может быть затратно.  Теперь через специальную опцию включать.
