### ISSUE TITLE
Не видно службы youtubeUnblock в service

### ISSUE THREAD

**Issue by 31337cat** [Waujito/youtubeUnblock#140]
Здравствуйте.
Установлена чистая 
![Unblock_1](https://github.com/user-attachments/assets/63172607-ead2-4dd4-97de-6afafe6b85eb)
![Unblock_2](https://github.com/user-attachments/assets/ca9f4223-7ec1-472f-a009-48a57bb85268)
![Unblock_3](https://github.com/user-attachments/assets/0d378f19-f9c7-4ec3-946c-eef619f72ad0)

OpenWrt 23.05.3 (r23809-234f1a2efa)
установлен пакет youtubeUnblock-0.3.2-3d50c00-mipsel_24kc-openwrt-23.05
IPV6 -включен.  В прошлых версиях его отключал - были проблемы с ним.
Не отображается служба в интерфейсе LUCI.
При этом в логе видно что работает, но как то странно - есть задержки в трансляции.

**Comment by lu1isss** [comment]
Установите пре релиз версию, в ней есть интерфейс https://github.com/Waujito/youtubeUnblock/releases

**Comment by 31337cat** [comment]
Удалил установленный пакет -  ребутнул роутер (что точно ничего не осталось от него). Установил рекомендованный по ссылке https://github.com/Waujito/youtubeUnblock/releases/tag/v1.0.0-rc1 . Без изменений. 
![Unblock_4](https://github.com/user-attachments/assets/b8109397-ce9e-4846-b0c6-03855dcd30f5)

**Comment by 31337cat** [comment]
Удалил этот пакет - https://github.com/Waujito/youtubeUnblock/releases/tag/v1.0.0-rc1 -  Ребут роутера. Установил заново - youtubeUnblock-0.3.2-2d1b58b-mipsel_24kc-openwrt-23.05 .
ребут Роутера. Появилась служба. Похоже , нужно обязательно через Удаление с перезагрузкой ставить пакет.
![Unblock_5](https://github.com/user-attachments/assets/005462e6-4533-4d1e-9423-4476ad9d68f5)
