### ISSUE TITLE
Please fix: software / hardware based offloading for routing NAT is not working on ethernet devices on v25.05.5 build with this ipk, in order IPK works all this should be disabled.

### ISSUE THREAD

**Issue by jagga99** [Waujito/youtubeUnblock#141]
Please fix: software / hardware based offloading for routing NAT is not working on ethernet devices on v25.05.5 build with this ipk, in order IPK works all this should be disabled.

**Comment by jagga99** [comment]
приложение не работает при включенном software/hardware offloading для ethernet клиентов

**Comment by Waujito** [comment]
А как я это пофикшу?) Это особенности роутинга. software/hardware offloading подразумевает пропуск обработки пакетов правилами фаервола. Возможно, модуль в ядро будет работать, но я не уверен. Да даже если будет, он убьёт производительность.
