### ISSUE TITLE
Please clarify how to force youtubeunblock work together with SSClash on openwrt (https://github.com/zerolabnet/ssclash), thanks

### ISSUE THREAD

**Issue by jagga99** [Waujito/youtubeUnblock#142]
Please clarify how to force youtubeunblock work together with SSClash (https://github.com/zerolabnet/ssclash) on openwrt.

**Comment by Waujito** [comment]
I think it is possible to use youtubeUnblock along with this tool. But youtubeUnblock will work on more low-level layer and will process every packet independetly of this. But theoretically this should work

**Comment by jagga99** [comment]
may you add a guide or explain below how to do this?

**Comment by Waujito** [comment]
I think this should work out of the box

**Comment by jagga99** [comment]
Im using this [youtubeUnblock-0.3.2-2d1b58b-aarch64_cortex-a53-openwrt-23.05.ipk](https://github.com/Waujito/youtubeUnblock/releases/download/v1.0.0-rc1/youtubeUnblock-0.3.2-2d1b58b-aarch64_cortex-a53-openwrt-23.05.ipk) and it is not working together with SSClash

**Comment by ALexeyAL1** [comment]
> Please clarify how to force youtubeunblock work together with SSClash (https://github.com/zerolabnet/ssclash) on openwrt.

Попахивает рекламой. Нет?

**Comment by jagga99** [comment]
но chatgpt не смог предложить правки в nftables rules

**Comment by Waujito** [comment]
Я не думаю, что имеет смысл продолжать это. Как работает анблок описано. Если он перестаёт работать от другого сервиса, запущенного параллельно с анблоком и тоже каким-либо образом изменяющего трафик - это вряд ли проблемы анблока. Если он не работает вообще, можете написать
