### ISSUE TITLE
Помощь с опредилением стратегии обхода блокировок

### ISSUE THREAD

**Issue by ALexeyAL1** [Waujito/youtubeUnblock#143]
Хотел семье сделать приятное, на распбери пи3 поставил опенВРТ и хотел быстро сделать мини роутер для мобилок. С бубном и горой мануалов установил и настроил опенВРТ, в анблок сутки игрался с галочками и циферками, но чуда так и на произошло. Знаний не то чтобы много, скачал запрет от бол-ван и почти 12 часов тестировал блокчек
Вот что он показал. Я надеялся найти похожие настройки в анблоке и сделать такие же настройки, но почему-то ничего похожего не нашел.

Еще видел тут подсказывают настройки если сказать при каких ключах работает гудбайдпи, но он как назло не работает. Помогие разобраться какие настройки применить в анблоке, чтобы посмотреть ютуб не только на мобильном интернете.
````
* SUMMARY
ipv4 instagram.com curl_test_http : winws not working
ipv4 instagram.com curl_test_https_tls12 : winws not working
ipv4 instagram.com curl_test_http3 : winws not working
ipv4 youtube.com curl_test_http : working without bypass
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake,split2 --dpi-desync-ttl=10 --dpi-desync-fake-tls=0x00000000 --dpi-desync-split-pos=1
ipv4 youtube.com curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=fake --dpi-desync-repeats=5
ipv4 meduza.io curl_test_http : winws --wf-l3=ipv4 --wf-tcp=80 --dpi-desync=split2 --dpi-desync-split-pos=3 --hostcase
ipv4 meduza.io curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake --dpi-desync-fooling=datanoack --dpi-desync-fake-tls=0x00000000
ipv4 meduza.io curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=fake
ipv4 x.com curl_test_http : working without bypass
ipv4 x.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=syndata
ipv4 x.com curl_test_http3 : winws not working
ipv4 rutracker.org curl_test_http : winws --wf-l3=ipv4 --wf-tcp=80 --dpi-desync=split2 --dpi-desync-split-http-req=host
ipv4 rutracker.org curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=split2
ipv4 rutracker.org curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=fake

Please note this SUMMARY does not guarantee a magic pill for you to copy/paste and be happy.
Understanding how strategies work is very desirable.
This knowledge allows to understand better which strategies to prefer and which to avoid if possible, how to combine strategies.
Blockcheck does it's best to prioritize good strategies but it's not bullet-proof.
It was designed not as magic pill maker but as a DPI bypass test tool.
````

**Comment by ALexeyAL1** [comment]
Вот что сказал гудчек для гудбайДПИ
```
-------------------------------

Strategies with 0 out of 23 successes:
-e 1 -q --native-frag --wrong-seq --fake-with-sni www.google.com
-e 1 -q --reverse-frag --wrong-seq --fake-with-sni www.google.com

Strategies with 4 out of 23 successes:
-e 1 -q --native-frag --wrong-seq
-e 1 -q --reverse-frag --wrong-seq
-e 1 -q --native-frag --wrong-seq --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5
-e 1 -q --reverse-frag --wrong-seq --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 10

-------------------------------

DNS-over-HTTPS resolver used: "https://one.one.one.one/dns-query"

-------------------------------

Log saved to "D:\DPI\GoodCheck\Logs\Log_GoodCheck_06-10-2024_20-47-08.txt"

-------------------------------

Script ended without catched errors
```

**Comment by Waujito** [comment]
А вы пробовали seg2delay=100, frag sni reverse=0, quic drop? Учтите, что остальные настройки должны остаться по умолчанию.

**Comment by ALexeyAL1** [comment]
> А вы пробовали seg2delay=100, frag sni reverse=0, quic drop? Учтите, что остальные настройки должны остаться по умолчанию.

Еще нет, но сегодня попробую. Только пока не знаю куда вводить эту команду. по SSH? перед ней что писать?

**Comment by Waujito** [comment]
Ну настройки анблока. Писать в гуях (нужна rc версия)

**Comment by RoVRy** [comment]
Насколько было бы всем легче, если унифицировать настройки и их описание с GoodbyeDPI

**Comment by ALexeyAL1** [comment]
Дело было не в бабине...
Анблок работает из коробки, это я своими руками кучерявыми неправильно настроил Распбери свою. Не трогал бридж, а рабо было его распустить на отдельные устройства. Вчера с 5 попытки наконец получилось правильно настроить роутер, а Анблок заработал сразу и без проблем. Большое спасибо за программу. Тикет можно закрывать. Но слова [RoVRy](https://github.com/RoVRy) очень интересны. В Друпале 8 версии и выше модули делающие похожие вещи объединяются в инициативы, которые унифицируют некоторые вещи. Было бы неплохо сделать нечто похожее и в этом благородном деле. Чтобы стратегии можно было искать в одной или вообще в отдельной программе, а применять в любой. Это бы упростило обход и сделало его доступным для большего числа людей

**Comment by Waujito** [comment]
Согласен, подумаю над алиасами
