### ISSUE TITLE
Перестала работать md5sum

### ISSUE THREAD

**Issue by aterebenkov** [Waujito/youtubeUnblock#147]
Самая эффективная стратегия сегодня вечером отвалилась. Обрабатывал с ней где-то 6 гигов ютюбовского трафика , добавил --frag-middle-sni=1 --synfake=1 -завелось, но там задержка около 20 секунд до старта видео. Мб есть у кого варианты комбинаций побыстрее?)

**Comment by itsphobia** [comment]
причем, какие-то видео запускаются мгновенно, а какие-то с задержкой.

**Comment by Waujito** [comment]
Обсуждение было в #148. Закрываю как дубликат.
Duplicate of #148
