### ISSUE TITLE
Удаление пакета ломает Luci

### ISSUE THREAD

**Issue by AlexMaximov73** [Waujito/youtubeUnblock#149]
v1.0.0-rc1 
Приходиться переставлять opkg install luci-lua-runtime

**Comment by Izvekov** [comment]
При удалении пакета ,  вот такое видим https://e.radikal.host/2024/10/11/UDALENIEOSIBKA.md.jpg
Сброс восстанавливает вход в систему, но DHCP так и не удалось запустить, перешил полностью прошивку на исходную.

**Comment by Waujito** [comment]
Очень странное поведение, я такого не видел, посмотрю еще

**Comment by R0iZ** [comment]
> При удалении пакета , вот такое видим https://e.radikal.host/2024/10/11/UDALENIEOSIBKA.md.jpg Сброс восстанавливает вход в систему, но DHCP так и не удалось запустить, перешил полностью прошивку на исходную.

Да, тоже такое сегодня словил

**Comment by Izvekov** [comment]
галочку поставили удалять ненужные зависимости (или что-то такое, уже не помню точно название)? Когда галку убираем удаляет нормально. Это только в последней версии такое поведения, раньше удалял и ставил многократно без проблем, последний пакет что-то тянет и ставит и при удалении удаляет, почему лишнее - вопрос.

**Comment by Waujito** [comment]
Я разделил обычный бинарь youtubeUnblock на uci и luci-app-youtubeUnblock. luci-app-youtubeUnblock теперь использует самый обычный мэйкфайл luci.mk, как в официальных релизах. Проблем быть не должно. Скачать оба пакета можно отсюда:
https://github.com/Waujito/youtubeUnblock/actions/runs/11298074283

**Comment by Waujito** [comment]
Полагаю, проблема ушла и можно закрывать?

**Comment by Steve-61** [comment]
Подскажите, как правильно удалить модуль. Нигде в мануале этого не нашел.

**Comment by R0iZ** [comment]
> Подскажите, как правильно удалить модуль. Нигде в мануале этого не нашел.

через web интерфейс, только галочку "удалять зависимости" сними. Желательно ещё удалить файл /etc/config/youtubeUnblock

**Comment by Waujito** [comment]
> Желательно ещё удалить файл /etc/config/youtubeUnblock

Не надо его удалять, есть кнопка ресет конфиг в интерфейсе

**Comment by R0iZ** [comment]
> > Желательно ещё удалить файл /etc/config/youtubeUnblock
> 
> Не надо его удалять, есть кнопка ресет конфиг в интерфейсе

на билде, который я ставил, не было ещё. Сегодня. поставил свежий, теперь кнопочка есть)))

**Comment by Hynix373** [comment]
> > Желательно ещё удалить файл /etc/config/youtubeUnblock
> 
> Не надо его удалять, есть кнопка ресет конфиг в интерфейсе

Да у меня тоже была проблема я удалил пакет через люси и wifi модули умерли 
Пришлось прошивать с нуля

**Comment by AlexMaximov73** [comment]
Сейчас столкнулся  с тем что, удаление пакета luci-app-youtubeUnblock-1.0.0-37a517e.ipk ломает всю Люсю )

**Comment by AlexMaximov73** [comment]
sercomm s1010 (mt7620) для родителей )
Установка youtubeUnblock-1.0.0-37a517e-mipsel_24kc-openwrt-23.05.ipk
Далее luci-app-youtubeUnblock-1.0.0-37a517e.ipk
Удаляю luci-app-youtubeUnblock-1.0.0-37a517e.ipk
Получаю картинку из 2-го поста ))
Больше помочь не чем ))

**Comment by R0iZ** [comment]
> sercomm s1010 (mt7620) для родителей ) Установка youtubeUnblock-1.0.0-37a517e-mipsel_24kc-openwrt-23.05.ipk Далее luci-app-youtubeUnblock-1.0.0-37a517e.ipk Удаляю luci-app-youtubeUnblock-1.0.0-37a517e.ipk Получаю картинку из 2-го поста )) Больше помочь не чем ))

Когда удаляешь luci-app-youtubeUnblock надо снять галку "Удалять зависимости" не помню как называется точно

**Comment by AlexMaximov73** [comment]
Сегодня ставил на свежий 25.05.05 МТС WG430223
При установке Люси словил ошибку

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-compat for luci-app-youtubeUnblock
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-youtubeUnblock found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-youtubeUnblock.

Видимо luci-compat уже нету в сборке
Может это чем то поможет ))

**Comment by Waujito** [comment]
@AlexMaximov73 Luci compat в сборке есть, а вот репозитории у вас не обновлены (update lists)

**Comment by Waujito** [comment]
luci перешёл на js, и я luci-compat теперь не является зависимостью, повториться не должно, закрываю https://github.com/Waujito/youtubeUnblock/actions/runs/12455144585
