### ISSUE TITLE
работает ли это с PBR?

### ISSUE THREAD

**Issue by Spp595** [Waujito/youtubeUnblock#15]
Будет ли это работать при уже настроенном pbr policy based routing на openwrt?

**Comment by zabbius** [comment]
Works for me on OpenWRT 23.05.3 with mwan3 balancer on two uplinks.

**Comment by Waujito** [comment]
Если я правильно понял, PBR использует метки пакетов. youtubeUnblock также их использует, чтобы помечать пакеты отправленные с rawsocket. Я рекомендую либо пропускать пакеты с меткой youtubeUnblock, либо, если метки поддерживают побитовые операции, можно включать только один бит. Тогда потребуется небольшое изменение в коде. Напишите, если это необходимо.

**Comment by ilshatms** [comment]
> UPD. Посмотрел в документации. У меток есть маски, поэтому это вполне реализуемо.

получается заведется без проблем поверх pbr без необходимости как-то настраивать зависимости? или наоборот требует тестов и при необходимости формировать запрос на изменение?

**Comment by Waujito** [comment]
> > UPD. Посмотрел в документации. У меток есть маски, поэтому это вполне реализуемо.
> 
> получается заведется без проблем поверх pbr без необходимости как-то настраивать зависимости? или наоборот требует тестов и при необходимости формировать запрос на изменение?

То есть я правильно понял, что pbr это штука, которая работает на метках (я не особо вчитывался в мануалы, просто предположил)? Если так, то конечно она будет требовать тестов и возможно изменений в таблицах при конфликте меток. Но сам факт того, что оно имеет маски облегчает задачу. К примеру, я могу заставить свою программу работать на метке (1 << 15) и ориентироваться только по 15-му биту. Да вообще лучше это всё-таки сделать. Метки вещь полезная и нельзя просто так их затирать.

**Comment by Waujito** [comment]
Да, это работает с PBR) #59

**Comment by Waujito** [comment]
> как понимаю настройка не требуется для работы?
> Или надо прописать что то?

На последних версиях всё должно быть нормально. Если происходит конфликт меток, поменяйте её на любую другую флагом —packet-mark

Метку желательно подбирать по степеням двойки
