### ISSUE TITLE
Не устанавливается v1.0.0-rc1

### ISSUE THREAD

**Issue by Izvekov** [Waujito/youtubeUnblock#150]
Скачиваю для своего маршрутизатора -
[youtubeUnblock-0.3.2-2d1b58b-mipsel_24kc-openwrt-23.05.ipk](https://github.com/Waujito/youtubeUnblock/releases/download/v1.0.0-rc1/youtubeUnblock-0.3.2-2d1b58b-mipsel_24kc-openwrt-23.05.ipk) - не устанавливается. В то время, как  [v0.3.2] https://github.com/Waujito/youtubeUnblock/releases/download/v0.3.2/youtubeUnblock-0.3.2-3d50c00-mipsel_24kc-openwrt-23.05.ipk устанавливается. Причина в ipk или я не то делаю? 
На версии 0.3.2 у меня не выполняется ключ --synfake=1, без которого видео не играет.

**Comment by Waujito** [comment]
update lists сделайте в luci

**Comment by Izvekov** [comment]
Спасибо. Это помогло, все установилось.
