### ISSUE TITLE
Некорректное поведение при обновлении прошивки OpenWrt

### ISSUE THREAD

**Issue by frungl** [Waujito/youtubeUnblock#151]
При обновлении прошивки с OpenWrt 23.05.4 на OpenWrt 23.05.5 пропал youtubeUnblock ([v1.0.0-rc1](https://github.com/Waujito/youtubeUnblock/releases/tag/v1.0.0-rc1) aka 	0.3.2-2d1b58b-ramips-1) из установленных пакетов. Установил заново, но программа упала с такими логами:
```
daemon.err youtubeUnblock[3438]: Thread 0 exited with status -1
daemon.info youtubeUnblock[3438]: Probably another instance of youtubeUnblock with the same queue number is running
daemon.info youtubeUnblock[3438]: mnl_cb_run: Operation not permitted
daemon.info youtubeUnblock[3438]: Queue 537 started
daemon.info youtubeUnblock[3438]: IPv6 is enabled
daemon.info youtubeUnblock[3438]: GSO is enabled
daemon.info youtubeUnblock[3438]: Past seq faking strategy will be used
daemon.info youtubeUnblock[3438]: Fragmentation Client Hello will be reversed
daemon.info youtubeUnblock[3438]: Fake SNI will be sent before each target client hello
daemon.info youtubeUnblock[3438]: Using TCP segmentation
daemon.info youtubeUnblock[3438]:
daemon.info youtubeUnblock[3438]: Bypasses deep packet inspection systems that relies on SNI
daemon.info youtubeUnblock[3438]: youtubeUnblock
```
Переустановка ничего не меняет. Если удалить, то в запущенных процессах и списке автозапусков youtubeUnblock не числится, то есть кажется, что экземпляр единственный. Видимо при обновлении прошивки программа завершается некорректно и не закрывает до конца использованные ресурсы. Да и сам вопрос исчезновения из списка пакетов интересный.

Прошивка: OpenWrt 23.05.04 -> OpenWrt 23.05.05
Архитектура: mipsel_24k
Версия youtubeUnblock: [v1.0.0-rc1](https://github.com/Waujito/youtubeUnblock/releases/tag/v1.0.0-rc1) aka 	0.3.2-2d1b58b-ramips-1

**Comment by frungl** [comment]
UPD: [Поменял](https://github.com/Waujito/youtubeUnblock/compare/main...frungl:youtubeUnblock:main) ручками номер очереди, но это не решило проблему.  Так что видимо проблема глубже

**Comment by frungl** [comment]
UPD2: Сделал полный сброс настроек роутера и установил программу на чистый роутер. Проблема не ушла, теперь думаю что проблема в прошивке, но issue на всякий оставлю

**Comment by Waujito** [comment]
Установите зависимости

**Comment by frungl** [comment]
Спасибо, помогло. Я уже успел забыть про то, что они существуют. Возможно стоит расширить сообщение (Probably another instance of youtubeUnblock with the same queue number is running) на этот случай
