### ISSUE TITLE
не работает яндекс станция при просмотре ютуба

### ISSUE THREAD

**Issue by 60letamozgovnet** [Waujito/youtubeUnblock#153]
настроил колонку, включил ютуб, перестала работать колонка

**Comment by Waujito** [comment]
а это точно связано?

**Comment by 60letamozgovnet** [comment]
подключилось с божьей помощью с 4 раза, ничего не меняя

**Comment by Waujito** [comment]
Вряд ли вообще это было связано с анблоком
