### ISSUE TITLE
Не стартует после обновления с 1.0.0rc1 на 1.0.0rc2

### ISSUE THREAD

**Issue by JustZhenya** [Waujito/youtubeUnblock#155]
В логах пишет `Sun Oct 13 21:58:03 2024 daemon.err youtubeUnblock[28761]: Unable to parse args: Invalid argument`
Сброс настроек через кнопку "Reset settings to defaults" на странице youtubeUnblock luci не помогает.
Обновлял так: вначале поставил новый youtubeUnlock.ipk поверх старого (при этом удалился luci-compat), затем поставил luci-app-youtubeUnblock.ipk (luci-compat вернулся).

**Comment by Waujito** [comment]
Спасибо за оперативное тестирование! Действительно, случайно убрал синфэйк)
