### ISSUE TITLE
Не работает reset

### ISSUE THREAD

**Issue by PadowYT2** [Waujito/youtubeUnblock#158]
Раньше стояли флаги из #148 (UPD 3), затем прочитал что надо обновиться и ресетнуть настройки. Обновился, нажимаю на кнопку, страница перезагружается, но ничего не происходит

**Comment by Waujito** [comment]
Еще надо перезапустить анблок (кнопочка restart там же) и несколько раз обновить страницу

**Comment by PadowYT2** [comment]
> Еще надо перезапустить анблок (кнопочка restart там же) и несколько раз обновить страницу

Попробывал, не помогло. Также теперь я вообще не могу запустить, ничего не происходит при нажатии

**Comment by cHameleonRu** [comment]
> > Еще надо перезапустить анблок (кнопочка restart там же) и несколько раз обновить страницу
> 
> Попробывал, не помогло. Также теперь я вообще не могу запустить, ничего не происходит при нажатии

Посмотрите, что в логах пишется.

**Comment by PadowYT2** [comment]
> > > Еще надо перезапустить анблок (кнопочка restart там же) и несколько раз обновить страницу
> > 
> > Попробывал, не помогло. Также теперь я вообще не могу запустить, ничего не происходит при нажатии
> 
> Посмотрите, что в логах пишется.

Абсолютно ничего нету в OpenWrt логах, и в youtubeUnblock последнее
```
Mon Oct 14 16:07:34 2024 daemon.info youtubeUnblock[13217]: Target SNI detected: gs-loc.apple.com```

**Comment by PadowYT2** [comment]
Ладно, я тупой. Я подумал что надо установить только luci, без самого executable
