### ISSUE TITLE
можете обьединить решение для discord также?

### ISSUE THREAD

**Issue by jagga99** [Waujito/youtubeUnblock#159]
можете обьединить решение для discord также?

**Comment by nihochuha** [comment]
Добавьте в список доменов
discord.com
discordapp.com
discord.gg
discordapp.net

**Comment by jagga99** [comment]
это предложение ? или гайд? не уловил

**Comment by Waujito** [comment]
Я НЕ буду добавлять обход дискорда по дефлоту. Вы можете сделать это самостоятельно, флагами. Фэйкинг UDP сделать стоит, обсуждение в #144
