### ISSUE TITLE
Захлебывается при определенных настройках

### ISSUE THREAD

**Issue by vitidev** [Waujito/youtubeUnblock#166]
Как и обещал, завожу отдельный issue

На дефолтных настройках все отлично держалось несколько дней.
Вернул проблемные

    config youtubeUnblock 'youtubeUnblock'
    	option frag 'tcp'
    	option frag_sni_reverse '1'
    	option frag_middle_sni '1'
    	option frag_sni_pos '2'
    	option fk_winsize '0'
    	option seg2delay '50'
    	option packet_mark '32768'
    	option fake_sni '1'
    	option faking_strategy 'pastseq'
    	option fake_sni_seq_len '10'
    	option frag_sni_faked '1'

Захлебывается где-то через 10-12 часов у меня.  

отличия от дефолтного профиля

    option frag_sni_pos '2'
    option seg2delay '50'
    option fake_sni_seq_len '10'
    option frag_sni_faked '1'

и в дефолтном есть  option fake_sni_type 'default', но это же дефолтное значение, поэтому игнорирую

Перестают открываться сайты и лог не обновляется. При этом у меня в последний раз при отвале воспроизводилось видео в ютубе и он отвалился частично -  можно было переходить по страницам и подгружались комменты даже (но не открывалось само видео), но не посторонний сайт (даже если он есть в списке youtubeUnblock). Хотя может ютуб просто держал http2 коннект и поэтому нового коннекта не делал.

перебираю варианты (сбрасываю на дефолтные значения) и жду. Первым было такое

    option frag_sni_pos '2'
    option seg2delay '0'  <---
    option fake_sni_seq_len '10'
    option frag_sni_faked '1'

Захлебнулось все через час. 
Сейчас такое

    option frag_sni_pos '2'
    option seg2delay '50'
    option fake_sni_seq_len '1' <---
    option frag_sni_faked '1'

По времени должно было повиснуть еще вчера (хотя это не слишком тонкая наука, ведь я не знаю как нужно нагружать сеть), но работает до сих пор и потому решил отписать.

забыл конфиг
openwrt 23.05.5  ramips 7621
youtubeUnblock | 1.0.0-37a517e-ramips-1 (v1.0.0-rc3)

**Comment by Waujito** [comment]
Я не могу отследить вашу проблему. Из гипотез - возможно что-то со стратегией выделения памяти. Но я сам в это слабо верю. В любом случае, я сделал другую стратегию. Попробуйте билды отсюда: https://github.com/Waujito/youtubeUnblock/actions/runs/11526123070

**Comment by vitidev** [comment]
@Waujito 

перевел настройки на сбойные чтобы все было честно и стал ждать зависания прошлого билда. Завис неожиданно быстро - через 20 минут

Обновил до версии 1.0.0-999eec7-ramips-1 и стал ждать. Прошло 6 часов и 
оно само упало с сообщением в логе

     Sat Oct 26 17:19:16 2024 kern.info kernel: [1063202.095890] do_page_fault():
     sending SIGSEGV to youtubeUnblock for invalid write access to 00000000

**Comment by Waujito** [comment]
@vitidev 
дайте точные настройки анблока. Если запустить через команду `/etc/init.d/youtubeUnblock restart`, скрипт должен вывести аргументы, которые он спарсил. Также посмотрите в `logread -l 200`, нет ли там более детального описания SEGFAULT

**Comment by Waujito** [comment]
> Обновил до версии 1.0.0-999eec7-ramips-1

На всякий случай уточню. У вас же youtubeUnblock-1.0.0-999eec7-mipsel_24kc-openwrt-23.05 стоит?

**Comment by vitidev** [comment]
@Waujito 

да. вот название файла

     youtubeUnblock-1.0.0-999eec7-mipsel_24kc-openwrt-23.05.ipk

**Comment by Waujito** [comment]
Кажется, мне удалось найти проблему. Попробуйте эту сборку https://github.com/Waujito/youtubeUnblock/actions/runs/11535824988

В чём она заключалась можете посмотреть в описании к коммиту :)
Спасибо!

**Comment by vitidev** [comment]
@Waujito 

А что вот такое появилось, вроде раньше не было.

      Mon Oct 28 15:16:26 2024 daemon.err youtubeUnblock[2366]: send delayed raw packet: Resource temporarily unavailable
      Mon Oct 28 15:16:26 2024 daemon.err youtubeUnblock[2366]: send delayed raw packet: Resource temporarily unavailable
      Mon Oct 28 15:16:26 2024 daemon.err youtubeUnblock[2366]: send delayed raw packet: Resource temporarily unavailable
      Mon Oct 28 15:16:26 2024 daemon.err youtubeUnblock[2366]: send delayed raw packet: Resource temporarily unavailable
      Mon Oct 28 15:16:26 2024 daemon.err youtubeUnblock[2366]: send delayed raw packet: Resource temporarily unavailable
      Mon Oct 28 15:16:26 2024 daemon.err youtubeUnblock[2366]: send delayed raw packet: Resource temporarily unavailable
      Mon Oct 28 15:16:26 2024 daemon.err youtubeUnblock[2366]: send delayed raw packet: Resource temporarily unavailable

**Comment by Waujito** [comment]
Если бы вы были на старом анблоке, у вас бы всё зависло. Переполнилась очередь фэйк пакетами и заблокировался сокет. В целом чтобы избежать этого можно добавить правило фаервола, которое примет маркированный пакет для того, как он попадёт в основную очередь. Я думаю, мне стоит чуть поправить в обновлении правила фаервола, чтобы эти пакеты вообще в очередь не шли
