### ISSUE TITLE
luci-app не устанавливается, ссылаясь на неподходящую архитектуру

### ISSUE THREAD

**Issue by walkedbyitself** [Waujito/youtubeUnblock#168]
Прежде всего, спасибо больше за это филигранное решение!

Сабж: у меня не хочет ставиться, ссылаясь на неподходящую архитектуру. Разумеется, update lists выполнен. Скомпилированного luci-lua-runtime под мою платформу не могу найти, если проблема в этом депенденсе.

```
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-youtubeUnblock
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-youtubeUnblock found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-youtubeUnblock.
 ```
 
Извлечение пакета luci-app из установщика позволило сократить .ipk в случае моего mipsel24kc24kf с 22.5кб до 21.1кб, но, по-видимому, аппку тоже нужно собирать со своим окружением. И, если эта проблема сохраняется не только у меня, то стоит ли игра свеч? Экономия 1.4кб ипкшки для товарищей с флешкой 4/32, от поддержки которых owrt отказался ещё года три назад, или же спортивный интерес - не знаю. Но знаю, что подавляющее большинство не будет пересобирать апп под себя, а те, кто будут - смогут собрать себе из исходников и без luci-app'а.

Если вдруг я где-то упустил нюанс, то, пожалуйста, не кидайтесь камнями сразу. Я сам себя ими закидаю, если не увидел описанное решение :)

Ещё раз спасибо!

![image](https://github.com/user-attachments/assets/fbac3b1c-576d-44b3-b46a-d9bffd4c3185)

**Comment by Waujito** [comment]
update lists.
For LuCI aka GUI aka web-interface of router you should install luci-app-youtubeUnblock package like you did it with the normal youtubeUnblock package. Note, that lists of official opkg feeds should be loaded (Do it with Update lists option).

**Comment by Waujito** [comment]
А, недочитал, что update lists сделали)

**Comment by walkedbyitself** [comment]
> Ну по идее тут только в update lists может быть проблема: cannot find dependency luci-lua-runtime for luci-app-youtubeUnblock
> 
> Архитектура роли не играет

Вот для меня тоже странно, что ссылается на неверную архитектуру, хотя какая архитектура у странички с парой булинов и парой стрингов, которые просто дописываются запуск сервиса...

И, что самое главное - встроенная аппка из rc1 работала как часы, и не требовала при установке никаких доп. пакетов типа lua-runtime, которые я нигде не могу найти на свой мипсель24кс (mt7621), на owrt есть только x86-64 и на кортекс а72 из того, что я смог найти (https://pkgs.org/download/luci-lua-runtime).

Если вдруг проблема в доступных фидах, то, можете кинуть в меня им? Сравнил с оригинальным дистром owrt 22.3.05, там те же сурцы.
```
src/gz openwrt_core https://downloads.openwrt.org/releases/22.03.5/targets/ramips/mt7621/packages                       src/gz openwrt_base https://downloads.openwrt.org/releases/22.03.5/packages/mipsel_24kc/base                            src/gz openwrt_luci https://downloads.openwrt.org/releases/22.03.5/packages/mipsel_24kc/luci                            src/gz openwrt_packages https://downloads.openwrt.org/releases/22.03.5/packages/mipsel_24kc/packages                    src/gz openwrt_routing https://downloads.openwrt.org/releases/22.03.5/packages/mipsel_24kc/routing                      src/gz openwrt_telephony https://downloads.openwrt.org/releases/22.03.5/packages/mipsel_24kc/telephony 
```
![image](https://github.com/user-attachments/assets/871dbe94-5478-4bc7-b397-0aabbc42c69f)

**Comment by Waujito** [comment]
Смотрите. Вам необходимо установить пакеты luci-base и luci-compat на роутер. Тогда должен будет встать и luci-app-youtubeUnblock

**Comment by walkedbyitself** [comment]
> Смотрите. Вам необходимо установить пакеты luci-base и luci-compat на роутер. Тогда должен будет встать и luci-app-youtubeUnblock

Без luci-base я не смог бы прилепить скриншот из первого сообщения топика. Разумеется, у меня и то и другое стоит, без них и самой люси не было, и работы приложения в версии 1.0.0рк1 :)

```
root@ac2100:~# opkg install luci-base
Package luci-base (git-24.208.65546-18f3914) installed in root is up to date.
root@ac2100:~# opkg install luci-compat
Package luci-compat (git-23.093.42303-ef4cd04) installed in root is up to date.
```
Все пакеты говорят, что они up to date. 
![image](https://github.com/user-attachments/assets/9fd695c9-d8fc-4cd2-b77b-e321a13f12d1)

**Comment by walkedbyitself** [comment]
1.0.0rc3 (1.0.0-37a517e-ramips-1):
![image](https://github.com/user-attachments/assets/d3ec184c-a025-430a-8e79-20d9b1c062a4)

1.0.0rc1 (0.3.2-2d1b58b-ramips-1):
![image](https://github.com/user-attachments/assets/03f386d1-ff32-457a-8720-52fb9ef9207c)
![image](https://github.com/user-attachments/assets/98154b1e-5b84-40da-aab4-7e884bd3615f)

То ли лыжи не едут, то ли я...
Но, могу заверить - без установленного интерфейса я не стал бы спрашивать, почему его фича не хочет заводиться :D

**Comment by Waujito** [comment]
Так стоп у вас 22 опенврт?

**Comment by walkedbyitself** [comment]
> Смотрите. Вам необходимо установить пакеты luci-base и luci-compat на роутер. Тогда должен будет встать и luci-app-youtubeUnblock

Я совершенно случайно упустил из виду тот факт, что оно собирается под 23.05. Но для меня всё ещё очень странно, что все предыдущие пребилды 23.05 заводились, а отдельно не хочет. И, сравнивая с девственным образом, скаченным с https://mirror-03.infra.openwrt.org/releases/23.05.5/targets/ramips/mt7621/, такого явления как "luci-lua-runtime" также не существует.

opkg все варианты форс-установки игнорирует, --nodeps и иже с ним приводят к одному и тому же выхлопу.

Вот rootfs прошивки:
![image](https://github.com/user-attachments/assets/ac26d21f-d142-4159-9dea-b6aa2799c084)

**Comment by walkedbyitself** [comment]
> Так стоп у вас 22 опенврт?

:C верно, сначала не придал этому значения, ведь все предыдущие версии работали абсолютно без нареканий.
Извиняюсь, что лишний раз запутал. Если по понятным причинам нет желания тянуть легаси, я пойму, и ишуй закрыть.
Но, если не затруднит, можете пнуть в нужном направлении, что там такого поменялось, что аппка перестала быть совместимой?

**Comment by Waujito** [comment]
Может быть что-то особенное в luci.mk сделали, чтобы ужесточить эту проверку. В целом, можете попробовать отключить флагами opkg их (правда, может вся люся слететь, если opkg прав, и там нет совместимости)

**Comment by walkedbyitself** [comment]
> Может быть что-то особенное в luci.mk сделали, чтобы ужесточить эту проверку. В целом, можете попробовать отключить флагами opkg их (правда, может вся люся слететь, если opkg прав, и там нет совместимости)

Понял, поковыряю на выходных, только нормальный бэкап сделаю. Отпишусь в итоге, как решил, и закрою ишуй.
Ещё раз спасибо за обратную связь!

**Comment by MayanKoyote** [comment]
На сколько я помню, luci-lua-runtime появился когда LuCI переписали с Lua на ucode с целью выкинуть Lua на мороз.
https://forum.openwrt.org/t/luci-rewrite-in-ucode-testers-wanted/137250

И обратная совместимость с существующими приложениями LuCI на базе Lua должна была уже достигаться только путем установки luci-lua-runtime.
https://github.com/openwrt/luci/pull/5976

Произошло это с релизом 23.05.

22.03 поставлялся с обоими (Lua и ucode) и никакого пакета luci-lua-runtime там быть и не может, так как он не нужен.
https://forum.openwrt.org/t/issue-building-with-openwrt-22-03-sdk/147779

Для предыдущих версий (как минимум 18.06, старее не проверял, ни к чему это мне было) luci-lua-runtime как отдельного пакета тоже нет, так как он тоже не нужен.

Для них как вариант можно испльзовать заглушку-пустышку из https://github.com/xiaorouji/openwrt-passwall/issues/2786
или устанавливать используя --force-depends для игнорирования зависимости luci-lua-runtime или просто копировать файлы из распакованного пакета  luci-app-youtubeUnblock. Проблем вроде пока не замечено (18.06). И это и хорошо и радует.

Update: Репозиторий канул, но остался в [«Архиве Интернета»](https://web.archive.org/web/20251206010921/https://github.com/xiaorouji/openwrt-passwall/issues/2786).
И на всякий: [luci-lua-runtime_all_fake.zip](https://github.com/user-attachments/files/26301994/luci-lua-runtime_all_fake.zip)

Пакет luci-compat всё же будет нужен, но он есть в официальных репозиториях для всех "акуальных" (начиная как минимум с 18.06, старее не проверял, ни к чему это мне было) - как заглушка-пустышка для 18.06 и как "настоящий" начиная с 19.07.

Пакет luci-base - понятное дело тоже, с ним тоже проблем нет.

**Comment by walkedbyitself** [comment]
> Для них как вариант можно испльзовать заглушку-пустышку из [xiaorouji/openwrt-passwall#2786](https://github.com/xiaorouji/openwrt-passwall/issues/2786) или устанавливать используя --force-depends для игнорирования зависимости luci-lua-runtime или просто копировать файлы из распакованного пакета luci-app-youtubeUnblock. Проблем вроде пока не замечено (18.06). И это и хорошо и радует.

Как же меня забавляет, что [пустышка](https://github.com/user-attachments/files/17605389/luci-lua-runtime_all_fake.zip) действительно помогла решить проблему, буквально в один клик. Без неё --force-depends не срабатывал, всё равно вредничал. @MayanKoyote спасибо!
Некоторые пакеты, которые я использую, нужно долго и муторно адаптировать для 23 версии. Откатился обратно, и в качестве временного быстрофикса я ставил рк1, там делал настройки (чтоб вручную не сидеть и не бояться, что где-то синтаксис нарушу), и потом обновлялся до третьего рк.

Разумеется, такое заранее очень сложно предугадать. @Waujito, стоит ли указать в факе, что если есть желание попытать счастье с запуском на старом оврт, можно попробовать этот фэйк? :)

![image](https://github.com/user-attachments/assets/9a47aaed-b28a-4cd9-85cb-fe7a60a7601b)

**Comment by Waujito** [comment]
Да, если всё заработало, напишу об этом в readme. 

@MayanKoyote спасибо!

**Comment by SDjin** [comment]
А как на 19.07 установить? И надо ли, или можно из консоли поиграться параметрами запуска?
