### ISSUE TITLE
после установки 1.0.0-37a517e-mipsel_24kc-openwrt-23.05.ipk сломался интернет

### ISSUE THREAD

**Issue by nitro3188** [Waujito/youtubeUnblock#175]
Добрый вечер. Установил пакет 1.0.0-37a517e-mipsel_24kc-openwrt-23.05.ipk - пропал интернет. Перезагрузил, обновил пакеты, удалил youtubeUnblock. Перезагрузил, обновил пакеты, поставил заново (с ошибками) 
```
''Sun Oct 27 18:57:03 2024 daemon.err uhttpd[1726]: [!] Automatically including '/usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft'
Sun Oct 27 18:57:04 2024 daemon.err uhttpd[1726]: In file included from /proc/self/fd/0:230:1-68:
Sun Oct 27 18:57:04 2024 daemon.err uhttpd[1726]: /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft:5:106-110: Error: Could not process rule: No such file or directory
Sun Oct 27 18:57:04 2024 daemon.err uhttpd[1726]: add rule inet fw4 youtubeUnblock meta l4proto { tcp, udp } th dport 443 ct original packets < 20 counter queue num 537 bypass
Sun Oct 27 18:57:04 2024 daemon.err uhttpd[1726]:  
```
пропал интернет и в логах вот такое:
![2024-10-27_191842](https://github.com/user-attachments/assets/f95cef0e-9793-462c-855a-d1f52d25e2a3)
![2024-10-27_192229](https://github.com/user-attachments/assets/b8c2ee51-3c41-443c-8537-0deab4d82e34)
![2024-10-27_192247](https://github.com/user-attachments/assets/8208f7fa-36d8-474b-857e-dc2862d4a335)
пишет что файла нет - на скрине видно он есть

**Comment by Waujito** [comment]
Зависимости стоят?

**Comment by nitro3188** [comment]
> Зависимости стоят?

я шляпа - установил зависимости всё заработало! извини за мою глупость!
