### ISSUE TITLE
Breaks some other sites 

### ISSUE THREAD

**Issue by nookeist** [Waujito/youtubeUnblock#176]
### Bug description

Ломает картинки на сайтах. Заметил только пока на ozon
из терминала хрома
```
Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Open+Sans&display=swap' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' cdn1.ozone.ru cdn2.ozone.ru st.ozone.ru st-1.ozone.ru st-2.ozone.ru st-3.ozone.ru mmedia.ozone.ru *.ozonstatic.cn". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
```
Failed to load resource: net::ERR_CONNECTION_RESET

помогает только остановка службы youtubeUnblock

### Device architecture

DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.4'
DISTRIB_REVISION='r24012-d8dd03c46f'
DISTRIB_TARGET='mediatek/filogic'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='OpenWrt 23.05.4 r24012-d8dd03c46f'
DISTRIB_TAINTS=''

**Comment by Waujito** [comment]
Конфиги?

**Comment by nookeist** [comment]
root@OpenWrt:~# cat /etc/config/youtubeUnblock
cat: can't open '/etc/config/youtubeUnblock': No such file or directory

root@OpenWrt:~# cat /etc/init.d/youtubeUnblock 
#!/bin/sh /etc/rc.common
USE_PROCD=1

START=50
STOP=50

# Openwrt procd script: https://openwrt.org/docs/guide-developer/procd-init-script-example
# The program should be put into /usr/bin/
# This file should be put into /etc/init.d/

start_service() {
        procd_open_instance
        procd_set_param command /usr/bin/youtubeUnblock

        procd_set_param nice -20

        procd_set_param stdout 1
        procd_set_param stderr 1

        procd_close_instance
}

У меня по дефолту всё, настройки для Nftables и закинул файлик, всё.

**Comment by Waujito** [comment]
так это старая версия. Ставьте 1.0.0-rc3

**Comment by nookeist** [comment]
Спс.. теперь всё ок

**Comment by nookeist** [comment]
Спс.. теперь всё ок
