### ISSUE TITLE
Entware run package

### ISSUE THREAD

**Issue by r0otx** [Waujito/youtubeUnblock#180]
### Bug description

Hello, I can't understand work package or not, but if I run youtubeUnblock, youtube don't load video. I make next steps: 

1. Go to /opt/etc/init.d/S91youtubeUnblock and edit file. 
2. Add flags in ARGS="--fake-sni-type=custom --fake-custom-payload=00 --fake-sni-seq-len=10 --frag-sni-faked=1 --frag-sni-reverse=0 --frag-sni-pos=1 --frag-middle-sni=0 --seg2delay=100" 
3. After I run youtubeUnblock &
4. In console show this text:

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/f8026236-7ade-42f6-8810-92ba1021372a">

5. Youtube in TV don't work :( What I make wrong?

**Comment by Waujito** [comment]
Ask in discussion and proviced information asked in issue which you just skipped.
