### ISSUE TITLE
Как установить оболочку для Luci?

### ISSUE THREAD

**Issue by Mihrutkin** [Waujito/youtubeUnblock#183]
Здравствуйте, установил пакет.
Но в  luci не появилось ничего
![Снимок экрана 2024-11-10 001523](https://github.com/user-attachments/assets/1d738600-dcb6-479f-b112-dcdff68ff577)

**Comment by Waujito** [comment]
Всё таки рекомендую почитать ридми

**Comment by Alexgolshtein** [comment]
For LuCI aka GUI aka web-interface of router you should install luci-app-youtubeUnblock package like you did it with the normal youtubeUnblock package. Note, that lists of official opkg feeds should be loaded (Do it with Update lists option).

If you got  * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-youtubeUnblock error, you are using old openwrt. Install [this dummy package](https://github.com/xiaorouji/openwrt-passwall/files/12605732/luci-lua-runtime_all_fake.zip). https://github.com/Waujito/youtubeUnblock/issues/168#issuecomment-2449227547 for more details.

LuCI configuration lives in Services->youtubeUnblock section. It is self descriptive, with description for each flag. Note, that after you push Save & Apply button, the configuration is applied automatically and the service is restarted.
