### ISSUE TITLE
CR: improve ‘Service Satus’ info in the luci-app-youtubeUnblock OpenWrt pakage

### ISSUE THREAD

**Issue by Ser9ei** [Waujito/youtubeUnblock#189]
Запрос на улучшение пользователького интерфейса сервиса - раздел ‘Service status’ в luci пакете модуля youtubeUnblock

Прошу рассмотреть возможность:
1. Добавить авто обновление название кнопок в ‘Service status‘ после нажатия на них
Сейчас после нажатия на кнопки - start/stop/enable/disable их название не меняется (start <-> stop, enable <-> disable), необходимо обновлять полностью страницу для youtubeUnblock. 

2. Добавить кнопку ‘Refresh’ для актуализации списка сообщений из лога 
Сейчас приходится обновлять всю страницу, целиком.

3. В раздел ‘Service Status’ добавить возможность проверить работу модуля.
Сервис может подняться, но по факту не улучшить работу YT.
Предлагаю добавить кнопку и вывод информации команды:
> curl -4ko /dev/null --connect-to ::speedtest.selectel.ru https://test.googlevideo.com/10MB

или любой ее аналог.

4. Разделить интерфейс страницы модуля в luci Закладками (Tabs)
Две закладки - ‘Service Status’ и ‘Settings’

заранее спасибо

**Comment by Waujito** [comment]
Пункты 1 и 2 будут в #205, третий не получится, потому что тащить curl и подобные вещи с TLS достаточно затратно по памяти роутера
