### ISSUE TITLE
postinst скрипт создает файл /1

### ISSUE THREAD

**Issue by romanovj** [Waujito/youtubeUnblock#192]
https://github.com/Waujito/youtubeUnblock/blob/2154e2699efe81fae8646666d88ce82c454f14ba/youtubeUnblock/Makefile#L59

**Comment by Waujito** [comment]
Упс :)

**Comment by Waujito** [comment]
Спасибо, исправил, ожидайте workflow https://github.com/Waujito/youtubeUnblock/actions/runs/12071446980
