### ISSUE TITLE
[bug]: проблема со сборкой программы

### ISSUE THREAD

**Issue by Fi44er** [Waujito/youtubeUnblock#22]
Здравствуй. У меня возникает проблема при выполнении make файла:
![Снимок экрана от 2024-08-03 01-08-22](https://github.com/user-attachments/assets/8d4724c5-5f09-4890-a4f8-5bf39d6b6f67)
Так же создается пустая папка "Рабочий" в домашней директории:
![Снимок экрана от 2024-08-03 01-23-33](https://github.com/user-attachments/assets/9730a7e9-e5ae-494f-8c06-e9087dfbad0d)
И папка стол в корне проекта:
![Снимок экрана от 2024-08-03 01-24-17](https://github.com/user-attachments/assets/cd5c09e6-879c-40f3-85bc-390d6b7e9b1e)

Помогите решить проблему, пожалуйста.

**Comment by Waujito** [comment]
Попробуй без кириллицы и пробелов. GCC/Make их не любит.

**Comment by Fi44er** [comment]
Спасибо тебе большое, все работает
