### ISSUE TITLE
Правило iptables не добавляется

### ISSUE THREAD

**Issue by VedyNN** [Waujito/youtubeUnblock#23]
Сборка прошла без ошибок, но с warningamи
Установка тоже без ошибок.
**При запуске из консоли вывод:**
```
Using TCP segmentation
Fake SNI will be sent before each googlevideo request
GSO is enabled
```
При попытке добавить правило iptables, команда выполняется без вывода ошибок в тоже время правило не добавляется.

**Comment by Waujito** [comment]
Что можно сказать. Проверяйте через `iptables -t mangle -nvL — line-numbers`. Можно попробовать ручками отследить пакет `iptables -t raw -A OUTPUT -p tcp — dport 443 -j TRACE`

**Comment by Lintech-1** [comment]
может вам это поможет?
https://losst.pro/kak-sohranit-pravila-iptables

**Comment by haageduard** [comment]
Возможно мешает mwan3

**Comment by haageduard** [comment]
Кстати, у меня тоже не всегда срабатывает правило, но я пытаюсь настроить это легковесное решение на роутере с OpenWRT и выяснилось следующее:

Цитата из проекта Zapret:
Если ваше устройство поддерживает аппаратное ускорение (flow offloading, hardware nat, hardware acceleration), то iptables могут не работать.
При включенном offloading пакет не проходит по обычному пути netfilter.
Необходимо или его отключить, или выборочно им управлять.

**Comment by Waujito** [comment]
> Кстати, у меня тоже не всегда срабатывает правило, но я пытаюсь настроить это легковесное решение на роутере с OpenWRT и выяснилось следующее:
> 
> Цитата из проекта Zapret: Если ваше устройство поддерживает аппаратное ускорение (flow offloading, hardware nat, hardware acceleration), то iptables могут не работать. При включенном offloading пакет не проходит по обычному пути netfilter. Необходимо или его отключить, или выборочно им управлять.

youtubeUnblock, zapret и вообще любая вещь, которая работает в User space будет напрочь убивать любое аппаратное ускорение. Собственно, это и понятно почему. Мы вырываем пакет, пока он идёт по цепочкам нетфильтра и отправляем в User-space, в User-space обрабатываем и говорим что дальше делать. И этот процесс максимально долгий и не оптимальный: на один пакет имеем минимум три контекст свича. По-хорошему, надо идти в ядро (#9) ну или ограничивать количество пакетов, идущих в юзер-спейс с одного подключения (в Readme)

Сейчас погуглил про flow offloading: https://docs.kernel.org/networking/nf_flowtable.html

Тут есть способ отследить это для nftables. Я думаю, можно будет даже прикрутить сюда оптимизацию из Readme, чтобы полностью не отключать аппаратное ускорение, но там надо будет поиграться. С другой стороны, непонятно как это настраивать в iptables и вообще поддерживает ли он offloading.

**Comment by haageduard** [comment]
Пока просто отключил offloading. На моем роутере 4 ядра и с ограничением на кол-во подключений все хорошо.

**Comment by aegoroff** [comment]
А почему у меня при включенном NAT Offloading все работает?
![image](https://github.com/user-attachments/assets/e1bca4f6-b518-4aba-9650-f4d73655c2c4)

**Comment by Waujito** [comment]
Нет ответа, закрываю.
@haageduard Если интересен модуль, можете отслеживать его в #89 и #98
