### ISSUE TITLE
tcp4_frag: Invalid argument

### ISSUE THREAD

**Issue by Shamanky** [Waujito/youtubeUnblock#24]
При работе приложения в логах возникают сообщения вида..
Google video!
tcp4_frag: proto is tcp or request is fragmented: Success
tcp4_frag: Invalid argument
Google video!
tcp4_frag: proto is tcp or request is fragmented: Success
tcp4_frag: Invalid argument
Google video!

И  через браузеры  которые на базе движка Chrome видео не работает, через Firefox все ОК. Сборка последняя.

**Comment by Waujito** [comment]
Что если удалить эти строки из youtubeUnblock.c?
```
	if (hdr->protocol != IPPROTO_TCP || !(ntohs(hdr->frag_off) & IP_DF)) {
		perror("tcp4_frag: proto is tcp or request is fragmented");
		errno = EINVAL;
		return -1;
	}
```

**Comment by Shamanky** [comment]
Сообщения пропали, но видео так и не открывается. 
`tcp4_frag: proto is tcp or request is fragmented: Success`

Тут возможно  2 проблемы, я не вижу в логах  Google video!  при попытке открыть  видео.
Хотя если снять дамп в дампе есть текс вида XXXXXXXXXXX.googlevideo.com

**Comment by Waujito** [comment]
Скорее всего, дело в фрагментации по IP
Верните  предыдущие строчки  и добавьте `printf("%04x\n", ntohs(hdr->frag_off));` после perror.

**Comment by Waujito** [comment]
> Тут возможно 2 проблемы, я не вижу в логах Google video! при попытке открыть видео. Хотя если снять дамп в дампе есть текс вида XXXXXXXXXXX.googlevideo.com

Буду рад, если отправите дамп вайршарка

**Comment by Waujito** [comment]
Также хочу уточнить. Эта ошибка только в хроме возникает?

**Comment by Shamanky** [comment]
Я хотел уточнить. Я делаю это на роутере  в FORWARD там используется iptables и NAT.
тут в разделе IP ФРАГМЕНТАЦИЯ
[https://github.com/bol-van/zapret](url)
```
При использовании iptables и NAT, похоже, что нет способа прицепить обработчик очереди после NAT.
Пакет попадает в nfqws с source адресом внутренней сети, затем фрагментируется и уже не обрабатывается NAT.
Так и уходит во внешюю сеть с src ip 192.168.x.x. Следовательно, метод не срабатывает.  
```
Ваше решение тоже использует "Using TCP segmentation". Поэтому у меня в принципе  это решение работать не будет.
Есть возможность отключить "Using TCP segmentation"   оставить только "Fake SNI will be sent before each googlevideo request"?

**Comment by Waujito** [comment]
> Я хотел уточнить. Я делаю это на роутере в FORWARD там используется iptables и NAT. тут в разделе IP ФРАГМЕНТАЦИЯ [https://github.com/bol-van/zapret](url)
> 
> ```
> При использовании iptables и NAT, похоже, что нет способа прицепить обработчик очереди после NAT.
> Пакет попадает в nfqws с source адресом внутренней сети, затем фрагментируется и уже не обрабатывается NAT.
> Так и уходит во внешюю сеть с src ip 192.168.x.x. Следовательно, метод не срабатывает.  
> ```
> 
> Ваше решение тоже использует "Using TCP segmentation". Поэтому у меня в принципе это решение работать не будет. Есть возможность отключить "Using TCP segmentation" оставить только "Fake SNI will be sent before each googlevideo request"?

mangle стоит раньше nat и youtubeUnblock с nat никак не взаимодействует. Оно не срабатывает потому что приходит пакет,  фрагментированный по IP. По идее, такого вообще не должно происходить. Всё должно разбиваться на сегменты TCP, когда они прилетают в роутер. 

Если проблема случается только в хроме, решением будет отключение Kyber в chrome://flags.

**Comment by Waujito** [comment]
С другой стороны, возможность отключения фрагментации - интересная опция, которую действительно стоит добавить

**Comment by Waujito** [comment]
Я добавил отключение фрагментации и восстановил фрагментацию по ip, но сразу скажу, что у меня ничего из этого не работает. И советую всё-таки разобраться с хромом. Вывод этой ошибки поправил.

**Comment by Waujito** [comment]
Проблема окончательно решена в версии 0.3.0
