### ISSUE TITLE
Сборка статического бинарника

### ISSUE THREAD

**Issue by azhinu** [Waujito/youtubeUnblock#25]
При сборке получается такой бинарник:
```
build/youtubeUnblock: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d5119d9f2d492d1b83b27e23621378b641f9d2be, for GNU/Linux 3.2.0, not stripped
```
У меня не получается скомпилировать тулчейном для моего роутера (toolchain-mipsel_mips32r2_gcc-8.4.0_glibc-2.27), тулчейном от OpenWRT собирается, но зависит от musl. Как собрать полностью статический бинарник, чтобы запустить на роутере?

**Comment by Waujito** [comment]
```patch
diff --git a/Makefile b/Makefile
index 672d989..4448971 100644
--- a/Makefile
+++ b/Makefile
@@ -65,7 +65,7 @@ $(LIBNETFILTER_QUEUE): $(LIBNFNETLINK) $(LIBMNL)

 $(APP): $(OBJS) $(LIBNETFILTER_QUEUE) $(LIBMNL)
        @echo 'CCLD $(APP)'
-       @$(CCLD) $(OBJS) -o $(APP) -L$(DEPSDIR)/lib -lmnl -lnetfilter_queue
+       @$(CCLD) $(OBJS) -o $(APP) -L$(DEPSDIR)/lib -lmnl -lnetfilter_queue -static

 $(BUILD_DIR)/%.o: %.c $(LIBNETFILTER_QUEUE) $(LIBMNL)
        @echo 'CC $@'
```

Если очень надо статически прилинковать libc используйте этот патч. Но тогда пакет весит 370 килобай. 

Вообще, вроде как libgcc1 и libpthread должны стоять на роутере. и проблем с этим быть не должно

**Comment by azhinu** [comment]
@Waujito Спасибо! Весь день пыталась собрать под свой роутер, ничего не вышло, так что полностью статический  бинарник решил проблему.
