### ISSUE TITLE
Не устанавливается. Fedora 39

### ISSUE THREAD

**Issue by fraudlord** [Waujito/youtubeUnblock#26]
/usr/bin/ld: /tmp/ccngG0yl.o: in function `tcp4_frag':
youtubeUnblock.c:(.text+0x8b): undefined reference to `nfq_ip_get_hdr'
/usr/bin/ld: youtubeUnblock.c:(.text+0xc3): undefined reference to `nfq_ip_set_transport_header'
/usr/bin/ld: youtubeUnblock.c:(.text+0xe8): undefined reference to `nfq_tcp_get_hdr'
/usr/bin/ld: youtubeUnblock.c:(.text+0x10d): undefined reference to `nfq_tcp_get_payload'
/usr/bin/ld: youtubeUnblock.c:(.text+0x11d): undefined reference to `nfq_tcp_get_payload_len'
/usr/bin/ld: youtubeUnblock.c:(.text+0x278): undefined reference to `nfq_tcp_compute_checksum_ipv4'
/usr/bin/ld: youtubeUnblock.c:(.text+0x284): undefined reference to `nfq_tcp_compute_checksum_ipv4'
/usr/bin/ld: youtubeUnblock.c:(.text+0x298): undefined reference to `pktb_alloc'
/usr/bin/ld: youtubeUnblock.c:(.text+0x2bb): undefined reference to `pktb_alloc'
/usr/bin/ld: youtubeUnblock.c:(.text+0x2d3): undefined reference to `pktb_free'
/usr/bin/ld: /tmp/ccngG0yl.o: in function `send_raw_socket':
youtubeUnblock.c:(.text+0x2fa): undefined reference to `pktb_len'
/usr/bin/ld: youtubeUnblock.c:(.text+0x355): undefined reference to `pktb_free'
/usr/bin/ld: youtubeUnblock.c:(.text+0x36c): undefined reference to `pktb_free'
/usr/bin/ld: youtubeUnblock.c:(.text+0x374): undefined reference to `pktb_free'
/usr/bin/ld: youtubeUnblock.c:(.text+0x383): undefined reference to `pktb_free'
/usr/bin/ld: youtubeUnblock.c:(.text+0x390): undefined reference to `nfq_ip_get_hdr'
/usr/bin/ld: youtubeUnblock.c:(.text+0x3ab): undefined reference to `nfq_ip_set_transport_header'
/usr/bin/ld: youtubeUnblock.c:(.text+0x3b7): undefined reference to `nfq_tcp_get_hdr'
/usr/bin/ld: youtubeUnblock.c:(.text+0x3c2): undefined reference to `nfq_udp_get_hdr'
/usr/bin/ld: youtubeUnblock.c:(.text+0x405): undefined reference to `pktb_len'
/usr/bin/ld: youtubeUnblock.c:(.text+0x40f): undefined reference to `pktb_data'
/usr/bin/ld: /tmp/ccngG0yl.o: in function `fallback_accept_packet':
youtubeUnblock.c:(.text+0x485): undefined reference to `nfq_nlmsg_put'
/usr/bin/ld: youtubeUnblock.c:(.text+0x497): undefined reference to `nfq_nlmsg_verdict_put'
/usr/bin/ld: youtubeUnblock.c:(.text+0x4aa): undefined reference to `mnl_socket_sendto'
/usr/bin/ld: /tmp/ccngG0yl.o: in function `queue_cb':
youtubeUnblock.c:(.text+0x503): undefined reference to `nfq_nlmsg_parse'
/usr/bin/ld: youtubeUnblock.c:(.text+0x53a): undefined reference to `mnl_attr_get_payload'
/usr/bin/ld: youtubeUnblock.c:(.text+0x552): undefined reference to `mnl_attr_get_payload_len'
/usr/bin/ld: youtubeUnblock.c:(.text+0x55d): undefined reference to `mnl_attr_get_payload'
/usr/bin/ld: youtubeUnblock.c:(.text+0x56e): undefined reference to `mnl_attr_get_u32'
/usr/bin/ld: youtubeUnblock.c:(.text+0x59b): undefined reference to `mnl_attr_get_u32'
/usr/bin/ld: youtubeUnblock.c:(.text+0x896): undefined reference to `nfq_nlmsg_put'
/usr/bin/ld: youtubeUnblock.c:(.text+0x8ac): undefined reference to `nfq_nlmsg_verdict_put'
/usr/bin/ld: youtubeUnblock.c:(.text+0x8f0): undefined reference to `nfq_nlmsg_verdict_put'
/usr/bin/ld: youtubeUnblock.c:(.text+0x936): undefined reference to `pktb_alloc'
/usr/bin/ld: youtubeUnblock.c:(.text+0x95a): undefined reference to `pktb_mangle'
/usr/bin/ld: youtubeUnblock.c:(.text+0x975): undefined reference to `pktb_mangle'
/usr/bin/ld: youtubeUnblock.c:(.text+0x97d): undefined reference to `nfq_ip_get_hdr'
/usr/bin/ld: youtubeUnblock.c:(.text+0x995): undefined reference to `nfq_ip_set_transport_header'
/usr/bin/ld: youtubeUnblock.c:(.text+0x9a6): undefined reference to `nfq_tcp_get_hdr'
/usr/bin/ld: youtubeUnblock.c:(.text+0x9bd): undefined reference to `pktb_free'
/usr/bin/ld: youtubeUnblock.c:(.text+0x9dd): undefined reference to `nfq_ip_set_checksum'
/usr/bin/ld: youtubeUnblock.c:(.text+0x9ec): undefined reference to `nfq_tcp_compute_checksum_ipv4'
/usr/bin/ld: youtubeUnblock.c:(.text+0xa3d): undefined reference to `pktb_alloc'
/usr/bin/ld: youtubeUnblock.c:(.text+0xa57): undefined reference to `pktb_free'
/usr/bin/ld: youtubeUnblock.c:(.text+0xa8b): undefined reference to `pktb_free'
/usr/bin/ld: youtubeUnblock.c:(.text+0xaf2): undefined reference to `pktb_free'
/usr/bin/ld: youtubeUnblock.c:(.text+0xafa): undefined reference to `pktb_free'
/usr/bin/ld: youtubeUnblock.c:(.text+0xb02): undefined reference to `pktb_free'
/usr/bin/ld: /tmp/ccngG0yl.o:youtubeUnblock.c:(.text+0xb0a): more undefined references to `pktb_free' follow
/usr/bin/ld: /tmp/ccngG0yl.o: in function `queue_cb':
youtubeUnblock.c:(.text+0xb1d): undefined reference to `mnl_socket_sendto'
/usr/bin/ld: /tmp/ccngG0yl.o: in function `delay_packet_send':
youtubeUnblock.c:(.text+0xb7f): undefined reference to `pktb_free'
/usr/bin/ld: /tmp/ccngG0yl.o: in function `close_socket.isra.0':
youtubeUnblock.c:(.text.unlikely+0xe): undefined reference to `mnl_socket_close'
/usr/bin/ld: /tmp/ccngG0yl.o: in function `main':
youtubeUnblock.c:(.text.startup+0xb4): undefined reference to `mnl_socket_open'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0xd4): undefined reference to `mnl_socket_bind'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0xea): undefined reference to `mnl_socket_close'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0xfb): undefined reference to `mnl_socket_get_portid'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0x234): undefined reference to `nfq_nlmsg_put'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0x249): undefined reference to `nfq_nlmsg_cfg_put_cmd'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0x25c): undefined reference to `mnl_socket_sendto'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0x27e): undefined reference to `nfq_nlmsg_put'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0x293): undefined reference to `nfq_nlmsg_cfg_put_params'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0x2af): undefined reference to `mnl_attr_put_u32'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0x2c1): undefined reference to `mnl_attr_put_u32'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0x2d4): undefined reference to `mnl_socket_sendto'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0x2fa): undefined reference to `mnl_socket_setsockopt'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0x30c): undefined reference to `mnl_socket_recvfrom'
/usr/bin/ld: youtubeUnblock.c:(.text.startup+0x345): undefined reference to `mnl_cb_run'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: youtubeUnblock] Error 1

**Comment by Waujito** [comment]
```
[root@d6133c915622 youtubeUnblock]# history
    1  yum install git gcc make autoconf automake pkg-config libtool glibc-static
    2  git clone https://github.com/Waujito/youtubeUnblock
    3  cd youtubeUnblock/
    4  make
    5  make install
    6  history
```
Docker, Fedora 39. Проблем нет.

**Comment by fraudlord** [comment]
Вышеперечисленое уже было установлено (git gcc make autoconf automake pkg-config libtool glibc-static), сделал все еще раз (пробовал до этого раз 10, те же ошибки выдавало), внезапно установилось. Чудо, не иначе. Теперь всё работает как надо, спасибо
