### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by sivanoff** [Waujito/youtubeUnblock#27]
Doesn't work via ipv6 even after ` ip6tables -t mangle -A OUTPUT -p tcp -m tcp --dport 443 -j NFQUEUE --queue-num 537 --queue-bypass`

Should this work with ipv6 connection?

**Comment by Waujito** [comment]
Ipv6 is unsupported yet. 

Btw on ipv6 for me here is no TSPU on ipv6 (Rostelecom). Does YouTube throttled on your ipv6?

**Comment by sivanoff** [comment]
> Btw for me here is no TSPU on ipv6 (Rostelecom). Does YouTube throttled on your ipv6?
Yes it stopped working recently. Have to switch off ipv6 to watch youtube in Chromium. But it still doesn't work in Kodi, may be you can please tell why, may be kodi youtube plugin uses sni which is not handled?

**Comment by Waujito** [comment]
The problem may also hide in quic.

**Comment by sivanoff** [comment]
> The problem may also hide in quic if we're talking about players. Track it in #30

searched for quic in kodi youtube plugin repo and found solution which uses this tool https://github.com/hufrea/byedpi

**Comment by Klink0v** [comment]
> Btw for me here is no TSPU on ipv6 (Rostelecom). Does YouTube throttled on your ipv6?

У меня тоже Ростелеком / Онлайм. Одно время QUIC через IPv6 ходил нормально, но потом его тоже придушили.

**Comment by Waujito** [comment]
Hello! Can you test out #93 with ipv6 support? Binaries are available here: https://github.com/Waujito/youtubeUnblock/actions/runs/10582327899

**Comment by sivanoff** [comment]
I was able to view videos in chromium and kodi via ipv6 with this version. Thanks
