### ISSUE TITLE
How to disable debug?

### ISSUE THREAD

**Issue by antiuser** [Waujito/youtubeUnblock#34]
Hi there!
I want to know how to disable debug? Will be great if i can start youtubeUnblock without debug option.
This youtubeUnblock work great on 4gbps traffic. Will try this to 12gbps traffic, and leave feedback necessary.
Thanks!

**Comment by Waujito** [comment]
Hello! 
You can disable verbosity (google video! packet split! and warning google video is too big) by passing -DSILENT as CFLAGS.

And.. 4 gbps, 12 gbps... Are you an ISP? 
Which iptables rule do you use? Are you using connbytes or packets counter for performance?

**Comment by antiuser** [comment]
Yep, im testing this with rule
`iptables -t mangle -A FORWARD -p tcp -m tcp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass `

**Comment by altlc** [comment]
Кстати на linux вот с этим не работает -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19,
только пакеты целиком, на трафике под 6 гиг... Может smp так влияет...

**Comment by Waujito** [comment]
> Кстати на linux x64 вот с этим не работает -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19, только пакеты целиком, на трафике под 6 гиг. Может smp так влияет. Логи на вид никак не меняются, только разблокировка не происходит.

Весь трафик приходится через youtubeUnblock гонять? Странно, как будто бы коннбайтсы должны прекрасно работать

**Comment by altlc** [comment]
> Весь трафик приходится через youtubeUnblock гонять? Странно, как будто бы коннбайтсы должны прекрасно работать
Приходится. Сам не пойму почему не работает, по логике должно. Загрузка прям на порядки падает но не рабортает.

**Comment by Waujito** [comment]
> Приходится. Сам не пойму почему не работает, по логике должно. Загрузка прям на порядки падает но не рабортает.

Так, ну начнём с того, что youtubeUnblock блокирует пакет в цепочке и не даёт ему идти дальше. Я как бы не вижу больше вариантов почему оно может не работать. Второе правило, которое на метках работает стоит в OUTPUT?

Если уж прям так надо гонять всё через youtubeUnblock, можно использовать `--threads=n` для программы и --queue-balance `queue_num:queue_num + n` в iptables

**Comment by altlc** [comment]
Сам натупил, у меня notrack в raw стоял на мой адрес, с которого проверял, вот и не работаело.

**Comment by antiuser** [comment]
`--silent`
this arg disable messages in syslog
