### ISSUE TITLE
pre-built packages?

### ISSUE THREAD

**Issue by bam80** [Waujito/youtubeUnblock#36]
Hi,
thanks for the building instructions,
but could we make some pre-built packages for OpenWrt and release them?
Manually or with GitHub Actions, etc.
Thanks.

**Comment by Waujito** [comment]
Idk. It will be great if we do it with GitHub actions but here is too much architectures. Probably, openwrt supports multibuilds but idk.  I will dig in this problem.

**Comment by jelly8173** [comment]
Static binary should work on any OpenWRT version, as kernel api for netlink sockets are stable, so the easiest way to test it is to provide a binary and collect user reports from different OpenWRT versions and adjust accordingly. Even non-static binary should work if user has access to official OpenWRT feeds (needs it anyways in order to install required kmods)

**Comment by bam80** [comment]
> Probably, openwrt supports multibuilds

I'm pretty sure it does. Let me know if you need help, anyway.

> It will be great if we do it with GitHub actions

If you didn't use GitHub Actions before (I didn't), getting familiar with it might take significant time.
For such a tiny project like this, it might be an overkill also.

Instead, could we please manually build and publish some most common platform's packages first, say, for the latest OpenWrt release?
Full automation is a separate task here.

**Comment by Waujito** [comment]
@spvkgn 
> Packages for 23.05 (arm and mips) built with SDK using GH Actions: https://github.com/spvkgn/youtubeUnblock/releases

Wow, thats great! I see the ways to enhance it. For example we don't really want to update openwrt feeds each time. I didn't know that openwrt publishes their docker images with sdk and that it is too easy to deal with it. Please, create the pull request. I want to merge it to separate branch first, apply my fixes and then merge with main. And can you disable auto release? I want to publish it manually.
Thanks

**Comment by antiuser** [comment]
Will be there packages available for Zyxel Keenetic?
https://habr.com/ru/articles/833564/

**Comment by Waujito** [comment]
98e1c2f5d6dbe82f76cd7f2f7f18e077a9b89ab3 fixes the issue, thanks to @spvkgn 


> Will be there packages available for Zyxel Keenetic? https://habr.com/ru/articles/833564/
I will play with entware.

Also a good option is add normal binaries for x86_64 and i386

**Comment by Waujito** [comment]
So the issue may be closed now. 
Thanks a lot to @spvkgn for buildsystem for OpenWRT (#47) and normal static binaries (#50).

In 80811a41e6e3ae9540aaa0e51b48f5f48a50bcad I have also added the support for Keenetics and other routers driven by Entware.

**Comment by bam80** [comment]
Thanks to all for the quick solving! (I didn't try it but hope it's all right there)

The next step I suppose would be creating an OpenWrt feed for easy installation/upgrade.

You guys rock! :+1:
