### ISSUE TITLE
*.youtube.com is filtered as well

### ISSUE THREAD

**Issue by SergejVolkov** [Waujito/youtubeUnblock#40]
The tool does not work anymore. Zapret users report youtube.com, yt3.ggpht.com, i.ytimg.com, i9.ytimg.com have been blocked since this morning: https://github.com/bol-van/zapret/discussions/200
![Screenshot_2024-08-08_11-07-50](https://github.com/user-attachments/assets/2262e715-70d3-46f5-beaa-b2ee149af91d)

**Comment by Waujito** [comment]
I see. Try to duplicate the program and I'm mangle.c replace googlevideo.com with youtube.com
Note that you need two instances of youtubeUnblock one with googlevideo and second with youtube

**Comment by Waujito** [comment]
Whoops, that won't work. Please, wait for the new version.

**Comment by manchelsi** [comment]
Is it possible to add these hosts:
ytimg.com
l.google.com
youtube.com
?

**Comment by CHuKeR** [comment]
fyi, goodbyedpi works on Windows, maybe should look at this

**Comment by asuasu** [comment]
I made a dirty quick fix to check a list of hardcoded domains and it seems to be working well, but of course it is better to load a list from file on startup.

```patch
diff --git a/mangle.c b/mangle.c
index b049168..31447cb 100644
--- a/mangle.c
+++ b/mangle.c
@@ -285,6 +285,21 @@ int tcp4_frag(const __u8 *pkt, __u32 buflen, __u32 payload_offset,
 #define TLS_EXTENSION_SNI 0x0000
 #define TLS_EXTENSION_CLIENT_HELLO_ENCRYPTED 0xfe0d
 
+struct
+{
+	char *domain;
+	int len;
+}
+domains[] =
+{
+	{ "googlevideo.com", 15 },
+	{ "youtube.com", 11 },
+	{ "ggpht.com", 9 },
+	{ "ytimg.com", 9 },
+};
+
+int domains_count = 4;
+
 const char googlevideo_ending[] = "googlevideo.com";
 const int googlevideo_len = 15;
 
@@ -406,14 +421,17 @@ struct verdict analyze_tls_data(
 			vrd.sni_offset = (uint8_t *)sni_name - data;
 			vrd.sni_len = sni_len;
 
-			char *gv_startp = sni_name + sni_len - googlevideo_len;
-			if (sni_len >= googlevideo_len &&
-				sni_len < 128 && 
-				!strncmp(gv_startp, 
-				googlevideo_ending, 
-				googlevideo_len)) {
-
-				vrd.gvideo_hello = 1;
+			for (int i = 0; i < domains_count; ++i) {
+				char *gv_startp = sni_name + sni_len - domains[i].len;
+				if (sni_len >= domains[i].len &&
+					sni_len < 128 && 
+					!strncmp(gv_startp, 
+					domains[i].domain, 
+					domains[i].len))
+				{
+					vrd.gvideo_hello = 1;
+					break;
+				}
 			}
 
 nextExtension:

```

**Comment by Waujito** [comment]
> I made a dirty quick fix to check a list of hardcoded domains and it seems to be working well, but of course it is better to load a list from file on startup.
> 
> ```diff
> diff --git a/mangle.c b/mangle.c
> index b049168..31447cb 100644
> --- a/mangle.c
> +++ b/mangle.c
> @@ -285,6 +285,21 @@ int tcp4_frag(const __u8 *pkt, __u32 buflen, __u32 payload_offset,
>  #define TLS_EXTENSION_SNI 0x0000
>  #define TLS_EXTENSION_CLIENT_HELLO_ENCRYPTED 0xfe0d
>  
> +struct
> +{
> +	char *domain;
> +	int len;
> +}
> +domains[] =
> +{
> +	{ "googlevideo.com", 15 },
> +	{ "youtube.com", 11 },
> +	{ "ggpht.com", 9 },
> +	{ "ytimg.com", 9 },
> +};
> +
> +int domains_count = 4;
> +
>  const char googlevideo_ending[] = "googlevideo.com";
>  const int googlevideo_len = 15;
>  
> @@ -406,14 +421,17 @@ struct verdict analyze_tls_data(
>  			vrd.sni_offset = (uint8_t *)sni_name - data;
>  			vrd.sni_len = sni_len;
>  
> -			char *gv_startp = sni_name + sni_len - googlevideo_len;
> -			if (sni_len >= googlevideo_len &&
> -				sni_len < 128 && 
> -				!strncmp(gv_startp, 
> -				googlevideo_ending, 
> -				googlevideo_len)) {
> -
> -				vrd.gvideo_hello = 1;
> +			for (int i = 0; i < domains_count; ++i) {
> +				char *gv_startp = sni_name + sni_len - domains[i].len;
> +				if (sni_len >= domains[i].len &&
> +					sni_len < 128 && 
> +					!strncmp(gv_startp, 
> +					domains[i].domain, 
> +					domains[i].len))
> +				{
> +					vrd.gvideo_hello = 1;
> +					break;
> +				}
>  			}
>  
>  nextExtension:
> ```

Yup, thank you for the patch. I wasn't at home so I couldn't do it. Now I'm ready. 

I don't want to store domains as file because it is too much overhead. I think, the better solution is to pass domains as one comma-separated string.

**Comment by asuasu** [comment]
> I don't want to store domains as file because it is too much overhead.

I personally don't think it is a big overhead, we just need to parse a file on startup and cache domains in the same manner as in my patch (maybe add binary search in future if there will be a lot of them). Yeah, the list could not be reloaded without a restart but at least a user could add more domains if they will continue to block more of them without editing the source code.

**Comment by Waujito** [comment]
Please, check for the issue to be fixed.

Parsing from file will also be a good option, so I will work around it.

**Comment by Lintech-1** [comment]
> @SergejVolkov Пытаться`youtubeUnblock 537 --sni-domains=googlevideo.com,ggpht.com,ytimg.com,l.google.com,youtube.com,play.google.com`
> 
> Или`youtubeUnblock 537 --sni-domains=all`

I tried your patch on my dom.ru provider and my YouTube started loading instantly!

**Comment by kraytor** [comment]
> ```diff
> domains[] =
> ```

It really be better to separate code and config. Code be much more clean. Load from file is much easier to config for nonprogrammer people.

**Comment by jelly8173** [comment]
> It really be better to separate code and config. Code be much more clean. Load from file is much easier to config for nonprogrammers and for programmers 🤣 too

Sure, you are welcome to do it if you want. Shouldn't be that hard

**Comment by kraytor** [comment]
> > It really be better to separate code and config. Code be much more clean. Load from file is much easier to config for nonprogrammers and for programmers 🤣 too
> 
> Sure, you are welcome to do it if you want. Shouldn't be that hard

Sorry, I'm a Python programmer, not C. It was more of a look from the program architecture side for more convenient setup and support.

**Comment by jelly8173** [comment]
Yeah, I'm pretty sure it will evolve that way as soon as someone will have enough free time to implement it
