### ISSUE TITLE
Some ISPs throw RST with youtubeUnblock

### ISSUE THREAD

**Issue by aykhan247** [Waujito/youtubeUnblock#43]
Поставил последнюю версию 0.2.1-2, после того как перестала работать 0.2 из-за новых блокировок, но к сожалению сайт открывается, но с ошибкой "Нет подключения к интернету"
![Снимок экрана от 2024-08-08 21-25-57](https://github.com/user-attachments/assets/3608825e-31a0-4b77-9025-a75f07d04b1d)

Правило в iptables добавляется, через curl скорость хорошая, что ещё можно глянуть?

**Comment by jaz-man** [comment]
У меня все норм.

**Comment by aykhan247** [comment]
> У меня все норм.

А запущен как сервис systemd?

**Comment by Waujito** [comment]
Что если отключить quic в chrome://flags

или network.http.http{2,3}.enable(d) в about:config в Firefox

**Comment by jaz119** [comment]
Да, на Ubuntu с systemd.

**Comment by jaz119** [comment]
> > У меня все норм.
> 
> А запущен как сервис systemd?

Да, на Ubuntu с systemd.

**Comment by aykhan247** [comment]
> Что если отключить quic в chrome://flags
> 
> или network.http.http{2,3}.enable(d) в about:config в Firefox

quick и так отключен был, а в firefox отключение http2,3 не помогло

**Comment by Waujito** [comment]
В логах сообщения есть о том, что гуглвидео встретил?

**Comment by aykhan247** [comment]
> В логах сообщения есть о том, что что-то встретил?

Да

```
journalctl -b -t youtubeUnblock
авг 08 18:44:41 ThinkPad youtubeUnblock[347845]: Using TCP segmentation
авг 08 18:44:41 ThinkPad youtubeUnblock[347845]: Fake SNI will be sent before each googlevideo request, Ack-Seq strategy will be used
авг 08 18:44:41 ThinkPad youtubeUnblock[347845]: GSO is enabled
авг 08 18:44:41 ThinkPad youtubeUnblock[347845]: Queue 537 started!
авг 08 18:44:41 ThinkPad youtubeUnblock[347845]: Google video!
авг 08 18:44:41 ThinkPad youtubeUnblock[347845]: Packet split in portion 134 465
авг 08 18:44:41 ThinkPad youtubeUnblock[347845]: Google video!
авг 08 18:44:41 ThinkPad youtubeUnblock[347845]: Packet split in portion 275 242
авг 08 18:44:41 ThinkPad youtubeUnblock[347845]: Google video!
авг 08 18:44:41 ThinkPad youtubeUnblock[347845]: Packet split in portion 144 455
авг 08 18:44:41 ThinkPad youtubeUnblock[347845]: Google video!
авг 08 18:44:41 ThinkPad youtubeUnblock[347845]: Packet split in portion 554 13
```

**Comment by Waujito** [comment]
Это не последняя версия :)

**Comment by Waujito** [comment]
Да, там поменялось сообщение. Теперь же всё-таки не гуглвидео, а чуть больше доменов.

Попробуйте не как сервис запускать, а просто `sudo ./youtubeUnblock 537`

**Comment by aykhan247** [comment]
Вот если бинарник запустить, видно же, что есть флаг --sni-domains, а он же появился в последней версии
```
 /usr/local/bin/youtubeUnblock
Usage: /usr/local/bin/youtubeUnblock <queue_num> [OPTIONS]
Options:
        --sni-domains=<comma separated domain list>|all
        --fake-sni={ack,ttl,none}
        --fake-sni-ttl=<ttl>
        --frag={tcp,ip,none}
        --seg2delay=<delay>
        --threads=<threads number>
        --silent
        --no-gso
Unable to parse args: Invalid argument
```

**Comment by Waujito** [comment]
Пробуйте --sni-domains=all тогда

**Comment by aykhan247** [comment]
> Пробуйте --sni-domains=all тогда

Добавил правило в iptables вручную, запустил, пошел вывод как кидал выше, но сайт так же не открывается(

**Comment by hukarere** [comment]
@Waujito так ведь youtubeUnblock.service не поменялся и в нем нет --sni-domains, может, надо добавить туда?

**Comment by aykhan247** [comment]
> @Waujito так ведь youtubeUnblock.service не поменялся и в нем нет --sni-domains, может, надо добавить туда?

Там по дефолту уже этот флаг выставлен на `googlevideo.com,youtube.com,ggpht.com,ytimg.com'. А у меня не работает даже если запускать бинарник без использования systemd

**Comment by Waujito** [comment]
> @Waujito так ведь youtubeUnblock.service не поменялся и в нем нет --sni-domains, может, надо добавить туда?

Нет, там по умолчанию всё.

**Comment by hukarere** [comment]
> Нет, там по умолчанию всё
Ну я к тому, что, возможно, у topic starter поэтому и не работает, что из   youtubeUnblock.service запускается без --sni--domains?

**Comment by Waujito** [comment]
> > Пробуйте --sni-domains=all тогда
> 
> Добавил правило в iptables вручную, запустил, пошел вывод как кидал выше, но сайт так же не открывается(

Но вывод с google video?

**Comment by hukarere** [comment]
А, проверил последнюю версию, уже действительно не надо --sni-domains добавлять...

**Comment by aykhan247** [comment]
> > > Пробуйте --sni-domains=all тогда
> > 
> > 
> > Добавил правило в iptables вручную, запустил, пошел вывод как кидал выше, но сайт так же не открывается(
> 
> Но вывод с google video?
Вот такой вывод:

```
youtubeUnblock[961]: Using TCP segmentation
youtubeUnblock[961]: Fake SNI will be sent before each googlevideo request, Ack-Seq strategy will be used
youtubeUnblock[961]: GSO is enabled
youtubeUnblock[961]: Queue 537 started!
youtubeUnblock[961]: SNI target detected
youtubeUnblock[961]: Packet split in portion 174 361
youtubeUnblock[961]: SNI target detected
youtubeUnblock[961]: Packet split in portion 216 301
youtubeUnblock[961]: SNI target detected
```

**Comment by 87elijah87** [comment]
> > > > Пробуйте --sni-domains=all тогда
> > > 
> > > 
> > > Добавил правило в iptables вручную, запустил, пошел вывод как кидал выше, но сайт так же не открывается(
> > 
> > 
> > Но вывод с google video?
> 
> Вот такой вывод:
> 
> ```
> youtubeUnblock[961]: Using TCP segmentation
> youtubeUnblock[961]: Fake SNI will be sent before each googlevideo request, Ack-Seq strategy will be used
> youtubeUnblock[961]: GSO is enabled
> youtubeUnblock[961]: Queue 537 started!
> youtubeUnblock[961]: SNI target detected
> youtubeUnblock[961]: Packet split in portion 174 361
> youtubeUnblock[961]: SNI target detected
> youtubeUnblock[961]: Packet split in portion 216 301
> youtubeUnblock[961]: SNI target detected
> ```

попробуй так запускать
youtubeUnblock 537 --seg2delay=400

**Comment by aykhan247** [comment]
> попробуй так запускать youtubeUnblock 537 --seg2delay=400

Спасибо добрый человек, помогло!

**Comment by Waujito** [comment]
А попробуйте флаг --fake-sni=ttl

**Comment by Waujito** [comment]
> попробуй так запускать youtubeUnblock 537 --seg2delay=400

400 слишком долго и может ломать соединение, но если помогает - без проблем)

**Comment by aykhan247** [comment]
> > попробуй так запускать youtubeUnblock 537 --seg2delay=400
> 
> 400 слишком долго и может ломать соединение, но если помогает - без проблем)

Я сначала подумал, что помогло, оказывается впн был включен(

В общем попробовал и с --fake-sni=ttl, тоже без результата

**Comment by 87elijah87** [comment]
> > попробуй так запускать youtubeUnblock 537 --seg2delay=400
> 
> 400 слишком долго и может ломать соединение, но если помогает - без проблем)

поднимал до этого значения пока не заработало :). До него - глухо

**Comment by Waujito** [comment]
У меня походу fake-sni=ttl сломалось )

**Comment by Waujito** [comment]
Пробуйте последний коммит 8e3fa48

**Comment by aykhan247** [comment]
> Пробуйте последний коммит [8e3fa48](https://github.com/Waujito/youtubeUnblock/commit/8e3fa48510737914f9eccf6d119d6e97efae1de8) С --fake-sni=ttl

Без изменений(

**Comment by Waujito** [comment]
Тогда можете сделать два дампа pcap? Один с --fake-sni=ttl, другой без. Делать можно вайршарком или `tcpdump -w dump.pcap` Между и перед дампами перезапускайте все инстансы браузера. Если страшно оставлять их тут в свободном доступе, напишите мне в тг https://t.me/waujito

**Comment by MaksimAnishko** [comment]
Собрал с последними правками и у меня заработало.

**Comment by jelly8173** [comment]
**offtopic**: По хорошему провайдер может заблокировать все, что бы мы не наизобретали, даже есть знаменитое высказывание, которое приписывают Энштейну или кому-то вроде него: "Ни одна проблема не решается на одном уровне абстакции, где она возникает". В связи с чем, предлагаю всем, кто столкнулся с блокировками от провайдера -- в срочном порядке идти подать заявление на отключение, в графе причина указать: "не работает youtube", и подключиться к нормальному провайдеру (тоже срочно, чтобы эффект был всем заметен). В данный момент на Yota у меня нет никаких проблем с Youtube

**Comment by zabbius** [comment]
@jelly8173 блин, чувак, ну не порти классную штуку. Эта тулза не только и не столько для обхода DPI, сколько для фана и бесценного опыта. Интересен в первую очередь процесс.

**Comment by Waujito** [comment]
> **offtopic**: По хорошему провайдер может заблокировать все, что бы мы не наизобретали, даже есть знаменитое высказывание, которое приписывают Энштейну или кому-то вроде него: "Ни одна проблема не решается на одном уровне абстакции, где она возникает". В связи с чем, предлагаю всем, кто столкнулся с блокировками от провайдера -- в срочном порядке идти подать заявление на отключение, в графе причина указать: "не работает youtube", и подключиться к нормальному провайдеру (тоже срочно, чтобы эффект был всем заметен). В данный момент на Yota у меня нет никаких проблем с Youtube
> 
> --
> 
> Логика простая -- государство открыто призналось, что мобильный трафик пока ограничивать не может, так зачем воевать на его территории, где уже есть вся инфраструктура и обходные пути блокируются за три дня, если можно просто уйти туда, где у него лапки не достают и надо прилагать значительные усилия?

Знаешь, это как с парсингом. Никто не хочет, чтоб его делали, все блокируют его как только можно. Клаудфлари там всякие и тому подобные приколы, но всё равно мы можем найти обход. Тут собственно тоже самое. Играем на несовершенстве провайдеров и строим обходы. Сейчас можно было залезть в политику но зачем, если все и так всё понимают.

**Comment by jelly8173** [comment]
Я не настаиваю, просто озвучиваю очевидные вещи для тех, кто пришел искать решение, а не тренажер для своих программерских способностей. Идет очевидная война брони и снаряда и конца и края этому не будет, так что не переживайте за то что останетесь не у дел.

В свою очередь предлагаю обдумать возможный функционал для benchmark-а ТСПУ -- набор тестов для определения возможных параметров задержек, TTL, вариантов фрагментации, чтобы сделать процесс отладки более быстрым за счет сокращения ряда вопросов туда-обратно. Можно даже какую-то отладочную информацию выводить.

**Comment by Waujito** [comment]
> В свою очередь предлагаю обдумать возможный функционал для benchmark-а ТСПУ -- набор тестов для определения возможных параметров задержек, TTL, вариантов фрагментации, чтобы сделать процесс отладки более быстрым за счет сокращения ряда вопросов туда-обратно. Можно даже какую-то отладочную информацию выводить (например версию программы при запуске).

С версией согласен. На счёт проверок для ТСПУ сложнее, возможно стоит просто добавить это в отдельный md файлик и заставить в issue прикреплять. Хотя в целом можно и самим программно создавать сокеты и чекать на RST. Хотя, замедление гуглвидео так определить невозможно.

**Comment by antiuser** [comment]
> **offtopic**: По хорошему провайдер может заблокировать все, что бы мы не наизобретали, даже есть знаменитое высказывание, которое приписывают Энштейну или кому-то вроде него: "Ни одна проблема не решается на одном уровне абстакции, где она возникает". В связи с чем, предлагаю всем, кто столкнулся с блокировками от провайдера -- в срочном порядке идти подать заявление на отключение, в графе причина указать: "не работает youtube", и подключиться к нормальному провайдеру (тоже срочно, чтобы эффект был всем заметен). В данный момент на Yota у меня нет никаких проблем с Youtube
> 
> --
> 
> Логика простая -- государство открыто призналось, что мобильный трафик пока ограничивать не может, так зачем воевать на его территории, где уже есть вся инфраструктура и обходные пути блокируются за три дня, если можно просто уйти туда, где у него лапки не достают и надо прилагать значительные усилия?

я тут отвечу по русски уже :) раз более политическая пьянка пошла, то есть вы предлагаете чтоб все сбежали с ШПД провайдеров на мобильных? Вы в своем уме? :) представляете сколько бизнеса погибнет? :) Вопрос работы у мобильных операторов - вопрос лишь времени, не более того. Операторы не блокируют ничего в плане ютюба, да они блокируют то что есть в реестре роскомнадзора, иначе штраф, полное соблюдение законов, все прозрачно, и это тоже было трудно сделать, провайдеры вместо того чтобы заниматься развитием своих сетей 5 лет занимались тем как бы соблюдать законы, чтобы обойтись без штрафов и обнуления лицензий предоставления услуг. Но правительство решило еще подкинуть камень в воду устанавливая насильно ТСПУ (кстати говоря, за аренду и за содержание электроэнергии платит опять таки провайдер, а прерогатива эта чисто РКН). Спорить ни с чем не буду, говорю как есть, потому что 13 лет посвятил телекому. А вообще предлагаю закрыть этот ISSUE, сообщения не относятся к проблеме

**Comment by jelly8173** [comment]
Простыня большая, цитировать не буду, просто скажу, что это переведет плоскость борьбы с юзерлевела на уровень админа -- если бизнес начнет страдать, он будет пытаться предпринять что-то, а это уже сила, потому что пользователь бесправная букашка, а у бизнеса есть деньги и влияние. Если кто-то что-то и может изменить, то это он. Задача пользователя -- выбрать того, кто отстаивает его интересы, и если это отдает преференции конкретным мобильным операторам -- они будут жить, другие вымрут. Это называется "голосовать рублем", и именно из-за того, что мы не приучены использовать подобные практики -- большинство наших проблем. Пипл хавает -- и блокировку ютуба схавает.

**Comment by Waujito** [comment]
> А вообще предлагаю закрыть этот ISSUE, сообщения не относятся к проблеме

Увы, я общаюсь с автором, и у него действительно что-то странное творится)

**Comment by jelly8173** [comment]
Я действительно прошу прощения, за то что разговор перерос в политическую плоскость. Просто удивительно, что некоторые не понимают, что бизнесы должны решать свои вопросы сами, не за счет пользователей. И то что рутуб с ВК видео прибегли к подобному способу конкуренции сойдет им с рук только если пользователи это схавают -- читай "не отключатся от провайдера, который выступает в этом случае подельником". У нас же официальная позиция сейчас -- сервера Гугл Кеша устарели, и мы тут отлично видим, что нам пи**ят

**Comment by jelly8173** [comment]
> С версией согласен. На счёт проверок для ТСПУ сложнее, возможно стоит просто добавить это в отдельный md файлик и заставить в issue прикреплять. Хотя в целом можно и самим программно создавать сокеты и чекать на RST. Хотя, замедление гуглвидео так определить невозможно.

Ну я имею в виду автоматическая подгонка параметров и тесты, например можно определять на какой хопе сидит ТСПУ, используя подобие курл теста постепенно увеличивая ттл, тот же тест с разными параметрами задержек и всевозможными комбинациями разбиения пакетов. То есть развитие в сторону улучшения основного функционала программы

**Comment by zabbius** [comment]
@jelly8173 звучит как альтернатива GoodByeDPI, но под линух. Категорически за и готов вписаться в движуху

**Comment by Waujito** [comment]
Сервера гугла теперь проксируются "ужесточённо".
Вот прямо на данный момент v2.0 работает, а v2.2 не работает?

**Comment by Waujito** [comment]
> На данный момент из unblock не работает ни одна версия.

Можете точно сказать какие настройки запрета используются?

**Comment by Waujito** [comment]
Может быть поможет —fake-sni=ttl?

**Comment by Waujito** [comment]
Not solved yet.

**Comment by Waujito** [comment]
@rngvalerka Обновление доступно, и я буду благодарен если протестируете youtubeUnblock на последней версии.
Чтобы максимально близко эмулировать действия zapret на ваших настройках, сделайте
`youtubeUnblock --sni-domains=all --faking-strategy=ttl --faking-ttl=4 --fk-winsize=1`

Если не сработает, дам патч, который имплементирует абсолютно такое же поведение, как и в zapret.

Проверять
```
curl -o/dev/null -k --connect-to ::google.com -k -L -H Host:\ mirror.gcr.io https://test.googlevideo.com/v2/cimg/android/blobs/sha256:6fd8bdac3da660bde7bd0b6f2b6a46e1b686afb74b9a4614def32532b73f5eaa
```

**Comment by Waujito** [comment]
И смысл сюда писать если после трёх комментариев "я сливаюсь"

**Comment by Waujito** [comment]
И так, автор утверждает, что его проблема решилась. Скорее всего, п юровайдер что-то тестировал. Нам остаётся только ждать. Если у кого-то ещё она сохраняется - пишите.

**Comment by Waujito** [comment]
Проблему можно считать окончательно исправленной. У автора всё работает на последнем коммите с флагами `youtubeUnblock --frag-sni-pos=1 --sni-domains=all`. Закрываю.
