### ISSUE TITLE
Not working on 2 port arm target

### ISSUE THREAD

**Issue by Igorbunow** [Waujito/youtubeUnblock#48]
I try to run this utility on ssd202d arm target with 2 ethenet port eth0 and eth1.
eth0 - to internet
eth1 - local network

Iptable rooles are:

```
iptables -I OUTPUT -m mark --mark 32768/32768 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j NFQUEUE --queue-num 537 --queue-bypass
iptables -t mangle -A FORWARD -p tcp -m tcp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass
iptables -I FORWARD 1 -i eth0 -o eth1 -j ACCEPT
iptables -I FORWARD 1 -i eth1 -o eth0 -j ACCEPT
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
```
Ip forwarding is on:

`sysctl -w net.ipv4.ip_forward=1`

kernel build with NFQUEUE support.

After runing 

`./youtubeUnblock 537`

and youtube on on PC I see:

```
xt_connbytes: Forcing CT accounting to be enabled
Using TCP segmentation
Fake SNI will be sent before each googlevideo request, Ack-Seq strategy will be used
GSO is enabled
Queue 537 started!
SNI target detected
Packet split in portion 165 352
SNI target detected
WARNING! Client Hello packet is too big and may cause issues!
Packet split in portion 442 1333
Split packet!
Packet split in portion 1256 77
SNI target detected
WARNING! Client Hello packet is too big and may cause issues!
Packet split in portion 165 1578
Split packet!
Packet split in portion 1256 322
SNI target detected
WARNING! Client Hello packet is too big and may cause issues!
Packet split in portion 1464 490
Split packet!
Packet split in portion 1256 208
SNI target detected
```

And no video loading.

But curl test passing OK (directly on target and on PC, connected to eth1):

```
curl --connect-to ::speedtest.selectel.ru https://manifest.googlevideo.com/100MB -k -o/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  100M  100  100M    0     0   9.8M      0  0:00:10  0:00:10 --:--:-- 11.1M
```

How can i fix this problem? What can I do with my arm target?

In case runing util directly on PC, curl test and youtube works fine, but in chrome broser only

**Comment by zabbius** [comment]
second rule should be 
```
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
```
I guess

**Comment by zabbius** [comment]
Why do you need the secod rule ?
```
iptables -A OUTPUT -p tcp --dport 443 -j NFQUEUE --queue-num 537 --queue-bypass
```

If your device is used as router, you've already redirected traffic with mangle. 
And maybe adding interface names will be good idea.

**Comment by Igorbunow** [comment]
> Why do you need the secod rule ?
> ```
> iptables -A OUTPUT -p tcp --dport 443 -j NFQUEUE --queue-num 537 --queue-bypass
> ```
> 
> If your device is used as router, you've already redirected traffic with mangle. 
> And maybe adding interface names will be good idea.

This rule used only for internal router curl test only. So curl test works perfcecly well into router console and in local network

**Comment by zabbius** [comment]
@Igorbunow Are you sure that this rule will not intercept packlets which were already forged and sent by the tool?
I mean something like this:
1. packet to *.googlevideo.com:443 is intercepted and send to tool's queue 
2. tool drops the packet and generates some new ones
3. instead of sending to wan they are intercepted again by the second rule

**Comment by Igorbunow** [comment]
After removing this rule, curl test only working in local net, youtube not...

My full iptable is:



```
# iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 289 packets, 81822 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 42 packets, 5477 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 1 packets, 72 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  248 76417 MASQUERADE  0    --  *      eth0    0.0.0.0/0            0.0.0.0/0           
# iptables -t mangle -L -n -v
Chain PREROUTING (policy ACCEPT 78771 packets, 114M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 3060 packets, 176K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 73971 packets, 113M bytes)
 pkts bytes target     prot opt in     out     source               destination         
 1740  808K NFQUEUE    6    --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 connbytes 0:19 connbytes mode packets connbytes direction original NFQUEUE num 537 bypass

Chain OUTPUT (policy ACCEPT 2981 packets, 653K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 78677 packets, 114M bytes)
 pkts bytes target     prot opt in     out     source               destination         
# iptables  -L -n -v
Chain INPUT (policy ACCEPT 3096 packets, 179K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
43903 3720K ACCEPT     0    --  eth1   eth0    0.0.0.0/0            0.0.0.0/0           
31794  110M ACCEPT     0    --  eth0   eth1    0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 2946 packets, 608K bytes)
 pkts bytes target     prot opt in     out     source               destination         
   58 47882 ACCEPT     0    --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x8000/0x8000
```

**Comment by Waujito** [comment]
Hello!
Can you post the output of `curl https://youtube.com` with and without youtubeUnblock enabled?

**Comment by Waujito** [comment]
Or if you haven't troubles with youtube do that with `curl https://googlevideo.com`

**Comment by Igorbunow** [comment]
> Or if you haven't troubles with youtube do that with `curl https://googlevideo.com`

curl https://googlevideo.com -v
* Host googlevideo.com:443 was resolved.
* IPv6: 2a00:1450:4010:c03::67, 2a00:1450:4010:c03::6a, 2a00:1450:4010:c03::93, 2a00:1450:4010:c03::69
* IPv4: 209.85.233.103, 209.85.233.147, 209.85.233.105, 209.85.233.104, 209.85.233.106, 209.85.233.99
*   Trying 209.85.233.103:443...
* Connected to googlevideo.com (209.85.233.103) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=www.google.com
*  start date: Jul 30 12:50:13 2024 GMT
*  expire date: Oct 22 12:50:12 2024 GMT
*  subjectAltName does not match host name googlevideo.com
* SSL: no alternative certificate subject name matches target host name 'googlevideo.com'
* Closing connection
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (60) SSL: no alternative certificate subject name matches target host name 'googlevideo.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by Igorbunow** [comment]
> Hello! Can you post the output of `curl https://youtube.com` with and without youtubeUnblock enabled?

curl https://youtube.com -v
* Host youtube.com:443 was resolved.
* IPv6: 2a00:1450:4010:c09::5b, 2a00:1450:4010:c09::88, 2a00:1450:4010:c09::5d, 2a00:1450:4010:c09::be
* IPv4: 142.251.1.91, 142.251.1.190, 142.251.1.93, 142.251.1.136
*   Trying 142.251.1.91:443...
* Connected to youtube.com (142.251.1.91) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.google.com
*  start date: Jul 30 12:32:53 2024 GMT
*  expire date: Oct 22 12:32:52 2024 GMT
*  subjectAltName: host "youtube.com" matched cert's "youtube.com"
*  issuer: C=US; O=Google Trust Services; CN=WR2
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha384WithRSAEncryption
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://youtube.com/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: youtube.com]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.8.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: youtube.com
> User-Agent: curl/8.8.0
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 301 
< content-type: application/binary
< x-content-type-options: nosniff
< expires: Fri, 09 Aug 2024 20:36:43 GMT
< date: Fri, 09 Aug 2024 20:36:43 GMT
< cache-control: private, max-age=31536000
< location: https://www.youtube.com/
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-frame-options: SAMEORIGIN
< report-to: {"group":"youtube_main","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/youtube_main"}]}
< cross-origin-opener-policy: same-origin-allow-popups; report-to="youtube_main"
< origin-trial: AmhMBR6zCLzDDxpW+HfpP67BqwIknWnyMOXOQGfzYswFmJe+fgaI6XZgAzcxOrzNtP7hEDsOo1jdjFnVr2IdxQ4AAAB4eyJvcmlnaW4iOiJodHRwczovL3lvdXR1YmUuY29tOjQ0MyIsImZlYXR1cmUiOiJXZWJWaWV3WFJlcXVlc3RlZFdpdGhEZXByZWNhdGlvbiIsImV4cGlyeSI6MTc1ODA2NzE5OSwiaXNTdWJkb21haW4iOnRydWV9
< permissions-policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-wow64=*, ch-ua-form-factors=*, ch-ua-platform=*, ch-ua-platform-version=*
< content-security-policy: require-trusted-types-for 'script'
< server: ESF
< content-length: 0
< x-xss-protection: 0
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
< 
* Connection #0 to host youtube.com left intact

**Comment by Waujito** [comment]
Idk why but your curl automatically jumps to HTTP/2. Use --http1.1 to force it use normal tcp connection. Also I don't need in verbose mode. And I want two curl outputs per domain: with and without youtubeUnblock. About that error in googlevideo.com: use `manifest.googlevideo.com`

**Comment by Igorbunow** [comment]
> Idk why but your curl automatically jumps to HTTP/2. Use --http1.1 to force it use normal tcp connection. Also I don't need in verbose mode. And I want two curl outputs per domain: with and without youtubeUnblock. About that error in googlevideo.com: use `manifest.googlevideo.com`

=== Turn off YoutubeUnblock wait forewer

`~$ curl https://manifest.googlevideo.com --http1.1`


=== Turn on YoutubeUnblock wait forewer

```
~$ curl https://manifest.googlevideo.com --http1.1
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/</code> was not found on this server.  <ins>That’s all we know.</ins
```

**Comment by Igorbunow** [comment]
So, I see this warinigs:

```

SNI target detected
WARNING! Client Hello packet is too big and may cause issues!
Packet split in portion 159 1586
Split packet!
Packet split in portion 1256 330
SNI target detected
```

**Comment by Waujito** [comment]
To suppress warnings disable kyber in chrome://flags
Also you can try to disable quic in chrome://flags

If nothing works, keep quic and kyber disabled and play around with arguments in the README.md
Say me if that helped.

**Comment by Igorbunow** [comment]
> To suppress warnings disable kyber in chrome://flags Also you can try to disable quic in chrome://flags
> 
> If nothing works, keep quic and kyber disabled and play around with arguments in the README.md Say me if that helped.

Thanks a lot! Now warning suppressed!

After experiment with settings, this:

`./youtubeUnblock 537 --sni-domains=all --fake-sni=ttl`

 helps to make it works with crome and firefox. But in stube on adroid TV it isn't working

**Comment by Waujito** [comment]
Good news! Android TV may use QUIC. You can block it by `iptables -t filter -A FORWARD -p udp --dport 443 -j DROP`

**Comment by Igorbunow** [comment]
> Good news! Android TV may use QUIC. You can block it by `iptables -t filter -A FORWARD -p udp --dport 443 -j DROP`

Thanks!
It helps to make it works with standart youtube client from Google Play, other client such as sTube not works. Thanks a lot! Now I can connect this board beetween internet provider provider and router and watch youtube on all home devices!

The result full gateway settings are:

```
sysctl -w net.ipv4.ip_forward=1
iptables -I OUTPUT -m mark --mark 32768/32768 -j ACCEPT
#iptables -A OUTPUT -p tcp --dport 443 -j NFQUEUE --queue-num 537 --queue-bypass
iptables -t mangle -A FORWARD -p tcp -m tcp --dport 443 -m connbytes --connbytes-dir original --connbytes-mode packets --connbytes 0:19 -j NFQUEUE -->
iptables -t filter -A FORWARD -p udp --dport 443 -j DROP
iptables -A FORWARD -i eth0 -o eth1 -j ACCEPT
iptables -A FORWARD -i eth1 -o eth0 -j ACCEPT
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
/bin/youtubeUnblock 537 --sni-domains=all --fake-sni=ttl
```

Maybe it'll be helpfull for anyone. So in free time, I try to find minimal kernel config, for this I turn on NFQUEUE and connbytes into Networking support->Networking options->Network packet filtering framework (Netfilter)->Core Netfilter Configuration->Netfilter Xtables support

Build utility string is:

before build:

```
export PATH=TOOLCHAIN_PATH:$PATH
export ARCH=arm
export CROSS_COMPILE=arm-buildroot-linux-gnueabihf-
export CROSS_NAME=arm-buildroot-linux-gnueabihf
```



`STAGING_DIR=temp make CC=arm-buildroot-linux-gnueabihf-gcc LD=arm-buildroot-linux-gnueabihf-ld AR=arm-buildroot-linux-gnueabihf-ar OBJDUMP=arm-buildroot-linux-gnueabihf-objdump NM=arm-buildroot-linux-gnueabihf-nm STRIP=arm-buildroot-linux-gnueabihf-objcopy CROSS_COMPILE_PLATFORM=arm-buildroot-linux-gnueabihf`

**Comment by Waujito** [comment]
So, if the problem solved, I am closing the issue. For Android TV check #59 (still in progress)
