### ISSUE TITLE
Which build should i use for OpenWRT?

### ISSUE THREAD

**Issue by andrrrw** [Waujito/youtubeUnblock#54]
![image](https://github.com/user-attachments/assets/69d915f5-a565-4859-86c4-5b1d3632c137)
there no issue
just little misunderstanding
On my router i have cpu with `MIPS 1004Kc` architecture
which build i can use from [there](https://github.com/Waujito/youtubeUnblock/actions/runs/10333533908) or how i build it myself for my router?

**Comment by Waujito** [comment]
Your binaries will be `ramips-mt7621`. I have added it.

**Comment by andrrrw** [comment]
Думаю, стоит дополнить информацию в readme

> root@router:~# grep ARCH /etc/openwrt_release 
> DISTRIB_ARCH='mipsel_24kc'

**Comment by boozzze** [comment]
Model | Xiaomi AX3600
-- | --
Architecture | ARMv8 Processor rev 4
Target Platform | ipq807x/generic
Firmware Version | OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-23.236.53405-fc638c8


привет, подскажите, пожалуйста, Какой пакет взять?
