### ISSUE TITLE
ramips-mt76x8-openwrt-23.05 не запускается

### ISSUE THREAD

**Issue by mrOkk** [Waujito/youtubeUnblock#56]
Я не уверен, но выглядит странно, что в архиве бинарь как будто от другой архитекктуры (mipsel_24kc)
Попробовал поставить на роутер разные вариант и они вроде ставятся, но не запускаются

**Comment by Waujito** [comment]
> Я не уверен, но выглядит странно, что в архиве бинарь как будто от другой архитекктуры (mipsel_24kc) Попробовал поставить на роутер разные вариант и они вроде ставятся, но не запускаются

ramips-mt76x8 и mipsel_24kc это практически одно и то же https://github.com/Waujito/youtubeUnblock/issues/54#issuecomment-2282490807 

https://openwrt.org/docs/techref/instructionset/mipsel_24kc

Несмотря на эту особенность, сборка происходит с SDK для ramips-mt76x8. Какая именно проблема возникла с бинарником?

**Comment by Waujito** [comment]
Хм, общаюсь сейчас с еще одним человеком с такой же жалобой. Можете точно сказать, что происходит?

Это странно, потому что у меня точно такая же архитектура и с ней всё работает

**Comment by mrOkk** [comment]
На всякий случай для полноты картины скажу, что роутер старенький TP-Link TL-WR850N v1. Вдруг чем-то поможет.
Происходит следующее: при установке выдается сообщение
"Installing youtubeUnblock (05648cc7-1) to root...
Configuring youtubeUnblock."

далее перехожу в Startup, вижу в списке youtubeUnblock, на start/restart никакой реакции, а на enable выдается сообщение "Failed to execute "/etc/init.d/youtubeUnblock enable" action: Command failed".

**Comment by Waujito** [comment]
Зависимости не установили. Они описаны в ридми.

**Comment by zabbius** [comment]
Есть предложение зависимости в ipk прописать, чтобы оно тупо без них не ставилось (если конечно до сих пор не сделано).

**Comment by Waujito** [comment]
> Есть предложение зависимости в ipk прописать, чтобы оно тупо без них не ставилось (если конечно до сих пор не сделано).

Если бы всё было так просто. На старых версиях openwrt стоит iptables, на новых nftables. Если я поставлю зависимости nftables, то не будут работать старые версии. Если поставлю зависимости iptables, я на nftables буду тянуть кучу пакетов iptables. К тому же, зависимости типа kmod в разы увеличивают build time. 

Возможно, у @spvkgn есть идеи как это исправить.

**Comment by andrrrw** [comment]
> Зависимости не установили. Они описаны в ридми.

Установили. У меня nftables стояли по умолчанию.
Установил:
1. `kmod-nft-queue`
2. `kmod-nf-conntrack`
Бинарник не стартует. Выдает ту же ошибку

> "Failed to execute "/etc/init.d/youtubeUnblock enable" action: Command failed".

**Comment by Waujito** [comment]
> "Failed to execute "/etc/init.d/youtubeUnblock enable" action: Command failed".

А что скажет `/usr/bin/youtubeUnblock`?

**Comment by andrrrw** [comment]
> А что скажет `/usr/bin/youtubeUnblock`?

Стандартный вывод
![image](https://github.com/user-attachments/assets/9a6b2bdb-3311-4438-aad2-72df9619d1ca)

**Comment by Waujito** [comment]
Установите программу из релиза: https://github.com/Waujito/youtubeUnblock/releases/tag/v0.3.0

**Comment by andrrrw** [comment]
> (или последнюю версию из Actions)
Установил новую версию
теперь бинарник запускается
ютуб ожил
но openwrt не дает включить initscript
![image](https://github.com/user-attachments/assets/9dd6bab9-58c9-43c0-8654-7d856c7a4086)

**Comment by Waujito** [comment]
Operation not permitted
Случается если пытаться запустить два инстанса youtubeUnblock одновременно с одним и тем же значение номера netfilter queue (по умолчанию 537)

Возможно, knit скрипт уже работает. Тогда необходимо его остановить /etc/init.d/youtubeUnblock stop

**Comment by andrrrw** [comment]
Как выяснилось init-скрипт успешно стартует из панели openwrt
просто он выдает почему-то сообщение об ошибке, но сам сервис запускается

**Comment by Waujito** [comment]
А если этот init-скрипт попробовать? https://github.com/Waujito/youtubeUnblock/blob/main/owrt/youtubeUnblock.owrt

**Comment by andrrrw** [comment]
> А если этот init-скрипт попробовать? https://github.com/Waujito/youtubeUnblock/blob/main/owrt/youtubeUnblock.owrt

Ошибка пропала.
OpenWrt больше не ругается

**Comment by vgicksm** [comment]
> А если этот init-скрипт попробовать? https://github.com/Waujito/youtubeUnblock/blob/main/owrt/youtubeUnblock.owrt

А как его "попробовать" на бытовом языке?

**Comment by Waujito** [comment]
> А как его "попробовать" на бытовом языке?

Уже можно загрузить пакет с фиксом отсюда: https://github.com/Waujito/youtubeUnblock/actions/runs/10373649686

**Comment by boozzze** [comment]
привет, подскажите, Какой пакет выбрать

<html><body>
<markdown-accessiblity-table data-catalyst="">
Model | Xiaomi AX3600
-- | --
Architecture | ARMv8 Processor rev 4
Target Platform | ipq807x/generic
Firmware Version | OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-23.236.53405-fc638c8

</markdown-accessiblity-table>
<p dir="auto">привет, подскажите, пожалуйста, Какой пакет взять?</p>
</body>
</html>

**Comment by boozzze** [comment]
> > привет, подскажите, Какой пакет выбрать
> > Model	Xiaomi AX3600
> > Architecture	ARMv8 Processor rev 4
> > Target Platform	ipq807x/generic
> > Firmware Version	OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-23.236.53405-fc638c8
> 
> Что то мне подсказывает, что этот должен завестись https://github.com/Waujito/youtubeUnblock/releases/download/v0.3.0/armsr-armv8-openwrt-23.05.zip

![изображение](https://github.com/user-attachments/assets/ca8ee189-e92f-425b-afa1-9d8b92f86d29)
видимо нет*(

**Comment by Waujito** [comment]
@boozzze пробуйте https://github.com/Waujito/youtubeUnblock/actions/runs/10385027359/artifacts/1810577695

**Comment by mrOkk** [comment]
На всякий случай напишу, что по моей проблеме все решено. Большое спасибо разрабам и @andrrrw, что продвинул тему.

**Comment by Waujito** [comment]
> Судя по именам пакетов на сайте [OpenWrt](https://downloads.openwrt.org/snapshots/targets/ipq807x/generic/packages/), нужен aarch64_cortex-a53

Опять я добавил уже существующую "архитектуру") Тогда затрём твоим PRом)

**Comment by mrOkk** [comment]
Еще вопрос, может есть какие-то подобные кейсы. На пк и смартфоне ютуб летает, а вот на телике - не запускается с ошибкой сети (Samsung - Tizen). Судя по всему нужно как-то пошатать nftables, но не представляю, как именно

**Comment by boozzze** [comment]
> Еще вопрос, может есть какие-то подобные кейсы. На пк и смартфоне ютуб летает, а вот на телике - не запускается с ошибкой сети (Samsung - Tizen). Судя по всему нужно как-то пошатать nftables, но не представляю, как именно

у меня тоже завелось, Комп, моб, А вот телик LG - Ошибка - проверьте подключение к сети...

**Comment by boozzze** [comment]
> @boozzze пробуйте https://github.com/Waujito/youtubeUnblock/actions/runs/10385027359/artifacts/1810577695

завелось!) Спасибище!

**Comment by Waujito** [comment]
Да, известная проблема. Подробнее в #59 (в последних сообщениях)

**Comment by Waujito** [comment]
Закрываю, потому что главная проблема решена. Далее следите за #59 по вопросам tv
