### ISSUE TITLE
OpenWrt compilation issue

### ISSUE THREAD

**Issue by spvkgn** [Waujito/youtubeUnblock#6]
Пробую собрать для x86_64, ошибка при сборке - [compile.zip](https://github.com/user-attachments/files/16437867/compile.zip)

**Comment by Waujito** [comment]
Скорее всего, проблема в том, что у меня CCLD называется LD, что может приводить к путанице. В значение LD мэйка необходимо передавать gcc (см. пример).

**Comment by luckydevil13** [comment]
no issue with openwrt compilation (tested on filogic taget)

**Comment by Waujito** [comment]
> no issue with openwrt compilation (tested on filogic taget) (via readme)

Hello! First link in google about filogic stays that it has 4 CPU cores. Can you please tell me how much your device has and how youtubeUnblock impacts the network speed and CPU usage? It _may_ because of tons of context switchs between the kernel and the userspace. For my 1 core model the speed is awful.

**Comment by Waujito** [comment]
> > Скорее всего, проблема в том, что у меня CCLD называется LD, что может приводить к путанице. Возможно, в значении LD мэйка необходимо передать gcc (см. пример).
> 
> Попробовал с патчем из #8, другая ошибка [compile.txt](https://github.com/user-attachments/files/16450762/compile.txt)
> 
> ```
> CCLD /builder/build_dir/target-x86_64_musl/youtubeUnblock-main/build/youtubeUnblock
> /usr/bin/ld: /builder/build_dir/target-x86_64_musl/youtubeUnblock-main/build/youtubeUnblock.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /builder/build_dir/target-x86_64_musl/youtubeUnblock-main/build/deps/lib/libmnl.a(socket.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /builder/build_dir/target-x86_64_musl/youtubeUnblock-main/build/deps/lib/libmnl.a(callback.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /builder/build_dir/target-x86_64_musl/youtubeUnblock-main/build/deps/lib/libmnl.a(nlmsg.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /builder/build_dir/target-x86_64_musl/youtubeUnblock-main/build/deps/lib/libmnl.a(attr.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /builder/build_dir/target-x86_64_musl/youtubeUnblock-main/build/deps/lib/libnetfilter_queue.a(nlmsg.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /builder/build_dir/target-x86_64_musl/youtubeUnblock-main/build/deps/lib/libnetfilter_queue.a(tcp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /builder/build_dir/target-x86_64_musl/youtubeUnblock-main/build/deps/lib/libnetfilter_queue.a(ipv4.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /builder/build_dir/target-x86_64_musl/youtubeUnblock-main/build/deps/lib/libnetfilter_queue.a(udp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /builder/build_dir/target-x86_64_musl/youtubeUnblock-main/build/deps/lib/libnetfilter_queue.a(ipv6.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
> collect2: error: ld returned 1 exit status
> ```

Тот патч требовал, чтобы CCLD был передан специально, отдельно от CC. Исправил, теперь должно работать (с предыдущей командой). 

Если дальше будут проблемы, вместе с логами сборки передавайте еще и команду.

**Comment by luckydevil13** [comment]
> Can you please tell me how much your device has and how youtubeUnblock impacts the network speed and CPU usage?

+3-5% CPU (AVG)

**Comment by Waujito** [comment]
> +3-5% CPU (AVG)

That's perfect!

**Comment by Waujito** [comment]
The issue seems resolved, so I will close it and commit #8 If you have any related issues further, please reopen this one.
