### ISSUE TITLE
[since 0.3.0] performance degradation after a couple of successful hits

### ISSUE THREAD

**Issue by irulanCorrino** [Waujito/youtubeUnblock#61]
i already mentioned this in my comment https://github.com/Waujito/youtubeUnblock/issues/44#issuecomment-2276948409 which issue was closed because the issue was about a regression and after proper patching from Waujito the unblocker is definitely working;  
i have performance issues that are somewhat similar to what is described in #52 but i do not have "No Internet" warning:
> If i stop youtubeUnblock, waits for loading page and then run
> `youtubeUnblock 537 --sni-domains=all --fake-sni-ttl=6 --fake-sni=ttl`
> All works fine, till close page or application.

but now i have found something significant i guess, a clue to my performance issues i mention before closing that thread https://github.com/Waujito/youtubeUnblock/issues/44#issuecomment-2276948409  
I SEE app reporting (`SNI target detected 0 -157516579 -2135231887 ...`) the target if i close firefox [after stopping youtube video], do `ctrl+c` to the unblocker, then START the unblocker again WITHOUT firefox!!!  
<ins>so i still have some stream at the background!</ins>  
i can even repeat `ctrl+c`+`START` cycle a couple of times before i see there is no stream remaining from that previous youtube session.

p.s.: and firefox on other sites had become NOTORIOUSLY slow to load the content last days [russian online stores: if i have active tabs with `Wildberries` in them then another tab with `Ozon` lags just insanely, but without `WB` it is fast (both marketplaces run hell a lot of scripts, and they both have had major updates recently)].

**Comment by Waujito** [comment]
First of all, update the program to version 0.3.0

Second, in #44 I see that you are using iptables rule without connbytes which may lead to degraded performance.

**Comment by irulanCorrino** [comment]
> First of all, update the program to version 0.3.0

<ins>thanks</ins>, missed a new release (and sorry for such lag with a response)

> Second, in #44 I see that you are using iptables rule without connbytes which may lead to degraded performance. Read the README

<ins>yes, you have solved</ins> the issue with `the stream left opened at background`;  
but i still have performance degradation after a couple of decently played videos,  
AND, idk if it is related, but a long video like [this](https://www.youtube.com/watch?v=yDZIUFiIgHM) is cut at 10th minute, watching it i have had  
`temporary failure with a name resolution` (i'd checked my distro's server with `ping`),  
but my ISP is notorious for poisoning/screwing up DNS ...i could test it with wireshark if  
it would diagnose the poisoning attack, just guide me through this, i am quiet slow  
with learning security/network protocols [it was not my field, before this i was a UI designer].  

before switching to your app, while trying to install VPNs (complete failure), i tried  
to enable DoH/DoT in firefox but to no avail (i repeat, i am a newbie on security issues)  
then i have found this article: [Avoiding Tunnel Vision on Linux | Pro Custodibus](https://www.procustodibus.com/blog/2024/05/avoid-tunnelvision-on-linux/)  
and even though i have not succeeded with my VPN attempts i had had a feeling that my ISP  
abuses DNS or maybe tempers with DHCP (idk if it is possible if i am connected to them via  
a router, the article is about <ins>local network's vulnerability</ins>).

p.s.: nothing is reachable if i try DoH, and also disabling network.http.http{2,3}.enable(d) в about:config в Firefox does not change anything in regards to your app's performance

**Comment by irulanCorrino** [comment]
summary for https://github.com/Waujito/youtubeUnblock/issues/61#issuecomment-2288647790
> long video like [this](https://www.youtube.com/watch?v=yDZIUFiIgHM) is cut at 10th minute, watching it i have had
`temporary failure with a name resolution` (i'd checked my distro's server with ping)[...] 

- mostly that was irrelevant to SPTU or `youtubeUnblock` but a side effect of a firewall working, which has screwed up the connection to my distro's server (but did not cut that long video)

> @Waujito Second, in https://github.com/Waujito/youtubeUnblock/issues/44 I see that you are using iptables rule without connbytes which may lead to degraded performance. Read the README

- that is a working advice

> @Waujito First of all, update the program to version 0.3.0
@irulanCorrino thanks, missed a new release (and sorry for such lag with a response)
- at that moment i was using `youtubeUnblock-0.2.1-2` and then i did like @Waujito had said
- #61 was opened after that update
- since then i had found #72 and did like in https://github.com/Waujito/youtubeUnblock/issues/72#issuecomment-2293192856
- it has solved everything [with a correct firewall rule]

conclusion: `youtubeUnblock-0.2.1-2` was broken, `youtubeUnblock-0.3.0` was screwed up; <ins>`youtubeUnblock-0.2.2` is fine NO ISSUES, sometimes i do not pause videos at beginning, it still works [but i prefer to pause to be confident it will be loaded]</ins>
