### ISSUE TITLE
FORWARD rule do not work

### ISSUE THREAD

**Issue by sk011** [Waujito/youtubeUnblock#67]
> PC configuration
> On local host make sure to change FORWARD to OUTPUT chain in the Firewall rulesets.

For localhost all wook goods. Forward packets don't fragment
ubuntu 22.04
net.ipv4.ip_forward=1 enable

I try insert rule for all mangle CHAINS. It doesn't help
In tcpdump `Flags [P.], seq 0:517`   from localhost `Flags [P.], seq 170:518, Flags [P.], seq 3:170, Flags [P.], seq 1:3,`

**Comment by Waujito** [comment]
> On local host make sure to change FORWARD to OUTPUT chain in the Firewall rulesets.

That line means that if you are running the local machine, you should use OUTPUT chain instead of FORWARD

**Comment by sk011** [comment]
Yes, i undesstand. On local machine (router) all work
I need FORWARD packets, iptables rule in -t mangle dont work or youtubeUnblock bin dont work
-A FORWARD -p tcp -m tcp --dport 443 -m connbytes --connbytes 0:19 --connbytes-mode packets --connbytes-dir original -j NFQUEUE --queue-num 537 --queue-bypass

In my case NAT unused, localnetwork machines have real IP
Maybe that's the reason

**Comment by Waujito** [comment]
On router you should you FORWARD chain, on host you should use OUTPUT. NAT is not a problem. Playaround with configs unless you got `target detected` logs from youtubeUnblock. Try to start it with `/usr/bin/youtubeUnblock --sni-domains=all`. If you got mnl_cb_start Operation not permitted do `/etc/inti.d/youtubeUnblock stop`

**Comment by sk011** [comment]
It doesn't help
In the local version, all right i see in debug Target SNI detected: .... Packet split in portion .....
In the forward version, dont work and no debug messages in console
Maybe need sysctl options except net.ipv4.ip_forward=1

**Comment by Waujito** [comment]
Можете на русском описать проблему?

**Comment by sk011** [comment]
Пакеты, которые проходят через таблицу mangle цепочка FORWARD не обрабатываются. 
На сервере два одинаковых правила
```
-A FORWARD  -p tcp -m tcp --dport 443 -m connbytes --connbytes 0:19 --connbytes-mode packets --connbytes-dir original -j NFQUEUE --queue-num 537 --queue-bypass
-A OUTPUT -p tcp -m tcp --dport 443 -m connbytes --connbytes 0:19 --connbytes-mode packets --connbytes-dir original -j NFQUEUE --queue-num 537 --queue-bypass

```
при локальной проверке curl или youtube-dl все отлично, в логе видно что распознан SNI доступ есть
при проверке с локальной сети по счетчикам iptables видно что пакет попадает в правило, но при этом утилита не распознает SNI в пакете. NAT на сервере не используется! Локальный клиент с реальным IP адресом

На сервере tcpdump видно что пакет от локальной машины уходит в внешний интерфейс, т.е. маршрутизация верная 
forward в sysctl включен 

> Try to start it with /usr/bin/youtubeUnblock --sni-domains=all

Пробовал разные варианты, результат один

**Comment by Waujito** [comment]
А это точно mangle? Что если попробовать 
```
iptables -t mangle -I FORWARD -p tcp -m tcp --dport 443 -m connbytes --connbytes 0:19 --connbytes-mode packets --connbytes-dir original -j NFQUEUE --queue-num 537 --queue-bypass
```

**Comment by sk011** [comment]
точно mangle

```
iptables -L -n -v -t mangle
Chain PREROUTING (policy ACCEPT 6013 packets, 1133K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 2589 packets, 482K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 582 packets, 127K bytes)
 pkts bytes target     prot opt in     out     source               destination         
   89 16683 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 connbytes 0:19 connbytes mode packets connbytes direction original NFQUEUE num 537 bypass

Chain OUTPUT (policy ACCEPT 2166 packets, 267K bytes)
 pkts bytes target     prot opt in     out     source               destination         
  175 38340 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 connbytes 0:19 connbytes mode packets connbytes direction original NFQUEUE num 537 bypass

Chain POSTROUTING (policy ACCEPT 2986 packets, 434K bytes)
 pkts bytes target     prot opt in     out     source               destination         

```

**Comment by sk011** [comment]
Как только включаю NAT правило на внешнем интерфейсе, локальный клиент начинает работать
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
Что то с цепочкой по которой проходит forward пакет, утилита не видит его или что то с NFQUEUE 
Не могу понять

**Comment by sk011** [comment]
```
       --connbytes-dir {original|reply|both}
	      which packets to consider

```
разобрался, при локальной проверке и при работе с NAT пакет проходящий через правила считается original 
forward пакет считается **both**
@Waujito спасибо, что откликнулись!

**Comment by sk011** [comment]
Поспешил ((( забыл убрать правило NAT из таблицы 
ситуация такая же

**Comment by sk011** [comment]
если сократить правило до 
`-A FORWARD -p tcp -m tcp --dport 443 -j NFQUEUE --queue-num 537 --queue-bypass`
работает

**Comment by Waujito** [comment]
Значит conntrack отключен

**Comment by sk011** [comment]
вроде все есть

```
lsmod | grep conn
xt_connbytes           16384  1
nf_conntrack          172032  2 nf_nat,xt_connbytes
nf_defrag_ipv6         24576  1 nf_conntrack
nf_defrag_ipv4         16384  1 nf_conntrack
x_tables               53248  5 nft_compat,xt_tcpudp,ip_tables,xt_NFQUEUE,xt_connbytes
libcrc32c              16384  5 nf_conntrack,nf_nat,btrfs,nf_tables,raid456
```

**Comment by Waujito** [comment]
What `cat /proc/net/nf_conntrack` returns?

**Comment by sk011** [comment]
> What `cat /proc/net/nf_conntrack` returns?

ubuntu 22/04 не сконфигурирован параметр `CONFIG_NF_CONNTRACK_PROCFS` 
/proc/net/nf_conntrack: No such file or directory

conntrack --count,  conntrack -L показывают информацию 
при любом правиле с  -m conntrack или -m connbytes попадает почему то только один пакет 
например, видно что в TRACE попало 6 пакетов в NFQUEUE 1 
```
Chain FORWARD
    6  1871 TRACE      tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443
    1    60 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 ctorigdst 8.7.169.160/27 NFQUEUE num 537 bypass

```
если такие же правила сделать но в Chain OUTPUT, все отлично, счетчики правил совпадают
