### ISSUE TITLE
 ip4_payload_split

### ISSUE THREAD

**Issue by Qel-Droma** [Waujito/youtubeUnblock#68]
Собрал v0.3.0 без варнингов - youtubeUnblock_0.3.0-1_aarch64_cortex-a53.ipk
Redmi AX6S, OpenWrt 23.05.3 
Файрвол nft
Поставил пакет, установил зависимости, добавил правила, запустил
По логам такая картина: 
![Снимок экрана от 2024-08-14 21-25-31](https://github.com/user-attachments/assets/85de948b-35e9-4a87-a8f4-365593ce85a9)

Сразу уточню: я обычный пользователь. С OpenWrt работаю впервые.

**Comment by bvasiliev** [comment]
Похоже, соединения по IPv6, которые youtubeUnblock не поддерживает.

https://github.com/Waujito/youtubeUnblock/blob/460f392a91f6637fcd87c610f41ac3799a56347f/mangle.c#L368

**Comment by Waujito** [comment]
Да, так и есть. С ipv6 не работает. Его поддержка запрошена в #27. Что можно сделать сейчас - отключить ipv6 на роутере

**Comment by Qel-Droma** [comment]
Отключил ipv6 и теперь ютуб летает
Спасибо!

**Comment by Waujito** [comment]
Hello! Can you test out #93 with ipv6 support? Binaries are available here: https://github.com/Waujito/youtubeUnblock/actions/runs/10582327899
