### ISSUE TITLE
C ipk все нормально в версии 0.3.0

### ISSUE THREAD

**Issue by Chuguevskiy** [Waujito/youtubeUnblock#69]
Привет! Я собственно к чему. Хотел сначала на виртуалке OpenWRT x86/64 опробовать а потом уже на роутер натянуть.
так вот беру ipk под x86 скармливаю пакет - ругань на архитектуру. ладно думаю сразу попробую поставить на роутер. Выбираю свой ipk aarch64_generic-openwrt-23.05 под свою железку (MediaTek MT7986/Filogic 830/ARMv8 Processor rev 4).
Скармливаю пакет - снова ругань на архитектуру. В итогге пришлось просто распаковать и раскидать все куда нужно, права на выполнение и все взлетело и работает прям радость!
Но вот сами ipk не съедобны почему то.
Главное работает - спасибо за труды.

**Comment by Waujito** [comment]
x86 != x86_64 :) Используйте x64

Для своего роутера попробуйте aarch64_cortex-a53

**Comment by Chuguevskiy** [comment]
aarch64_generic-openwrt-23.05 - этот нормально работает(распакованный) Я просто подумал может c самим ipk что не так. Все работает, все отлично просто не скармливается в виде пакета. Спасибо.

**Comment by Waujito** [comment]
Если всё работает - закрываю.
