### ISSUE TITLE
systemd start-stop

### ISSUE THREAD

**Issue by ivan1986** [Waujito/youtubeUnblock#7]
Здравствуйте,
Немного доработал systemd unit - пусть сам iptables конфигурит - ExecStartPre и ExecStop

```
[Unit]
Description=youtubeUnblock

[Service]
StandardError=journal
StandardOutput=journal
StandardInput=null
ExecStartPre=iptables -A OUTPUT -p tcp --dport 443 -j NFQUEUE --queue-num 537 --queue-bypass
ExecStart=$(PREFIX)/bin/youtubeUnblock 537
ExecStop=iptables -D OUTPUT -p tcp --dport 443 -j NFQUEUE --queue-num 537 --queue-bypass

[Install]
WantedBy=multi-user.target
```

спасибо за это решение, а то у меня как-то странно отрубается http3 в хроме при включении рабочего vpn который в наши подсети роутит.

**Comment by Waujito** [comment]
Добрый день!
Спасибо за фидбек! Думаю, действительно стоит добавить автоконфигурацию. Другой кейс - если iptables нет в системе, а вместо него используется nftables. Но тут я просто написал в ридми, что придётся самостоятельно настроить.

**Comment by Waujito** [comment]
В общем, вроде как всё работает. Думаю, можно закрыть это. Если будут еще какие-то предложения - пишите.
