### ISSUE TITLE
AndroidTV отказывается работать

### ISSUE THREAD

**Issue by myx0m00000p** [Waujito/youtubeUnblock#70]
Установил на роутер под опенврт. Работает отлично, спасибо большое. Но все же основная цель была починить Ютуб на ТВ приставке. В приложении на приставке ошибка "нет сети". При этом на ней же через браузер всё работает. С флагами немного экспериментировал, не сработало. Планируется ли какое-то решение?

**Comment by Waujito** [comment]
ТВ - зло :) Обсуждение в #59

**Comment by myx0m00000p** [comment]
> ТВ - зло :) Обсуждение в #59

Правда, но всё же бабушка очень хочет чтобы у неё починился Ютуб

**Comment by myx0m00000p** [comment]
с флагами --faking-strategy=ttl --faking-ttl=6 --frag-sni-faked=1 всё заработало
