### ISSUE TITLE
Connection reset by peer, no internet connection in 0.3.0

### ISSUE THREAD

**Issue by SergejVolkov** [Waujito/youtubeUnblock#72]
0.3.0 release does not work at all for me. It detects packets, reports successful splitting, then connection dies. Tried everything:ttl, disabled quic and kyber, sni domains in all combinations, different browsers and curl test. Release 0.2.2 works without issues with default configuration, kyber and quic enabled in chromium (in fact, it does not work without kyber).
![Screenshot_2024-08-15_17-32-55](https://github.com/user-attachments/assets/ad51cd7d-3ee6-4387-a147-c3111528ad84)

**Comment by Waujito** [comment]
try --frag=none or --frag=ip

**Comment by Waujito** [comment]
So, I know about the problem. It was discussed in #43 and suddenly author's ISP falled back to the normal behavior. I see you are on linux so if you want to dig deeper in this problem we can run OpenVPN server for me to connect over your IP. Find me in telegram with https://t.me/waujito

and... Right now, at this moment v0.2.2 works but v0.3.0 does not?

**Comment by Waujito** [comment]
Hello! I have added compatibility with 0.2.2.
https://github.com/Waujito/youtubeUnblock/actions/runs/10431361822
You will need to pass `--frag-middle-sni=1 --frag-sni-pos=0` to fully imitiate v0.2.2 behavior. Can you please tell me if that works.
