### ISSUE TITLE
[OpenWrt] Is it safe to use `/etc/rc.local` for autostart?

### ISSUE THREAD

**Issue by proninyaroslav** [Waujito/youtubeUnblock#73]
The documentation mentions that forcing the daemon into autostart using initd is not recommended, as it can block the router (due to a possible bug in the package). It may be safe to set a delay for app execution in the  `/etc/rc.local`  (for example, 2-3 minutes after launch)? During this time, you can successfully connect via ssh.

**Comment by Waujito** [comment]
I should probaby delete that line. As long as you use only forward hook you are safe. If you pass it to output chain, here is a tiny that if you got a bug, you may lose access to your router. In that case simple configuration reset should help.
