### ISSUE TITLE
Client Hello packet is too big

### ISSUE THREAD

**Issue by TheBugurtov** [Waujito/youtubeUnblock#75]
Не работает - в логах ошибки:

Sun Aug 18 10:35:07 2024 daemon.info youtubeUnblock[7345]: Target SNI detected: www.youtube.com
Sun Aug 18 10:35:07 2024 daemon.info youtubeUnblock[7345]: WARNING! Client Hello packet is too big and may cause issues!
Sun Aug 18 10:35:07 2024 daemon.info youtubeUnblock[7345]: Packet split in portion 2 2274
Sun Aug 18 10:35:07 2024 daemon.info youtubeUnblock[7345]: Packet split in portion 141 2133
Sun Aug 18 10:35:07 2024 daemon.info youtubeUnblock[7345]: Split packet!
Sun Aug 18 10:35:07 2024 daemon.info youtubeUnblock[7345]: Packet split in portion 1256 877
Sun Aug 18 10:36:34 2024 daemon.info youtubeUnblock[7345]: Target SNI detected: play.google.com
Sun Aug 18 10:36:34 2024 daemon.info youtubeUnblock[7345]: WARNING! Client Hello packet is too big and may cause issues!
Sun Aug 18 10:36:34 2024 daemon.info youtubeUnblock[7345]: Packet split in portion 2 1755
Sun Aug 18 10:36:34 2024 daemon.info youtubeUnblock[7345]: Packet split in portion 132 1623
Sun Aug 18 10:36:34 2024 daemon.info youtubeUnblock[7345]: Split packet!
Sun Aug 18 10:36:34 2024 daemon.info youtubeUnblock[7345]: Packet split in portion 1256 367
Sun Aug 18 10:37:38 2024 daemon.info youtubeUnblock[7345]: Target SNI detected: yt3.ggpht.com
Sun Aug 18 10:37:38 2024 daemon.info youtubeUnblock[7345]: WARNING! Client Hello packet is too big and may cause issues!
Sun Aug 18 10:37:38 2024 daemon.info youtubeUnblock[7345]: Packet split in portion 2 1817
Sun Aug 18 10:37:38 2024 daemon.info youtubeUnblock[7345]: Packet split in portion 436 1381
Sun Aug 18 10:37:38 2024 daemon.info youtubeUnblock[7345]: Split packet!
Sun Aug 18 10:37:38 2024 daemon.info youtubeUnblock[7345]: Packet split in portion 1256 125
Sun Aug 18 10:37:48 2024 daemon.info youtubeUnblock[7345]: Target SNI detected: yt3.ggpht.com
Sun Aug 18 10:37:48 2024 daemon.info youtubeUnblock[7345]: WARNING! Client Hello packet is too big and may cause issues!
Sun Aug 18 10:37:48 2024 daemon.info youtubeUnblock[7345]: Packet split in portion 2 1817
Sun Aug 18 10:37:48 2024 daemon.info youtubeUnblock[7345]: Packet split in portion 509 1308

**Comment by Waujito** [comment]
Это не ошибки. Смотрите troubleshooting в readme и играйте с флагами. Можете посмотреть другие issues для поиска решения
