### ISSUE TITLE
Проблема с фиксингом скорости для Youtube

### ISSUE THREAD

**Issue by h4ckee** [Waujito/youtubeUnblock#76]
Привет.
Пробую на тарифе для роутеров от Мегафона (роутер ramips/mt7621), с дефолтными настройками и так-же игрался с разными флагами, но никак не получается поднять скорость. Провайдер заметно тормозит Youtube  в отличии от того-же Rutube.
Вот тесты скоростей:

> x@dell:/home/x/Downloads$ curl -o/dev/null -k --connect-to ::google.com -k -L -H Host:\ mirror.gcr.io https://test.googlevideo.com/v2/cimg/android/blobs/sha256:6fd8bdac3da660bde7bd0b6f2b6a46e1b686afb74b9a4614def32532b73f5eaa
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1144  100  1144    0     0   1111      0  0:00:01  0:00:01 --:--:--  1111
>   0  664M    0  588k    0     0  70708      0  2:44:15  0:00:08  2:44:07 52603^C
> x@dell:/home/x/Downloads$ curl -o/dev/null -k --connect-to ::google.com -k -L -H Host:\ mirror.gcr.io https://test.googlevideo.com/v2/cimg/android/blobs/sha256:6fd8bdac3da660bde7bd0b6f2b6a46e1b686afb74b9a4614def32532b73f5eaa
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1144  100  1144    0     0    986      0  0:00:01  0:00:01 --:--:--   987
>   0  664M    0  540k    0     0  56563      0  3:25:19  0:00:09  3:25:10 17711^C
> x@dell:/home/x/Downloads$ curl -o/dev/null -k --connect-to ::google.com -k -L -H Host:\ mirror.gcr.io https://test.googlevideo.com/v2/cimg/android/blobs/sha256:6fd8bdac3da660bde7bd0b6f2b6a46e1b686afb74b9a4614def32532b73f5eaa
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1144  100  1144    0     0    909      0  0:00:01  0:00:01 --:--:--   909
>   0  664M    0 32012    0     0   3628      0 53:21:10  0:00:08 53:21:02     0^C

Тест обычной скорости:

> x@dell:/home/x/Downloads$ curl -o/dev/null -k --connect-to ::google.com -k -L -H Host:\ mirror.gcr.io https://mirror.gcr.io/v2/cimg/android/blobs/sha256:6fd8bdac3da660bde7bd0b6f2b6a46e1b686afb74b9a4614def32532b73f5eaa
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1144  100  1144    0     0    843      0  0:00:01  0:00:01 --:--:--   843
>  11  664M   11 78.3M    0     0  7545k      0  0:01:30  0:00:10  0:01:20  9.9M^C

Может кто подскажет куда копать?
Спасибо.

**Comment by Waujito** [comment]
Смотрите troubleshooting в readme и играйте с флагами. Можете посмотреть другие issues для возможных решений. На ветке Dev сейчас еще больше флагов, бинарники на ней доступны через GitHub actions.

**Comment by Waujito** [comment]
Попробуйте `/usr/bin/youtubeUnblock --frag-sni-faked=1 --frag-sni-pos=1 --faking-ttl=4 --fake-sni-seq-len=6 --faking-strategy=ttl` --faking-strategy стоит попробовать заменять на pastseq, tcp_check, ack.

**Comment by Waujito** [comment]
Пробовать надо на последнем релизе (v0.3.1)

**Comment by Waujito** [comment]
Да, смотрите через `grep ARCH /etc/openwrt_release`

**Comment by Waujito** [comment]
Да название поменять забыл)
