### ISSUE TITLE
Не хочет работать при подключении по Ethernet

### ISSUE THREAD

**Issue by JeViCo** [Waujito/youtubeUnblock#77]
Способ работает на всех устройствах, подключенных по WiFi. На ПК из-под Windows по проводу полностью работать не хочет. Сам сайт открывается (браузер Librewolf), т.е. спокойно перемещаюсь по панели навигации, вижу превьюшки, аватарки и комментарии. Проблемы начинаются в самом плеере, будь то обычное видео или шортсы, или попытка запуска обоих во вложениях ВК. Везде в консоли одна и та же ошибка плюется:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://play.google.com/log?format=json&hasfast=true&authuser=0. (Reason: CORS request did not succeed). Status code: (null).
```
Попробовал на chromium - также. Что интересно, запустил Windows Sandbox, накатил туда свой браузер, и там все идеально работает. В подключениях показывает DHCP, возможно в этом дело.

По логам при подключении с ПК напрямую (не из-под песочницы), вроде как все нормально:
```
Sun Aug 18 12:55:34 2024 daemon.info youtubeUnblock[3084]: Target SNI detected: www.youtube.com
Sun Aug 18 12:55:34 2024 daemon.info youtubeUnblock[3084]: Packet split in portion 2 1227
Sun Aug 18 12:55:34 2024 daemon.info youtubeUnblock[3084]: Packet split in portion 130 1097
Sun Aug 18 12:55:35 2024 daemon.info youtubeUnblock[3084]: Target SNI detected: i.ytimg.com
Sun Aug 18 12:55:35 2024 daemon.info youtubeUnblock[3084]: Packet split in portion 2 657
Sun Aug 18 12:55:35 2024 daemon.info youtubeUnblock[3084]: Packet split in portion 128 529
Sun Aug 18 12:55:35 2024 daemon.info youtubeUnblock[3084]: Target SNI detected: fonts.googleapis.com
Sun Aug 18 12:55:35 2024 daemon.info youtubeUnblock[3084]: Packet split in portion 2 666
Sun Aug 18 12:55:35 2024 daemon.info youtubeUnblock[3084]: Packet split in portion 133 533
Sun Aug 18 12:55:38 2024 daemon.info youtubeUnblock[3084]: Target SNI detected: yt3.ggpht.com
Sun Aug 18 12:55:38 2024 daemon.info youtubeUnblock[3084]: Packet split in portion 2 659
Sun Aug 18 12:55:38 2024 daemon.info youtubeUnblock[3084]: Packet split in portion 129 530
Sun Aug 18 12:55:40 2024 daemon.info youtubeUnblock[3084]: Target SNI detected: accounts.youtube.com
Sun Aug 18 12:55:40 2024 daemon.info youtubeUnblock[3084]: Packet split in portion 2 1232
Sun Aug 18 12:55:40 2024 daemon.info youtubeUnblock[3084]: Packet split in portion 133 1099
Sun Aug 18 12:55:42 2024 daemon.info youtubeUnblock[3084]: Target SNI detected: rr5---sn-jvhnu5g-n8vk.googlevideo.com
Sun Aug 18 12:55:42 2024 daemon.info youtubeUnblock[3084]: Packet split in portion 2 683
Sun Aug 18 12:55:42 2024 daemon.info youtubeUnblock[3084]: Packet split in portion 141 542
```

**Comment by JeViCo** [comment]
@Waujito https://gist.github.com/JeViCo/7f8cc53830e640e5d912005bc7c84e93

**Comment by JeViCo** [comment]
Как и сказали выше, проблема не связана с настройкой. Нужно было почистить куки на всех сайтах, которые ранее с ютубом общались (в том числе вк), и всё заработало. Либо было временный глюк, тут уже не знаю. В любом случае, спасибо что ответили!

**Comment by Waujito** [comment]
Первый раз чистка куки хоть кому то помогла)) В целом, проблема может быть и в play.google.com, потому что он разблокировался

**Comment by JeViCo** [comment]
Похоже очистка куки имеет временный эффект. При закрытии вкладкок и повторном открытии, происходит отвал. Интересно то, что после смены темы темная/светлая и очистки куки видео снова начинают грузиться

**Comment by Waujito** [comment]
Что если попробовать запускать yoututbeUnblock с флагом `--sni-domains=all`?

**Comment by JeViCo** [comment]
Прописал флаг, не похоже что сильно помогает. Вот, кстати, что происходит во вкладке network, когда я открыл шортс. Он секунд через 30 решил запуститься, но при переключении на следующий снова та же шляпа
![image](https://github.com/user-attachments/assets/3744c47d-b429-4450-880f-07a835c98fe5)

**Comment by JeViCo** [comment]
Обновился до 0.3.1, перезагрузился, пока работает. Не могу уловить связь, еще понаблюдаю. Может кто-то еще с похожей проблемой появится

**Comment by Waujito** [comment]
Если всё работает - закрываю.

**Comment by soil7800** [comment]
Ровно такая же проблема, на последнем релизе [v1.0.0-rc1](https://github.com/Waujito/youtubeUnblock/releases/tag/v1.0.0-rc1) все устройства в сети по wifi работают отлично, Windows ПК по ethernet не работает.

**Comment by JeViCo** [comment]
@soil7800 В моем случае в браузерах всех надо было http2/http3/kyber отключить, в readme об этом сказано, легко пропустить. Попробуй еще предыдущий релиз

**Comment by soil7800** [comment]
@JeViCo отключен, работает отлично по wifi в любых браузерах + curl. По ethernet не работает даже curl в терминале.

**Comment by Waujito** [comment]
Нет никакой кастомной конфигурации которая может менять роутинг? Может  PBR, VPN, software/hardware offloading?

**Comment by Ser9ei** [comment]
@ Waujito подтверждаю, ваш сервис не работает с offloading, необходимо отключать offloading в настройках Firewall OpenWrt.
