### ISSUE TITLE
Не работает практически на всех телевизорах и приставках

### ISSUE THREAD

**Issue by jim2310** [Waujito/youtubeUnblock#80]
Доброго времени суток, огромное спасибо за ваш труд, в браузере и на телефоне Ютуб летает, но основная часть телевизоров и приставок не может загрузить приложение , причем если раздать интернет с телефона (на МТС пока проблем с Ютубом не замечено), приложение запускается и далее можно переходить на wifi, все работает прекрасно. Пробовал добавлять в параметр домен youtubei.googleapis.com:

`ExecStart=/usr/local/bin/youtubeUnblock --sni-domains=youtubei.googleapis.com,googlevideo.com,ggpht.com,ytimg.com,youtube.com,play.google.com,youtu.be,googleapis.com,googleusercontent.com,gstatic.com,l.google.com`

не подскажите куда копать?

![photo_2024-08-20_18-50-03](https://github.com/user-attachments/assets/8ead8181-a776-4d6c-8197-f296d1814557)
![photo_2024-08-20_18-50-10](https://github.com/user-attachments/assets/c11aa34a-a128-4aa7-9aec-dd93536e8339)

**Comment by jim2310** [comment]
Спасибо огромное, помогло!

**Comment by vgicksm** [comment]
> Спасибо огромное, помогло!

а что помогло то? что конкретно сделано?

**Comment by jim2310** [comment]
> > Спасибо огромное, помогло!
> 
> а что помогло то? что конкретно сделано?

 --faking-strategy=ttl --frag-sni-faked=1 --faking-ttl=5

**Comment by Waujito** [comment]
Если всё работает - закрываю.
