### ISSUE TITLE
SSL connect error 

### ISSUE THREAD

**Issue by eryepa** [Waujito/youtubeUnblock#81]
Привет! 
Youtube летает, большое спасибо! 
Собственно установил [youtubeUnblock](https://github.com/Waujito/youtubeUnblock) и по инструкции [dnscrypt-proxy2](https://openwrt.org/docs/guide-user/services/dns/dnscrypt_dnsmasq_dnscrypt-proxy2#troubleshooting)

Сначала обратил внимание что chrome во flatpak не обновляется, все остальные паки обновляются
![google ssl eroor](https://github.com/user-attachments/assets/071f2c3a-3960-4be5-8bf0-6253bc28bb60)

Вчера ко мне приехала новая читалка на андроиде, при попытке войти в гугл аккаунт: 
![google 404](https://github.com/user-attachments/assets/ef6a8c0f-195e-44e6-aad5-4623c52529b1)
Если использовать другую сеть - всё работает 

В логах openwrt ничего криминального
Как от траблшутить не знаю

**Comment by Waujito** [comment]
accounts.google.com не должен быть затронут youtubeUnblock. dl.google.com может быть. Но на настройках по умолчанию не должен. Попробуйте поиграть с флагами faking strategy.

**Comment by eryepa** [comment]
randseq и ttl  - ютуб работает,        гугл не пускает
pastseq          - ютую не работает,  гугл пускает 
tcp_check       - ютуб не работает,   гугл не пускает

**Comment by Waujito** [comment]
Закрываю. Программа многократно обновлялась с того времени, поставьте последнюю версию
