### ISSUE TITLE
Перезапись текущих конфигов на дефолтные при обновлении пакета в Openwrt

### ISSUE THREAD

**Issue by PulseDiver** [Waujito/youtubeUnblock#84]
При обновлении пакета на новую версию в openwrt перетираются текущие конфиги 
` /etc/init.d/youtubeUnblock` и `/usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft`

Можно ли сделать какую-то проверку, если есть уже конфиги, то чтоб не переписывались они дефолтными?

**Comment by Waujito** [comment]
Хм, интересно. Тут еще вопрос в том, что делать если я захочу что нибудь поменять в дальнейшем для старта. Из дефолтного - в install можно делать бекапы конфигов. Тогда он будет помещаться в файл config.conf -> config.conf~ если еще дальше хочется залезть, уже надо будет делать конфиг файлы в /etc

**Comment by insound** [comment]
По ману https://openwrt.org/docs/guide-developer/packages

**Comment by insound** [comment]
По ману https://openwrt.org/docs/guide-developer/packages

Конечно правильнее, лоадить конфиг, пусть и в формате флагов в процессе старта запускать функцию которая оверлоадит дефолт конфиг. Так ты принципе избежишь проблем в последующих обновлениях - те сможешь задать свои дефолт, а кто столкнется с проблемами своего старого конфига по ченджлогами причешет его.

**Comment by Waujito** [comment]
Я добавил конфигурацию через uci и luci, теперь конфиг будет сохраняться между версиями. К тому же, его не придётся писать в /etc/init.d скрипте.  Можете проверить на последнем development релизе, подробности - в readme, в секции openwrt

**Comment by ALexeyAL1** [comment]
Подскажите. У меня другая проблема. Мне наоборот нужно вернуть дефолтные настройки. Что бы не писать домены sni руками. Уже удалял и заново ставил анблок, но настройки сохраняются. А кнопку вернуть по умолчанию не нашел. Хотя это не сильно важно,я и руками настрою. Но в копилочку идей...

**Comment by Waujito** [comment]
> Подскажите. У меня другая проблема. Мне наоборот нужно вернуть дефолтные настройки. Что бы не писать домены sni руками. Уже удалял и заново ставил анблок, но настройки сохраняются. А кнопку вернуть по умолчанию не нашел. Хотя это не сильно важно,я и руками настрою. Но в копилочку идей...

На самом деле это, похоже, еще более важная проблема, чем сохранение при обновлении... Надо подумать над этим

**Comment by Waujito** [comment]
> Подскажите. У меня другая проблема. Мне наоборот нужно вернуть дефолтные настройки. Что бы не писать домены sni руками. Уже удалял и заново ставил анблок, но настройки сохраняются. А кнопку вернуть по умолчанию не нашел. Хотя это не сильно важно,я и руками настрою. Но в копилочку идей...

Я смог реализовать такое поведение. Сброс настроек доступен в файле /usr/share/youtubeUnblock/youtubeUnblock_default.sh и есть кнопочка в luci на сборке https://github.com/Waujito/youtubeUnblock/actions/runs/11308119925
