### ISSUE TITLE
Не работает при включённом Routing/NAT Offloading 

### ISSUE THREAD

**Issue by ashenzeroone** [Waujito/youtubeUnblock#85]
Заметил просадки по скорости с 500 до 200 mbps и повышение пинга после установки openWrt. Попробовал включить Routing/NAT Offloading (пробовал hardware\software), при включении не заходит на ютуб. Настройки стандартные.

**Comment by Waujito** [comment]
Увы, с этим ничего нельзя сделать. https://github.com/Waujito/youtubeUnblock/issues/23#issuecomment-2268791133

**Comment by bvasiliev** [comment]
В OpenWRT software offloading делается через
```
	flowtable ft {
		hook ingress priority filter
		devices = { ... }
		counter
	}

	chain forward {
		type filter hook forward priority filter; policy drop;
		meta l4proto { tcp, udp } flow add @ft
                ...
	}
```

Можно сделать выборочный offloading, поместив правило с queue в начало цепочки forward перед хуком ft.
Самый простой вариант: в файле /usr/share/nftables.d/ruleset-post/99-nfqws.nft заменить `mangle_forward` на `forward` — оно попадёт в самое начало цепочки при выполнении ruleset-post:

```add rule inet fw4 forward tcp dport 443 ct original packets < 20 counter queue num 537 bypass```

C hardware offloading ничего не сделать, но программный по производительности не должен сильно ему уступать.

**Comment by aegoroff** [comment]
А почему у меня при включенном NAT Offloading все работает?
![Снимок экрана от 2024-08-24 00-40-47](https://github.com/user-attachments/assets/66c72bb4-978c-4d1c-8436-822c647fc622)

**Comment by bvasiliev** [comment]
@aegoroff попробуйте разобраться почему.
Скорее всего, offloading у вас не работает.

**Comment by ashenzeroone** [comment]
Не совсем понял, у меня нет файла /usr/share/nftables.d/ruleset-post/99-nfqws.nft только 537-youtubeUnblock.nft

**Comment by ashenzeroone** [comment]
> Всё заработало, добавил строчку в файл 537-youtubeUnblock.nft
> 
> ```
> add rule inet fw4 forward tcp dport 443 ct original packets < 20 counter queue num 537 bypass
> insert rule inet fw4 mangle_forward tcp dport 443 ct original packets < 20 counter queue num 537 bypass
> insert rule inet fw4 output mark and 0x8000 == 0x8000 counter accept
> ```

А нет, ошибся, не помогло

**Comment by bvasiliev** [comment]
Моя ошибка, попробуйте изменить /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft так:

```
#!/usr/sbin/nft -f

insert rule inet fw4 forward tcp dport 443 ct original packets < 20 counter queue num 537 bypass
insert rule inet fw4 output mark and 0x8000 == 0x8000 counter accept
```

и применить `/etc/init.d/firewall restart`

Но в таком виде может проявиться #71 и выборочный offloading потребует более сложных правил. 
Например, дополнительный фильтр только по адресам Google и GGC.

**Comment by aegoroff** [comment]
> Скорее всего, offloading у вас не работает.

Это почему? как раз работает - без него процессоор сильно нагружен, а с ним все нормально. Выяснять я не хочу - принцип работает не трогай еще никто не отменял :)

**Comment by Waujito** [comment]
Не думаю, что software offliading вообще хоть как то может повлиять на ситуацию. При нём пакеты все равно будут идти через ядро, и поэтому скорость вряд ли сильно изменится. Другой вопрос, можно ли оффлоадинг сделать по вланам. К примеру, подключаем ко второму влану ТВ, вай фай, и они без оффлоадинга, с анблоком. А остальным, кто завязан на скорости, просто ставим оффлоадинг и на них уже гудбайдпи или ещё что нибудь. Другой вопрос, можно ли это сделать, но это уже детали реализации...

С прокси всё было бы проще, +1 к тому, чтобы его добавить.

Читал правила сверху и не понимаю, почему nftables вообще из принимает. Они идут в цепочку с типом filter, и как будто бы nfqueue там точно не место. iptables, к примеру, ругается, если так сделать. В целом, если продолжать по правилам, то можно их пробросить в отдельную цепочку с приоритетом filter-1, как мы уже это делали с pbr.

**Comment by aegoroff** [comment]
скорость конечно не меняется, меняется загруженность ЦП, - без него у меня проц очень сильно нагружен при большом потоке через роутер

**Comment by Waujito** [comment]
@aegoroff а youtubeUnblock точно работает?)

**Comment by aegoroff** [comment]
> а youtubeUnblock точно работает?)

точно работает. Ютуб есть и в журнале постоянно такое
```
Sat Aug 24 07:33:19 2024 daemon.info youtubeUnblock[16917]: Target SNI detected: rr4---sn-nx8xon3t-83ve.googlevideo.com
Sat Aug 24 07:33:19 2024 daemon.info youtubeUnblock[16917]: Packet split in portion 2 524
Sat Aug 24 07:33:19 2024 daemon.info youtubeUnblock[16917]: Packet split in portion 206 318
Sat Aug 24 07:36:12 2024 daemon.info youtubeUnblock[16917]: Target SNI detected: dl.google.com
Sat Aug 24 07:36:12 2024 daemon.info youtubeUnblock[16917]: Packet split in portion 2 563
Sat Aug 24 07:36:12 2024 daemon.info youtubeUnblock[16917]: Packet split in portion 530 33
Sat Aug 24 07:36:13 2024 daemon.info youtubeUnblock[16917]: Target SNI detected: geller-pa.googleapis.com
Sat Aug 24 07:36:13 2024 daemon.info youtubeUnblock[16917]: Packet split in portion 2 515
Sat Aug 24 07:36:13 2024 daemon.info youtubeUnblock[16917]: Packet split in portion 113 402
```

**Comment by aegoroff** [comment]
хотя возможно я неправ - я вообще отключил youtubeUnblock (удалив файлик для nfttables), перезапустил firewall, зашел в youtube - все работает, хотя небольшой тупеж (от нескольких секунд до минуты) при старте роликов имеется. Сообщений от youtubeUnblock в журнале естественно нет (тут ожидаемо, ибо мы выключили перенаправление).

Далее, выключаю offloading, обратно включаю youtubeUnblock, рестартую firewall, захожу в youtube - ролики начинают мгновенно стартовать (в логе сообщения от youtubeUnblock), но процессор начинает грузиться сильнее. Запускаю спидтест - загрузка выше 40-50%. Включаю offloading, - загрузка падает до нуля, при спидтесте. Проверил старт роликов, штук 30 разных - стартуют мгновенно. Мутно все это

**Comment by bvasiliev** [comment]
С offload первый пакет всё равно пройдёт через правила netfilter и попадёт в queue с youtubeUnblock, что и может быть видно в логе https://github.com/Waujito/youtubeUnblock/issues/85#issuecomment-2308103242. А вот следующие, необходимые youtubeUnblock для успешной ~~атаки~~ работы, могут уже не попадать в очередь.

**Comment by aegoroff** [comment]
@bvasiliev да, очевидно вы правы, но для меня загадка почему при выключенном youtubeUnblock у меня ютуб работает? хотя и с затупами при старте (не всегда)

**Comment by Waujito** [comment]
Первый пакет это разве не SYN?

**Comment by ashenzeroone** [comment]
Считаю вопрос решённым, с данным правилом и включенным software offloading всё работает, пинг и скорости стабильны.
Спасибо за помощь господа!
![Screenshot 2024-08-24 225749](https://github.com/user-attachments/assets/bedbaaab-cf66-4a99-90a8-e3823da32c64)


> Моя ошибка, попробуйте изменить /usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft так:
> 
> ```
> #!/usr/sbin/nft -f
> 
> insert rule inet fw4 forward tcp dport 443 ct original packets < 20 counter queue num 537 bypass
> insert rule inet fw4 output mark and 0x8000 == 0x8000 counter accept
> ```
> 
> и применить `/etc/init.d/firewall restart`
> 
> Но в таком виде может проявиться #71 и выборочный offloading потребует более сложных правил. Например, дополнительный фильтр только по адресам Google и GGC.

**Comment by ashenzeroone** [comment]
> Мозг подсказывает что оно не должно работать, но как сказали выше, работает - не трогаем :)
> 
> Upd. Скорее, не до конца вчитался в сообщение. Если правило действительно заработало - это хорошо, мне больше удивительно, что software offloading спасает скорость

И пинг!
