### ISSUE TITLE
Как запустить с флагом --sni-domains=all ?

### ISSUE THREAD

**Issue by AMAT0RY** [Waujito/youtubeUnblock#86]
Не понимаю, как запустить с флагом --sni-domains=all на OpenWrt, пробовал так 

/etc/init.d/youtubeUnblock start --sni-domains=all

но ничего не меняется

**Comment by Waujito** [comment]
Да, так неправильно. Необходимо внутри файла прописать аргументы (мне всё таки очень нужно разобраться с конфигами)

**Comment by suffermuffin** [comment]
Я неделю менял параметры при инициализации и не понимал, почему ничего не работает на тв, наткнулся на это обсуждение и всё стало на свои места. Надо в разделе #flags уточнить-таки.

В общем, пошаговая инструкция для openwrt, если ещё надо:

1. Открываем текстовым редактором "/etc/init.d/youtubeUnblock":
```
root@OpenWrt:~# nano /etc/init.d/youtubeUnblock
```
2. Файл выглядит так:
```
#!/bin/sh /etc/rc.common
USE_PROCD=1

START=50
STOP=50

# Openwrt procd script: https://openwrt.org/docs/guide-developer/procd-init-script-example
# The program should be put into /usr/bin/
# This file should be put into /etc/init.d/


start_service() {
        procd_open_instance
        procd_set_param command /usr/bin/youtubeUnblock

        procd_set_param nice -20

        procd_set_param stdout 1
        procd_set_param stderr 1

        procd_close_instance
}

```
В нём после ` procd_set_param command /usr/bin/youtubeUnblock` ставим нужные параметры, в нашем случае это будет:

...
start_service() {
        procd_open_instance
        procd_set_param command /usr/bin/youtubeUnblock --sni-domains=all
        ...
}

3. Сохраняем ctrl+O (в случае nano, в vim ":qw")
4. Запускаем
5.???
6. Profit

**Comment by Waujito** [comment]
Упомянул это в readme

**Comment by Waujito** [comment]
Ломает другие сайты?

**Comment by Waujito** [comment]
> Только Ethernet так, с WiFi все хорошо. Еще госуслуги и ржд не работает.

Странно. Попробуйте скачать последнююий пре-релиз и попробовать с ним

**Comment by Waujito** [comment]
Подтверждаю, что госуслуги не работают. Это проблема скорее госуслуг, чем анблока. Там, видимо, стоят свои фаерволы, которые блокируют всё подозрительное.

У меня всё решается через sni domains = all, exclude domains=.ru

Я добавил поддержку для интерфейса роутера, можете там прописывать всё
