### ISSUE TITLE
daemon.info youtubeUnblock[19698]: ip4_payload_split: ipversion: Invalid argument

### ISSUE THREAD

**Issue by 31337cat** [Waujito/youtubeUnblock#88]
Здравствуйте.
Не работает - youtubeUnblock 
В журнале вижу постоянное сообщение - ip4_payload_split: ipversion: Invalid argument
Архитектура - DISTRIB_ARCH='mipsel_24kc
OpenWrt 23.05.3 r23809-234f1a2efa 

устанавливался пакет - youtubeUnblock-0.3.0-78ed6a1-mipsel_24kc-openwrt-23.05.ipk

root@OpenWrt:~# nft list ruleset
table inet fw4 {
        ct helper amanda {
                type "amanda" protocol udp
                l3proto inet
        }

        ct helper RAS {
                type "RAS" protocol udp
                l3proto inet
        }

        ct helper Q.931 {
                type "Q.931" protocol tcp
                l3proto inet
        }

        ct helper irc {
                type "irc" protocol tcp
                l3proto ip
        }

        ct helper pptp {
                type "pptp" protocol tcp
                l3proto ip
        }

        ct helper sip {
                type "sip" protocol udp
                l3proto inet
        }

        ct helper snmp {
                type "snmp" protocol udp
                l3proto ip
        }

        ct helper tftp {
                type "tftp" protocol udp
                l3proto inet
        }

        chain input {
                type filter hook input priority filter; policy accept;
                iifname "lo" accept comment "!fw4: Accept traffic from loopback"
                ct state established,related accept comment "!fw4: Allow inbound established and related flows"
                tcp flags syn / fin,syn,rst,ack jump syn_flood comment "!fw4: Rate limit TCP syn packets"
                iifname "br-lan" jump input_lan comment "!fw4: Handle lan IPv4/IPv6 input traffic"
                iifname { "wan", "pppoe-RT" } jump input_wan comment "!fw4: Handle wan IPv4/IPv6 input traffic"
        }

        chain forward {
                type filter hook forward priority filter; policy drop;
                ct state established,related accept comment "!fw4: Allow forwarded established and related flows"
                iifname "br-lan" jump forward_lan comment "!fw4: Handle lan IPv4/IPv6 forward traffic"
                iifname { "wan", "pppoe-RT" } jump forward_wan comment "!fw4: Handle wan IPv4/IPv6 forward traffic"
                jump upnp_forward comment "Hook into miniupnpd forwarding chain"
                jump handle_reject
        }

        chain output {
                type filter hook output priority filter; policy accept;
                meta mark & 0x00008000 == 0x00008000 counter packets 0 bytes 0 accept
                oifname "lo" accept comment "!fw4: Accept traffic towards loopback"
                ct state established,related accept comment "!fw4: Allow outbound established and related flows"
                oifname "br-lan" jump output_lan comment "!fw4: Handle lan IPv4/IPv6 output traffic"
                oifname { "wan", "pppoe-RT" } jump output_wan comment "!fw4: Handle wan IPv4/IPv6 output traffic"
        }

        chain prerouting {
                type filter hook prerouting priority filter; policy accept;
                iifname "br-lan" jump helper_lan comment "!fw4: Handle lan IPv4/IPv6 helper assignment"
        }

        chain handle_reject {
                meta l4proto tcp reject with tcp reset comment "!fw4: Reject TCP traffic"
                reject comment "!fw4: Reject any other traffic"
        }

        chain syn_flood {
                limit rate 25/second burst 50 packets return comment "!fw4: Accept SYN packets below rate-limit"
                drop comment "!fw4: Drop excess packets"
        }

        chain input_lan {
                ct status dnat accept comment "!fw4: Accept port redirections"
                jump accept_from_lan
        }

        chain output_lan {
                jump accept_to_lan
        }

        chain forward_lan {
                jump accept_to_wan comment "!fw4: Accept lan to wan forwarding"
                ct status dnat accept comment "!fw4: Accept port forwards"
                jump accept_to_lan
        }

        chain helper_lan {
                udp dport 10080 ct helper set "amanda" comment "!fw4: Amanda backup and archiving proto"
                udp dport 1719 ct helper set "RAS" comment "!fw4: RAS proto tracking"
                tcp dport 1720 ct helper set "Q.931" comment "!fw4: Q.931 proto tracking"
                meta nfproto ipv4 tcp dport 6667 ct helper set "irc" comment "!fw4: IRC DCC connection tracking"
                meta nfproto ipv4 tcp dport 1723 ct helper set "pptp" comment "!fw4: PPTP VPN connection tracking"
                udp dport 5060 ct helper set "sip" comment "!fw4: SIP VoIP connection tracking"
                meta nfproto ipv4 udp dport 161 ct helper set "snmp" comment "!fw4: SNMP monitoring connection tracking"
                udp dport 69 ct helper set "tftp" comment "!fw4: TFTP connection tracking"
        }

        chain accept_from_lan {
                iifname "br-lan" counter packets 390 bytes 38290 accept comment "!fw4: accept lan IPv4/IPv6 traffic"
        }

        chain accept_to_lan {
                oifname "br-lan" counter packets 25 bytes 1704 accept comment "!fw4: accept lan IPv4/IPv6 traffic"
        }

        chain input_wan {
                meta nfproto ipv4 udp dport 68 counter packets 0 bytes 0 accept comment "!fw4: Allow-DHCP-Renew"
                icmp type echo-request counter packets 0 bytes 0 accept comment "!fw4: Allow-Ping"
                meta nfproto ipv4 meta l4proto igmp counter packets 27 bytes 864 accept comment "!fw4: Allow-IGMP"
                meta nfproto ipv6 udp dport 546 counter packets 0 bytes 0 accept comment "!fw4: Allow-DHCPv6"
                ip6 saddr fe80::/10 icmpv6 type . icmpv6 code { mld-listener-query . no-route, mld-listener-report . no-route, mld-listener-done . no-route, mld2-listener-report . no-route } counter packets 0 bytes 0 accept comment "!fw4: Allow-MLD"
                icmpv6 type { destination-unreachable, time-exceeded, echo-request, echo-reply, nd-router-solicit, nd-router-advert } limit rate 1000/second counter packets 0 bytes 0 accept comment "!fw4: Allow-ICMPv6-Input"
                icmpv6 type . icmpv6 code { packet-too-big . no-route, parameter-problem . no-route, nd-neighbor-solicit . no-route, nd-neighbor-advert . no-route, parameter-problem . admin-prohibited } limit rate 1000/second counter packets 0 bytes 0 accept comment "!fw4: Allow-ICMPv6-Input"
                ct status dnat accept comment "!fw4: Accept port redirections"
                jump reject_from_wan
        }

        chain output_wan {
                jump accept_to_wan
        }

        chain forward_wan {
                icmpv6 type { destination-unreachable, time-exceeded, echo-request, echo-reply } limit rate 1000/second counter packets 0 bytes 0 accept comment "!fw4: Allow-ICMPv6-Forward"
                icmpv6 type . icmpv6 code { packet-too-big . no-route, parameter-problem . no-route, parameter-problem . admin-prohibited } limit rate 1000/second counter packets 0 bytes 0 accept comment "!fw4: Allow-ICMPv6-Forward"
                meta l4proto esp counter packets 0 bytes 0 jump accept_to_lan comment "!fw4: Allow-IPSec-ESP"
                udp dport 500 counter packets 0 bytes 0 jump accept_to_lan comment "!fw4: Allow-ISAKMP"
                ct status dnat accept comment "!fw4: Accept port forwards"
                jump reject_to_wan
        }

        chain accept_to_wan {
                meta nfproto ipv4 oifname { "wan", "pppoe-RT" } ct state invalid counter packets 3 bytes 120 drop comment "!fw4: Prevent NAT leakage"
                oifname { "wan", "pppoe-RT" } counter packets 1055 bytes 76296 accept comment "!fw4: accept wan IPv4/IPv6 traffic"
        }

        chain reject_from_wan {
                iifname { "wan", "pppoe-RT" } counter packets 65 bytes 2808 jump handle_reject comment "!fw4: reject wan IPv4/IPv6 traffic"
        }

        chain reject_to_wan {
                oifname { "wan", "pppoe-RT" } counter packets 0 bytes 0 jump handle_reject comment "!fw4: reject wan IPv4/IPv6 traffic"
        }

        chain dstnat {
                type nat hook prerouting priority dstnat; policy accept;
                iifname "br-lan" jump dstnat_lan comment "!fw4: Handle lan IPv4/IPv6 dstnat traffic"
                iifname { "wan", "pppoe-RT" } jump dstnat_wan comment "!fw4: Handle wan IPv4/IPv6 dstnat traffic"
                jump upnp_prerouting comment "Hook into miniupnpd prerouting chain"
        }

        chain srcnat {
                type nat hook postrouting priority srcnat; policy accept;
                oifname "br-lan" jump srcnat_lan comment "!fw4: Handle lan IPv4/IPv6 srcnat traffic"
                oifname { "wan", "pppoe-RT" } jump srcnat_wan comment "!fw4: Handle wan IPv4/IPv6 srcnat traffic"
                jump upnp_postrouting comment "Hook into miniupnpd postrouting chain"
        }

        chain dstnat_lan {
                ip saddr 192.168.9.0/24 ip daddr XX.XX.XX.XX tcp dport 56923 dnat ip to 192.168.9.2:56923 comment "!fw4: Foobar UpNP (reflection)"
                ip saddr 192.168.9.0/24 ip daddr XX.XX.XX.XX tcp dport 19371 dnat ip to 192.168.9.2:19371 comment "!fw4: Monkey (reflection)"
        }

        chain srcnat_lan {
                ip saddr 192.168.9.0/24 ip daddr 192.168.9.2 tcp dport 56923 snat ip to 192.168.9.1 comment "!fw4: Foobar UpNP (reflection)"
                ip saddr 192.168.9.0/24 ip daddr 192.168.9.2 tcp dport 19371 snat ip to 192.168.9.1 comment "!fw4: Monkey (reflection)"
        }

        chain dstnat_wan {
                meta nfproto ipv4 tcp dport 56923 counter packets 0 bytes 0 dnat ip to 192.168.9.2:56923 comment "!fw4: Foobar UpNP"
                meta nfproto ipv4 tcp dport 19371 counter packets 0 bytes 0 dnat ip to 192.168.9.2:19371 comment "!fw4: Monkey"
        }

        chain srcnat_wan {
                meta nfproto ipv4 masquerade comment "!fw4: Masquerade IPv4 wan traffic"
        }

        chain raw_prerouting {
                type filter hook prerouting priority raw; policy accept;
        }

        chain raw_output {
                type filter hook output priority raw; policy accept;
        }

        chain mangle_prerouting {
                type filter hook prerouting priority mangle; policy accept;
        }

        chain mangle_postrouting {
                type filter hook postrouting priority mangle; policy accept;
        }

        chain mangle_input {
                type filter hook input priority mangle; policy accept;
        }

        chain mangle_output {
                type route hook output priority mangle; policy accept;
        }

        chain mangle_forward {
                type filter hook forward priority mangle; policy accept;
                iifname { "wan", "pppoe-RT" } tcp flags syn tcp option maxseg size set rt mtu comment "!fw4: Zone wan IPv4/IPv6 ingress MTU fixing"
                oifname { "wan", "pppoe-RT" } tcp flags syn tcp option maxseg size set rt mtu comment "!fw4: Zone wan IPv4/IPv6 egress MTU fixing"
                tcp dport 443 ct original packets < 20 counter packets 1543 bytes 165723 queue flags bypass to 537
        }

        chain upnp_forward {
        }

        chain upnp_prerouting {
        }

        chain upnp_postrouting {
        }
}
table inet nft-qos-monitor {
        chain upload {
                type filter hook postrouting priority filter; policy accept;
                ip saddr 192.168.9.2 counter packets 90599 bytes 13271843
                ip saddr 192.168.9.3 counter packets 87976 bytes 14720704
                ip saddr 192.168.9.168 counter packets 6748 bytes 735225
        }

        chain download {
                type filter hook prerouting priority filter; policy accept;
                ip daddr 192.168.9.2 counter packets 120846 bytes 118513680
                ip daddr 192.168.9.3 counter packets 178335 bytes 206307909
                ip daddr 192.168.9.168 counter packets 53230 bytes 76433651
        }
}
table inet nft-qos-static {
        chain upload {
                type filter hook postrouting priority filter; policy accept;
        }

        chain download {
                type filter hook prerouting priority filter; policy accept;

**Comment by Waujito** [comment]
Отключите ipv6

**Comment by 31337cat** [comment]
Пошел читать мануалы. Через LUCI не отключить (.

**Comment by 31337cat** [comment]
А нет. Я дурак)  Есть в интерфейсе - просто название не адекватное.
![изображение](https://github.com/user-attachments/assets/0af61df4-1c85-430c-923b-bfbbd3aeb3c0)

Отключил.
Перезагрузил роутер  -Всё работает.
Огромное Вам Спасибо за вашу работу.

**Comment by a3r5** [comment]
Спасибо за программу !

Отказываться от ipv6 , не вижу смысла.

У меня стоит как я понял последний билд https://github.com/Waujito/youtubeUnblock/actions/runs/10863253494 , youtubeUnblock-0.3.2-85d3843-aarch64_cortex-a53-openwrt-23.05.ipk .

Сообщения в логе те же:
```
ip4_payload_split: ipversion: Invalid argument
Target SNI detected: “e.t.c”
```

Лог у меня и так всегда отключен, что бы избежать износа флеш памяти , если я правильно понимаю.
Но можно ли как то отключить этот вывод в лог , чтобы не спамил ? Или не обращать внимания и  выключить log.service  ?

**Comment by a3r5** [comment]
[10863253494](https://github.com/Waujito/youtubeUnblock/actions/runs/10863253494)

**Comment by a3r5** [comment]
@Waujito

> Отключите ipv6

Спасибо за программу !

Хотелось бы, оставить ipv6.

Лог у меня и так всегда отключен, что бы избежать износа флеш памяти , если я правильно понимаю.

Можно ли как то отключить этот вывод в лог , чтобы не спамил ?
Или не обращать внимания и выключить log.service ?

У меня стоит как я понял последний билд [10863253494](https://github.com/Waujito/youtubeUnblock/actions/runs/10863253494) , youtubeUnblock-0.3.2-85d3843-aarch64_cortex-a53-openwrt-23.05.ipk .

Сообщения в логе , те же:

```
ip4_payload_split: ipversion: Invalid argument
Target SNI detected: “e.t.c”
```
