### ISSUE TITLE
kernel module

### ISSUE THREAD

**Issue by vurdng** [Waujito/youtubeUnblock#89]
Заметил в исходниках код модуля для xtables, но о нем никаких комментариев в описании и дата обновления 3 недели назад. Я правильно понимаю, что вы начали его писать, но в итоге выбрали вариант с NFQUEUE? Было бы замечательно делать это в ядре, это по идеи было бы быстрее и меньше ресурсов жрало. Поясните, пожалуйста.

**Comment by Waujito** [comment]
Я его начал после того как столкнулся с проблемами производительности nfqueue, но потом придумал считать пакеты для nftables и мне подсказали про коннбайтс в iptables. Я его продолжу, но на данный момент есть более высокие приоритеты.

**Comment by Waujito** [comment]
Уговорили, сяду за модуль))
Он был рабочим сначала, но потом я на него забил. Его надо обновлять под последнюю версию, адаптировать под openwrt, и добавлять конфигурацию.

**Comment by renr4** [comment]
Если получится под openwrt, то я бы мог затестить на падаване и выложить сборку (там немного другой формат mipsel FPU), ну или объяснить как собрать. Хотя в openwrt есть флаг `CONFIG_KERNEL_MIPS_FPU_EMULATOR`, но я не уверен, что оно так заработает, потому что ядра совсем разные.

**Comment by Waujito** [comment]
@renr4 А у вас получалось собрать модуль для OpenWRT? Также, если /lib/xtables ro, может быть, получится с `XTABLES_LIBDIR=/opt/lib/xtables`?

Если можете быстро собрать модуль, можете попробовать, я обновил его для IPv4 и IPv6 (тестировал только на TCP)

**Comment by Waujito** [comment]
И еще я вообще не уверен за nftables. Насколько я понял, там нет такого же интерфейса с расширениями, как для iptables, а значит что всё решается через переборку юзерспейс утилиты. Но там вроде как есть libnftnl, который может сразу ядру сказать что нам надо. В общем, тут еще надо смотреть.

**Comment by renr4** [comment]
Модуль пока не получилось собрать, много ошибок, но если будет результат, отпишусь.

Пробовал еще раз юзерспейс на падаване. Оказывается можно собрать все нужные модули и просто закинуть на роутер. `xt_NFQUEUE.ko`, `nfnetlink_queue.ko`, `nfnetlink.ko`, `xt_connbytes.ko` добавляются без проблем. Правила iptables тоже ок. youtubeUnblock запускается, никаких ошибок. Но не работает. Код останавливается на функции `mnl_socket_recvfrom()`, т.е. она ждет, что придут пакеты, но они не приходят.

**Comment by renr4** [comment]
Кстати локально на убунте 22.04 модуль без проблем собирается и работает!
На openwrt пока не пробовал. На падаване крашится ядро.

**Comment by renr4** [comment]
Ядро падает в функциях `netproto_version()`, `ip4_payload_split` и т.д., т.е. там, где происходит парсинг пакета. Собственно именно с этим я и столкнулся, когда игрался с `nf_register_hook()`.

А может быть это связано с архитектурой системы? x86, к примеру, дает правильные значения, а на mipsel что-то не то?

**Comment by Waujito** [comment]
У меня openwrt 23.05 kernel 5.15 mipsel на роутере летало (но вначале роутер умер из за трейс логов) Там проблемы со сборкой начинаются для старых ядер, на них половина интерфейса другая

**Comment by renr4** [comment]
На свежей openwrt вполне возможно все работает. Будет время, может проверю.
На падаване старое ядро 3.4, там кое-что отличается, к примеру нет функции `iov_iter_kvec`, хотя и без нее работает:) Еще у `ykb_nf_hook` немного другие параметры. Но openwrt мне не интересна.
Надо почитать про skb_linearize и вообще про разбор заголовков, может что придет в голову.

**Comment by Waujito** [comment]
До четвёртой версии ядра полёт нормальный.
https://github.com/Waujito/youtubeUnblock/actions/runs/10666295109

**Comment by Waujito** [comment]
@renr4 
Проверьте на своём третьем ядре. У меня на виртуалке вроде бы работает. Еще попробуйте faking_strategy=md5sum. Он у меня локально без проблем работает, а на виртуалке даёт ошибки в dmesg. Возможно, проблема в виртуализации.
