### ISSUE TITLE
Не работает с DoH в openwrt

### ISSUE THREAD

**Issue by nejtr0n** [Waujito/youtubeUnblock#91]
В дефолтных настройках не отрабатывает через DoH. Просто зависает на pending первого запроса.
Возможно ли как то прокинуть флаг с dns для резолва хостов, указанных в sni-domains?

**Comment by Waujito** [comment]
youtubeUnblock никак не взаимодействует и не зависит от dns. Он определяет домены в sni-domains точно так же, как это делает ТСПУ. Вообще, по идее запросы DoH не должны попадать в youtubeUnblock на настройках по умолчанию, так как они идут через цепочки input-output. Может быть, провайдер блокирует DoH? Или просто youtubeUnblock ломается на настройках по умолчанию? Тогда необходимо будет поиграть с флагами.

**Comment by nejtr0n** [comment]
Не работают только домены из списка sni domains.
Мне кажется дело в nft правилах.Так как DoH и youtubeUnblock по 443 работают, то трафик резолва залетает в youtubeunblock. Попробую поискать doh на другом порту и отпишусь о результатх

**Comment by nejtr0n** [comment]
По каким то причинам заработало. Возможно что то не так настроил изначально. Спасибо большое!
