### ISSUE TITLE
Не работают не могу подобрать стратегию ЛНР

### ISSUE THREAD

**Issue by foxy544** [Waujito/youtubeUnblock#94]
GoodDPI работает по умолчанию режим -9
![dpi](https://github.com/user-attachments/assets/a5bab53e-caa1-4926-a2e7-249f799f2393)
пробывал 
/usr/bin/youtubeUnblock --frag-middle-sni=0 --frag-sni-pos=1 --faking-strategy=ttl --faking-ttl=5
и по умолчанию
и стратегии все перебирал не работает и все

**Comment by foxy544** [comment]
![router](https://github.com/user-attachments/assets/3012f1b1-c2c2-459d-a8ee-3c4630d4fd50)

**Comment by Waujito** [comment]
Как будто бы, `--faking-strategy=pastseq` или `--faking-strategy=tcp_check` должен решать проблему. В GoodbyeDPI еще и quic блокируется на -9, но я рекомендую отключить его в браузере (в README в Troubleshooting написано как). Возможно, поможет еще и `--frag-middle-sni=0`, хотя вряд ли.

**Comment by Waujito** [comment]
Кстати, еще может быть вероятность, что у вас ipv6 используется. Попробуйте отсюда скачать https://github.com/Waujito/youtubeUnblock/actions/runs/10582327899

**Comment by foxy544** [comment]
ipv6 выключен, у провайдера нет v6,  3 мобилки, 2 телеки и мак на всем не работает
Experimental QUIC protocol конечно выключен

**Comment by Waujito** [comment]
GoodbyeDPI с `-e 2 --wrong-seq --reverse-frag -q` будет работать?

**Comment by foxy544** [comment]
![tcp](https://github.com/user-attachments/assets/72311abf-6fee-4a95-a984-21ba594e8192)

root@RouteRich:~# /etc/init.d/youtubeUnblock restart
root@RouteRich:~# /etc/init.d/youtubeUnblock stop
root@RouteRich:~# /etc/init.d/youtubeUnblock start
root@RouteRich:~# /etc/init.d/firewall  restart
Automatically including '/usr/share/nftables.d/ruleset-post/537-youtubeUnblock.nft'
root@RouteRich:~# /etc/init.d/firewall  restart

![Uploading log.jpg…]()

**Comment by foxy544** [comment]
![log](https://github.com/user-attachments/assets/0526d0fd-4339-4f16-b378-1a4b3e2f92a9)

**Comment by foxy544** [comment]
-e 2 --wrong-seq --reverse-frag -q 
![gooddpi](https://github.com/user-attachments/assets/fa0c5304-81e3-43bc-94a9-987da10fdc78)
да работает

**Comment by foxy544** [comment]
на телеках smarttube, youtube, помогает powertunnel с настройками по умолчанию, или wireguard

**Comment by Waujito** [comment]
Попробуйте проверить с флагами `youtubeUnblock --frag-sni-pos=1 --sni-domains=all`

**Comment by Waujito** [comment]
> Аналогичная проблема. Не получается подобрать конфиг. для GoodByeDPI рабочий вариант -9 --fake-gen 5. Можете подсказать как воспроизвести его поведение? Выше указанные не работают.

Напишите мне в личку https://t.me/waujito
Я попрошу развернуть у себя на машине (нужен линукс, возможно, wsl тоже пойдёт) docker контейнер с openvpn и сам посижу на вашем IP адресе

**Comment by aden16rus** [comment]
аналогичная история, на ноуте арч spoofdpi работает из коробки, на винде goodbyedpi тоже работает по умолчанию с ключом -9, а вот при попытке заюзать zapret на ноуте и ваш youtubeunblock на роутере ни то ни то не заводится ни с какими настройками, причем у zapret есть сканер с перебором всевозможных настроек и он не смог найти рабочий вариант, прям мистика что же у них такого реализовано что у вас и в zapret не включается ни одной настройкой

**Comment by Waujito** [comment]
> аналогичная история, на ноуте арч spoofdpi работает из коробки, на винде goodbyedpi тоже работает по умолчанию с ключом -9, а вот при попытке заюзать zapret на ноуте и ваш youtubeunblock на роутере ни то ни то не заводится ни с какими настройками, причем у zapret есть сканер с перебором всевозможных настроек и он не смог найти рабочий вариант, прям мистика что же у них такого реализовано что у вас и в zapret не включается ни одной настройкой

seg2delay 100 и frag sni reverse 0
