### ISSUE TITLE
Отдельное правило для TV

### ISSUE THREAD

**Issue by valeri2** [Waujito/youtubeUnblock#95]
Имеем роутер с OpenWRT.
При запуске youtubeUnblock с параметрами по умолчанию заработало без тормозов везде, кроме TV.

Последовал совету из Readme, добавил аргумент --faking-strategy=ttl заработало и на TV, но сломалось приложение Youtube на Android смартфонах.

Напрашивается запустить на роутере отдельный экземпляр youtubeUnblock на другую queue и вручную прописать правила в iptables на ip телевизора.

Может есть более элегантное решение?

**Comment by Waujito** [comment]
Есть --faking-strategy=pastseq :)

**Comment by valeri2** [comment]
А я послушно следовал инструкции для TV. ))
Да, вроде везде заработало с pastseq, соображает медленнее, но качество видео не страдает.
Спасибо, пока поживу с этим флагом, понаблюдаю.

**Comment by suffermuffin** [comment]
Мне более низкое значение ttl помогло (поставил --faking-ttl=4), быстро работает везде, однако слегка медленнее прогружает чем при дефолтных настройках, но не критично.

**Comment by valeri2** [comment]
Нет, все таки буду отдельный экземпляр настраивать. 
С pastseq иногда крайне раздражающие зависания. faking-ttl тоже разные пробовал, не помогает.
И именно на Android почему-то, такие проблемы у меня.

**Comment by Waujito** [comment]
Может, зависания из-за того, что ТВ пытается на quic прыгать? 
Попробуйте заблокировать его
```
nft insert rule inet fw4 output udp dport 443 counter drop
```

**Comment by andreysiznet** [comment]
Подскажите пожалуйста, dpi на debian12 работает все кроме samsung и lg?

**Comment by Waujito** [comment]
> Подскажите пожалуйста, dpi на debian12 работает все кроме samsung и lg?

Всё должно работать, ищите в обсуждениях.

**Comment by Waujito** [comment]
Закрою ишью, много чего обновилось с того времени, тут не актуально

**Comment by leonya1122** [comment]
решил проблему для tizen OS. Для youtubeUnblock 1.1.0 нужно создать 2 профиля настроек, один для входа в приложение и авторизации, второй для загрузки видео. Оба профиля должны быть активны.
1. Для входа: домены ggpht.com ytimg.com youtube.com play.google.com googleapis.com googleusercontent.com gstatic.com l.google.com, флаг Faking strategy=tcp_check, остальное по умолчанию
2. Для воспроизведения видео: домены googlevideo.com youtu.be, остальные настройки по умолчанию.

активируйте оба профиля одновременно и на телевизорах samsung будет работать. Но при этом на компьютере и телефоне отвалилось. Может получится решить эту проблему.

Настройки подобраны опытным путем, методом проб и ошибок. Все остальные советы из интернета не помогли, поэтому делюсь. Если есть решение сразу для всех устройств - буду рад посмотреть. Пока выход - создание отдельного профиля для пк телефона и отдельно для телевизора

**Comment by leonya1122** [comment]
PS, заработало при таких настройка на ПК и телефоне пока писал пост, одуплился видимо. Поэтому можете смело брать конфиги

**Comment by KowalskiVevo** [comment]
> решил проблему для tizen OS. Для youtubeUnblock 1.1.0 нужно создать 2 профиля настроек, один для входа в приложение и авторизации, второй для загрузки видео. Оба профиля должны быть активны.
> 
>     Для входа: домены ggpht.com ytimg.com youtube.com play.google.com googleapis.com googleusercontent.com gstatic.com l.google.com, флаг Faking strategy=tcp_check, остальное по умолчанию
>     Для воспроизведения видео: домены googlevideo.com youtu.be, остальные настройки по умолчанию.
> 
> активируйте оба профиля одновременно и на телевизорах samsung будет работать. Но при этом на компьютере и телефоне отвалилось. Может получится решить эту проблему.
> 
> Настройки подобраны опытным путем, методом проб и ошибок. Все остальные советы из интернета не помогли, поэтому делюсь. Если есть решение сразу для всех устройств - буду рад посмотреть. Пока выход - создание отдельного профиля для пк телефона и отдельно для телевизора

Попробовал также, сейчас начало пускать в ютуб на Android TV, превьюшки на видосах есть, но само видео не грузит((
(на обычном андройде и в браузере работает без проблем)

UPD: Крч, отказался от этой затеи, вернул все на свои места, просто для дефолтного профиля YouTube поменял Faking strategy на tcp_check и все завелось
