### ISSUE TITLE
Установка на роутер TP-Link

### ISSUE THREAD

**Issue by Symbiote2099** [Waujito/youtubeUnblock#99]
Приветствую . Можно ли установить youtubeunblock на роутер TP-Link? В моём случае это TP-Link Archer AX73 v1.0. Я абсолютный чайник в этом плане. Интернет говорит, что эти роутеры на операционной системе OpenWRT, но я не смог найти примерно похожих пунктов. Разве что "файл обновления прошивки", но я сомневаюсь, что это оно. Пункта "Автозагрузка" или что-то похожее не нашёл вовсе. Если поможете инструкцией для такого чайника, как я, буду очень признателен.
![image](https://github.com/user-attachments/assets/6523dd9c-8d2c-4270-9ad6-322d0ee8c3b4)

**Comment by Waujito** [comment]
тп линк - самая ужасная вещь, которая только может быть. Ладно мы можем закрыть глаза на NDA, но они могли хотя бы дать хоть какой нибудь доступ к оборудованию. 

В любом случае, мы можем рутить его через эксплойт:
https://4pda.to/forum/index.php?showtopic=1013145&st=8560#entry124480880

Я для своего AX1500 выложил инструкцию с рутингом и сборкой анблока в него:
https://github.com/Waujito/TPLlAX1500GPL

А вообще сборка нужна только для модуля в ядро, статические бинарники для arm64 также должны работать (они есть в релизах)
